<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

enum ControlledDataCode: string
{
    case consignee_city = 'consignee-city';
    case servicepoint_facilityId = 'servicepoint-facilityId';
    case servicepoint_url = 'servicepoint-url';
    case shipper_city = 'shipper-city';
    case signatory_name = 'signatory-name';
}
