<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\MalformedDataException;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\None;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class DgfAirport implements SelfNormalizingModel
{
    /**
     * @param Option<string>           $dgfLocationCode
     * @param Option<string>           $countryCode
     * @param Option<string>           $dgfLocationName
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $dgfLocationCode,
        private Option $countryCode,
        private Option $dgfLocationName,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): DgfAirportBuilder
    {
        return new DgfAirportBuilder(None::create(), None::create(), None::create(), []);
    }

    /**
     * Airport of departure/destination in IATA code format.
     *
     * @return Option<string>
     */
    public function getDgfLocationCode(): Option
    {
        return $this->dgfLocationCode;
    }

    /**
     * Code specifying the country using ISO 3166-1 alpha-2.
     *
     * @return Option<string>
     */
    public function getCountryCode(): Option
    {
        return $this->countryCode;
    }

    /**
     * The name of the location.
     *
     * @return Option<string>
     */
    public function getDgfLocationName(): Option
    {
        return $this->dgfLocationName;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $dgfLocationCode = None::create();
        $countryCode = None::create();
        $dgfLocationName = None::create();
        if (array_key_exists('dgf:locationCode', $data) && $data['dgf:locationCode'] !== null) {
            $dgfLocationCodeRaw = $data['dgf:locationCode'];
            if (!is_string($dgfLocationCodeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "dgf:locationCode" must be string, got %s.', get_debug_type($dgfLocationCodeRaw)),
                );
            }
            $dgfLocationCode = Some::create($dgfLocationCodeRaw);
        }
        if (array_key_exists('countryCode', $data) && $data['countryCode'] !== null) {
            $countryCodeRaw = $data['countryCode'];
            if (!is_string($countryCodeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "countryCode" must be string, got %s.', get_debug_type($countryCodeRaw)),
                );
            }
            $countryCode = Some::create($countryCodeRaw);
        }
        if (array_key_exists('dgf:locationName', $data) && $data['dgf:locationName'] !== null) {
            $dgfLocationNameRaw = $data['dgf:locationName'];
            if (!is_string($dgfLocationNameRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "dgf:locationName" must be string, got %s.', get_debug_type($dgfLocationNameRaw)),
                );
            }
            $dgfLocationName = Some::create($dgfLocationNameRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            ['dgf:locationCode' => true, 'countryCode' => true, 'dgf:locationName' => true],
        );

        return new self($dgfLocationCode, $countryCode, $dgfLocationName, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dgfLocationCodeOption = $this->dgfLocationCode;
        if ($dgfLocationCodeOption->isDefined()) {
            $dgfLocationCode = $dgfLocationCodeOption->get();
            $dataArray['dgf:locationCode'] = $dgfLocationCode;
        }
        $countryCodeOption = $this->countryCode;
        if ($countryCodeOption->isDefined()) {
            $countryCode = $countryCodeOption->get();
            $dataArray['countryCode'] = $countryCode;
        }
        $dgfLocationNameOption = $this->dgfLocationName;
        if ($dgfLocationNameOption->isDefined()) {
            $dgfLocationName = $dgfLocationNameOption->get();
            $dataArray['dgf:locationName'] = $dgfLocationName;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): DgfAirportBuilder
    {
        return new DgfAirportBuilder(
            $this->dgfLocationCode,
            $this->countryCode,
            $this->dgfLocationName,
            $this->additionalProperties,
        );
    }
}
