<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

/**
 * Builds a {@see DgfAirport}.
 */
final class DgfAirportBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $dgfLocationCode
     * @param Option<string>           $countryCode
     * @param Option<string>           $dgfLocationName
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $dgfLocationCode,
        private Option $countryCode,
        private Option $dgfLocationName,
        private array $additionalProperties,
    ) {
    }

    /**
     * Airport of departure/destination in IATA code format.
     */
    public function setDgfLocationCode(string $dgfLocationCode): self
    {
        $this->dgfLocationCode = Some::create($dgfLocationCode);

        return $this;
    }

    /**
     * Code specifying the country using ISO 3166-1 alpha-2.
     */
    public function setCountryCode(string $countryCode): self
    {
        $this->countryCode = Some::create($countryCode);

        return $this;
    }

    /**
     * The name of the location.
     */
    public function setDgfLocationName(string $dgfLocationName): self
    {
        $this->dgfLocationName = Some::create($dgfLocationName);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): DgfAirport
    {
        return new DgfAirport(
            $this->dgfLocationCode,
            $this->countryCode,
            $this->dgfLocationName,
            $this->additionalProperties,
        );
    }
}
