<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

/**
 * Builds a {@see DgfLocation}.
 */
final class DgfLocationBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $dgfLocationName
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private Option $dgfLocationName, private array $additionalProperties)
    {
    }

    /**
     * The name of the location.
     */
    public function setDgfLocationName(string $dgfLocationName): self
    {
        $this->dgfLocationName = Some::create($dgfLocationName);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): DgfLocation
    {
        return new DgfLocation($this->dgfLocationName, $this->additionalProperties);
    }
}
