<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\MalformedDataException;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\None;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class DgfLocation implements SelfNormalizingModel
{
    /**
     * @param Option<string>           $dgfLocationName
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private Option $dgfLocationName, private array $additionalProperties)
    {
    }

    public static function builder(): DgfLocationBuilder
    {
        return new DgfLocationBuilder(None::create(), []);
    }

    /**
     * The name of the location.
     *
     * @return Option<string>
     */
    public function getDgfLocationName(): Option
    {
        return $this->dgfLocationName;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $dgfLocationName = None::create();
        if (array_key_exists('dgf:locationName', $data) && $data['dgf:locationName'] !== null) {
            $dgfLocationNameRaw = $data['dgf:locationName'];
            if (!is_string($dgfLocationNameRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "dgf:locationName" must be string, got %s.', get_debug_type($dgfLocationNameRaw)),
                );
            }
            $dgfLocationName = Some::create($dgfLocationNameRaw);
        }
        $additionalProperties = array_diff_key($data, ['dgf:locationName' => true]);

        return new self($dgfLocationName, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dgfLocationNameOption = $this->dgfLocationName;
        if ($dgfLocationNameOption->isDefined()) {
            $dgfLocationName = $dgfLocationNameOption->get();
            $dataArray['dgf:locationName'] = $dgfLocationName;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): DgfLocationBuilder
    {
        return new DgfLocationBuilder($this->dgfLocationName, $this->additionalProperties);
    }
}
