<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

/**
 * Builds a {@see DgfRoute}.
 */
final class DgfRouteBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $dgfVesselName
     * @param Option<string>           $dgfVoyageFlightNumber
     * @param Option<DgfAirport>       $dgfAirportOfDeparture
     * @param Option<DgfAirport>       $dgfAirportOfDestination
     * @param Option<string>           $dgfEstimatedDepartureDate
     * @param Option<string>           $dgfEstimatedArrivalDate
     * @param Option<DgfLocation>      $dgfPlaceOfAcceptance
     * @param Option<DgfLocation>      $dgfPortOfLoading
     * @param Option<DgfLocation>      $dgfPortOfUnloading
     * @param Option<DgfLocation>      $dgfPlaceOfDelivery
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $dgfVesselName,
        private Option $dgfVoyageFlightNumber,
        private Option $dgfAirportOfDeparture,
        private Option $dgfAirportOfDestination,
        private Option $dgfEstimatedDepartureDate,
        private Option $dgfEstimatedArrivalDate,
        private Option $dgfPlaceOfAcceptance,
        private Option $dgfPortOfLoading,
        private Option $dgfPortOfUnloading,
        private Option $dgfPlaceOfDelivery,
        private array $additionalProperties,
    ) {
    }

    /**
     * Vessel Name for Ocean.
     */
    public function setDgfVesselName(string $dgfVesselName): self
    {
        $this->dgfVesselName = Some::create($dgfVesselName);

        return $this;
    }

    /**
     * Voyage number for Ocean, Flight Carrier and Number for Air.
     */
    public function setDgfVoyageFlightNumber(string $dgfVoyageFlightNumber): self
    {
        $this->dgfVoyageFlightNumber = Some::create($dgfVoyageFlightNumber);

        return $this;
    }

    /**
     * DHL Global Forwarding Airport.
     */
    public function setDgfAirportOfDeparture(DgfAirport $dgfAirportOfDeparture): self
    {
        $this->dgfAirportOfDeparture = Some::create($dgfAirportOfDeparture);

        return $this;
    }

    /**
     * DHL Global Forwarding Airport.
     */
    public function setDgfAirportOfDestination(DgfAirport $dgfAirportOfDestination): self
    {
        $this->dgfAirportOfDestination = Some::create($dgfAirportOfDestination);

        return $this;
    }

    /**
     * Flight Estimated Date and Time of Departure.
     */
    public function setDgfEstimatedDepartureDate(string $dgfEstimatedDepartureDate): self
    {
        $this->dgfEstimatedDepartureDate = Some::create($dgfEstimatedDepartureDate);

        return $this;
    }

    /**
     * Flight Estimated Date and Time of Arrival.
     */
    public function setDgfEstimatedArrivalDate(string $dgfEstimatedArrivalDate): self
    {
        $this->dgfEstimatedArrivalDate = Some::create($dgfEstimatedArrivalDate);

        return $this;
    }

    /**
     * DHL Global Forwarding Location.
     */
    public function setDgfPlaceOfAcceptance(DgfLocation $dgfPlaceOfAcceptance): self
    {
        $this->dgfPlaceOfAcceptance = Some::create($dgfPlaceOfAcceptance);

        return $this;
    }

    /**
     * DHL Global Forwarding Location.
     */
    public function setDgfPortOfLoading(DgfLocation $dgfPortOfLoading): self
    {
        $this->dgfPortOfLoading = Some::create($dgfPortOfLoading);

        return $this;
    }

    /**
     * DHL Global Forwarding Location.
     */
    public function setDgfPortOfUnloading(DgfLocation $dgfPortOfUnloading): self
    {
        $this->dgfPortOfUnloading = Some::create($dgfPortOfUnloading);

        return $this;
    }

    /**
     * DHL Global Forwarding Location.
     */
    public function setDgfPlaceOfDelivery(DgfLocation $dgfPlaceOfDelivery): self
    {
        $this->dgfPlaceOfDelivery = Some::create($dgfPlaceOfDelivery);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): DgfRoute
    {
        return new DgfRoute(
            $this->dgfVesselName,
            $this->dgfVoyageFlightNumber,
            $this->dgfAirportOfDeparture,
            $this->dgfAirportOfDestination,
            $this->dgfEstimatedDepartureDate,
            $this->dgfEstimatedArrivalDate,
            $this->dgfPlaceOfAcceptance,
            $this->dgfPortOfLoading,
            $this->dgfPortOfUnloading,
            $this->dgfPlaceOfDelivery,
            $this->additionalProperties,
        );
    }
}
