<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\MalformedDataException;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\None;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class DgfRoute implements SelfNormalizingModel
{
    /**
     * @param Option<string>           $dgfVesselName
     * @param Option<string>           $dgfVoyageFlightNumber
     * @param Option<DgfAirport>       $dgfAirportOfDeparture
     * @param Option<DgfAirport>       $dgfAirportOfDestination
     * @param Option<string>           $dgfEstimatedDepartureDate
     * @param Option<string>           $dgfEstimatedArrivalDate
     * @param Option<DgfLocation>      $dgfPlaceOfAcceptance
     * @param Option<DgfLocation>      $dgfPortOfLoading
     * @param Option<DgfLocation>      $dgfPortOfUnloading
     * @param Option<DgfLocation>      $dgfPlaceOfDelivery
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $dgfVesselName,
        private Option $dgfVoyageFlightNumber,
        private Option $dgfAirportOfDeparture,
        private Option $dgfAirportOfDestination,
        private Option $dgfEstimatedDepartureDate,
        private Option $dgfEstimatedArrivalDate,
        private Option $dgfPlaceOfAcceptance,
        private Option $dgfPortOfLoading,
        private Option $dgfPortOfUnloading,
        private Option $dgfPlaceOfDelivery,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): DgfRouteBuilder
    {
        return new DgfRouteBuilder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * Vessel Name for Ocean.
     *
     * @return Option<string>
     */
    public function getDgfVesselName(): Option
    {
        return $this->dgfVesselName;
    }

    /**
     * Voyage number for Ocean, Flight Carrier and Number for Air.
     *
     * @return Option<string>
     */
    public function getDgfVoyageFlightNumber(): Option
    {
        return $this->dgfVoyageFlightNumber;
    }

    /**
     * DHL Global Forwarding Airport.
     *
     * @return Option<DgfAirport>
     */
    public function getDgfAirportOfDeparture(): Option
    {
        return $this->dgfAirportOfDeparture;
    }

    /**
     * DHL Global Forwarding Airport.
     *
     * @return Option<DgfAirport>
     */
    public function getDgfAirportOfDestination(): Option
    {
        return $this->dgfAirportOfDestination;
    }

    /**
     * Flight Estimated Date and Time of Departure.
     *
     * @return Option<string>
     */
    public function getDgfEstimatedDepartureDate(): Option
    {
        return $this->dgfEstimatedDepartureDate;
    }

    /**
     * Flight Estimated Date and Time of Arrival.
     *
     * @return Option<string>
     */
    public function getDgfEstimatedArrivalDate(): Option
    {
        return $this->dgfEstimatedArrivalDate;
    }

    /**
     * DHL Global Forwarding Location.
     *
     * @return Option<DgfLocation>
     */
    public function getDgfPlaceOfAcceptance(): Option
    {
        return $this->dgfPlaceOfAcceptance;
    }

    /**
     * DHL Global Forwarding Location.
     *
     * @return Option<DgfLocation>
     */
    public function getDgfPortOfLoading(): Option
    {
        return $this->dgfPortOfLoading;
    }

    /**
     * DHL Global Forwarding Location.
     *
     * @return Option<DgfLocation>
     */
    public function getDgfPortOfUnloading(): Option
    {
        return $this->dgfPortOfUnloading;
    }

    /**
     * DHL Global Forwarding Location.
     *
     * @return Option<DgfLocation>
     */
    public function getDgfPlaceOfDelivery(): Option
    {
        return $this->dgfPlaceOfDelivery;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $dgfVesselName = None::create();
        $dgfVoyageFlightNumber = None::create();
        $dgfAirportOfDeparture = None::create();
        $dgfAirportOfDestination = None::create();
        $dgfEstimatedDepartureDate = None::create();
        $dgfEstimatedArrivalDate = None::create();
        $dgfPlaceOfAcceptance = None::create();
        $dgfPortOfLoading = None::create();
        $dgfPortOfUnloading = None::create();
        $dgfPlaceOfDelivery = None::create();
        if (array_key_exists('dgf:vesselName', $data) && $data['dgf:vesselName'] !== null) {
            $dgfVesselNameRaw = $data['dgf:vesselName'];
            if (!is_string($dgfVesselNameRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "dgf:vesselName" must be string, got %s.', get_debug_type($dgfVesselNameRaw)),
                );
            }
            $dgfVesselName = Some::create($dgfVesselNameRaw);
        }
        if (array_key_exists('dgf:voyageFlightNumber', $data) && $data['dgf:voyageFlightNumber'] !== null) {
            $dgfVoyageFlightNumberRaw = $data['dgf:voyageFlightNumber'];
            if (!is_string($dgfVoyageFlightNumberRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "dgf:voyageFlightNumber" must be string, got %s.',
                        get_debug_type($dgfVoyageFlightNumberRaw),
                    ),
                );
            }
            $dgfVoyageFlightNumber = Some::create($dgfVoyageFlightNumberRaw);
        }
        if (array_key_exists('dgf:airportOfDeparture', $data) && $data['dgf:airportOfDeparture'] !== null) {
            $dgfAirportOfDepartureRaw = $data['dgf:airportOfDeparture'];
            if (!is_array($dgfAirportOfDepartureRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "dgf:airportOfDeparture" must be object, got %s.',
                        get_debug_type($dgfAirportOfDepartureRaw),
                    ),
                );
            }
            /** @var array<string, mixed> $dgfAirportOfDepartureRawTyped */
            $dgfAirportOfDepartureRawTyped = $dgfAirportOfDepartureRaw;
            $dgfAirportOfDeparture = Some::create(DgfAirport::fromArray($dgfAirportOfDepartureRawTyped));
        }
        if (array_key_exists('dgf:airportOfDestination', $data) && $data['dgf:airportOfDestination'] !== null) {
            $dgfAirportOfDestinationRaw = $data['dgf:airportOfDestination'];
            if (!is_array($dgfAirportOfDestinationRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "dgf:airportOfDestination" must be object, got %s.',
                        get_debug_type($dgfAirportOfDestinationRaw),
                    ),
                );
            }
            /** @var array<string, mixed> $dgfAirportOfDestinationRawTyped */
            $dgfAirportOfDestinationRawTyped = $dgfAirportOfDestinationRaw;
            $dgfAirportOfDestination = Some::create(DgfAirport::fromArray($dgfAirportOfDestinationRawTyped));
        }
        if (array_key_exists('dgf:estimatedDepartureDate', $data) && $data['dgf:estimatedDepartureDate'] !== null) {
            $dgfEstimatedDepartureDateRaw = $data['dgf:estimatedDepartureDate'];
            if (!is_string($dgfEstimatedDepartureDateRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "dgf:estimatedDepartureDate" must be string, got %s.',
                        get_debug_type($dgfEstimatedDepartureDateRaw),
                    ),
                );
            }
            $dgfEstimatedDepartureDate = Some::create($dgfEstimatedDepartureDateRaw);
        }
        if (array_key_exists('dgf:estimatedArrivalDate', $data) && $data['dgf:estimatedArrivalDate'] !== null) {
            $dgfEstimatedArrivalDateRaw = $data['dgf:estimatedArrivalDate'];
            if (!is_string($dgfEstimatedArrivalDateRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "dgf:estimatedArrivalDate" must be string, got %s.',
                        get_debug_type($dgfEstimatedArrivalDateRaw),
                    ),
                );
            }
            $dgfEstimatedArrivalDate = Some::create($dgfEstimatedArrivalDateRaw);
        }
        if (array_key_exists('dgf:placeOfAcceptance', $data) && $data['dgf:placeOfAcceptance'] !== null) {
            $dgfPlaceOfAcceptanceRaw = $data['dgf:placeOfAcceptance'];
            if (!is_array($dgfPlaceOfAcceptanceRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "dgf:placeOfAcceptance" must be object, got %s.',
                        get_debug_type($dgfPlaceOfAcceptanceRaw),
                    ),
                );
            }
            /** @var array<string, mixed> $dgfPlaceOfAcceptanceRawTyped */
            $dgfPlaceOfAcceptanceRawTyped = $dgfPlaceOfAcceptanceRaw;
            $dgfPlaceOfAcceptance = Some::create(DgfLocation::fromArray($dgfPlaceOfAcceptanceRawTyped));
        }
        if (array_key_exists('dgf:portOfLoading', $data) && $data['dgf:portOfLoading'] !== null) {
            $dgfPortOfLoadingRaw = $data['dgf:portOfLoading'];
            if (!is_array($dgfPortOfLoadingRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "dgf:portOfLoading" must be object, got %s.',
                        get_debug_type($dgfPortOfLoadingRaw),
                    ),
                );
            }
            /** @var array<string, mixed> $dgfPortOfLoadingRawTyped */
            $dgfPortOfLoadingRawTyped = $dgfPortOfLoadingRaw;
            $dgfPortOfLoading = Some::create(DgfLocation::fromArray($dgfPortOfLoadingRawTyped));
        }
        if (array_key_exists('dgf:portOfUnloading', $data) && $data['dgf:portOfUnloading'] !== null) {
            $dgfPortOfUnloadingRaw = $data['dgf:portOfUnloading'];
            if (!is_array($dgfPortOfUnloadingRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "dgf:portOfUnloading" must be object, got %s.',
                        get_debug_type($dgfPortOfUnloadingRaw),
                    ),
                );
            }
            /** @var array<string, mixed> $dgfPortOfUnloadingRawTyped */
            $dgfPortOfUnloadingRawTyped = $dgfPortOfUnloadingRaw;
            $dgfPortOfUnloading = Some::create(DgfLocation::fromArray($dgfPortOfUnloadingRawTyped));
        }
        if (array_key_exists('dgf:placeOfDelivery', $data) && $data['dgf:placeOfDelivery'] !== null) {
            $dgfPlaceOfDeliveryRaw = $data['dgf:placeOfDelivery'];
            if (!is_array($dgfPlaceOfDeliveryRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "dgf:placeOfDelivery" must be object, got %s.',
                        get_debug_type($dgfPlaceOfDeliveryRaw),
                    ),
                );
            }
            /** @var array<string, mixed> $dgfPlaceOfDeliveryRawTyped */
            $dgfPlaceOfDeliveryRawTyped = $dgfPlaceOfDeliveryRaw;
            $dgfPlaceOfDelivery = Some::create(DgfLocation::fromArray($dgfPlaceOfDeliveryRawTyped));
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'dgf:vesselName' => true,
                'dgf:voyageFlightNumber' => true,
                'dgf:airportOfDeparture' => true,
                'dgf:airportOfDestination' => true,
                'dgf:estimatedDepartureDate' => true,
                'dgf:estimatedArrivalDate' => true,
                'dgf:placeOfAcceptance' => true,
                'dgf:portOfLoading' => true,
                'dgf:portOfUnloading' => true,
                'dgf:placeOfDelivery' => true,
            ],
        );

        return new self(
            $dgfVesselName,
            $dgfVoyageFlightNumber,
            $dgfAirportOfDeparture,
            $dgfAirportOfDestination,
            $dgfEstimatedDepartureDate,
            $dgfEstimatedArrivalDate,
            $dgfPlaceOfAcceptance,
            $dgfPortOfLoading,
            $dgfPortOfUnloading,
            $dgfPlaceOfDelivery,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dgfVesselNameOption = $this->dgfVesselName;
        if ($dgfVesselNameOption->isDefined()) {
            $dgfVesselName = $dgfVesselNameOption->get();
            $dataArray['dgf:vesselName'] = $dgfVesselName;
        }
        $dgfVoyageFlightNumberOption = $this->dgfVoyageFlightNumber;
        if ($dgfVoyageFlightNumberOption->isDefined()) {
            $dgfVoyageFlightNumber = $dgfVoyageFlightNumberOption->get();
            $dataArray['dgf:voyageFlightNumber'] = $dgfVoyageFlightNumber;
        }
        $dgfAirportOfDepartureOption = $this->dgfAirportOfDeparture;
        if ($dgfAirportOfDepartureOption->isDefined()) {
            $dgfAirportOfDeparture = $dgfAirportOfDepartureOption->get();
            $dataArray['dgf:airportOfDeparture'] = $normalizationTarget->model($dgfAirportOfDeparture);
        }
        $dgfAirportOfDestinationOption = $this->dgfAirportOfDestination;
        if ($dgfAirportOfDestinationOption->isDefined()) {
            $dgfAirportOfDestination = $dgfAirportOfDestinationOption->get();
            $dataArray['dgf:airportOfDestination'] = $normalizationTarget->model($dgfAirportOfDestination);
        }
        $dgfEstimatedDepartureDateOption = $this->dgfEstimatedDepartureDate;
        if ($dgfEstimatedDepartureDateOption->isDefined()) {
            $dgfEstimatedDepartureDate = $dgfEstimatedDepartureDateOption->get();
            $dataArray['dgf:estimatedDepartureDate'] = $dgfEstimatedDepartureDate;
        }
        $dgfEstimatedArrivalDateOption = $this->dgfEstimatedArrivalDate;
        if ($dgfEstimatedArrivalDateOption->isDefined()) {
            $dgfEstimatedArrivalDate = $dgfEstimatedArrivalDateOption->get();
            $dataArray['dgf:estimatedArrivalDate'] = $dgfEstimatedArrivalDate;
        }
        $dgfPlaceOfAcceptanceOption = $this->dgfPlaceOfAcceptance;
        if ($dgfPlaceOfAcceptanceOption->isDefined()) {
            $dgfPlaceOfAcceptance = $dgfPlaceOfAcceptanceOption->get();
            $dataArray['dgf:placeOfAcceptance'] = $normalizationTarget->model($dgfPlaceOfAcceptance);
        }
        $dgfPortOfLoadingOption = $this->dgfPortOfLoading;
        if ($dgfPortOfLoadingOption->isDefined()) {
            $dgfPortOfLoading = $dgfPortOfLoadingOption->get();
            $dataArray['dgf:portOfLoading'] = $normalizationTarget->model($dgfPortOfLoading);
        }
        $dgfPortOfUnloadingOption = $this->dgfPortOfUnloading;
        if ($dgfPortOfUnloadingOption->isDefined()) {
            $dgfPortOfUnloading = $dgfPortOfUnloadingOption->get();
            $dataArray['dgf:portOfUnloading'] = $normalizationTarget->model($dgfPortOfUnloading);
        }
        $dgfPlaceOfDeliveryOption = $this->dgfPlaceOfDelivery;
        if ($dgfPlaceOfDeliveryOption->isDefined()) {
            $dgfPlaceOfDelivery = $dgfPlaceOfDeliveryOption->get();
            $dataArray['dgf:placeOfDelivery'] = $normalizationTarget->model($dgfPlaceOfDelivery);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): DgfRouteBuilder
    {
        return new DgfRouteBuilder(
            $this->dgfVesselName,
            $this->dgfVoyageFlightNumber,
            $this->dgfAirportOfDeparture,
            $this->dgfAirportOfDestination,
            $this->dgfEstimatedDepartureDate,
            $this->dgfEstimatedArrivalDate,
            $this->dgfPlaceOfAcceptance,
            $this->dgfPortOfLoading,
            $this->dgfPortOfUnloading,
            $this->dgfPlaceOfDelivery,
            $this->additionalProperties,
        );
    }
}
