<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

/**
 * Builds a {@see Dimensions}.
 */
final class DimensionsBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<QuantitativeValue> $height
     * @param Option<QuantitativeValue> $length
     * @param Option<QuantitativeValue> $width
     * @param array<int|string, mixed>  $additionalProperties
     */
    public function __construct(
        private Option $height,
        private Option $length,
        private Option $width,
        private array $additionalProperties,
    ) {
    }

    /**
     * A point value or interval for product characteristics and other purposes.
     */
    public function setHeight(QuantitativeValue $height): self
    {
        $this->height = Some::create($height);

        return $this;
    }

    /**
     * A point value or interval for product characteristics and other purposes.
     */
    public function setLength(QuantitativeValue $length): self
    {
        $this->length = Some::create($length);

        return $this;
    }

    /**
     * A point value or interval for product characteristics and other purposes.
     */
    public function setWidth(QuantitativeValue $width): self
    {
        $this->width = Some::create($width);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): Dimensions
    {
        return new Dimensions($this->height, $this->length, $this->width, $this->additionalProperties);
    }
}
