<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\MalformedDataException;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\None;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function sprintf;

final readonly class Dimensions implements SelfNormalizingModel
{
    /**
     * @param Option<QuantitativeValue> $height
     * @param Option<QuantitativeValue> $length
     * @param Option<QuantitativeValue> $width
     * @param array<int|string, mixed>  $additionalProperties
     */
    public function __construct(
        private Option $height,
        private Option $length,
        private Option $width,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): DimensionsBuilder
    {
        return new DimensionsBuilder(None::create(), None::create(), None::create(), []);
    }

    /**
     * A point value or interval for product characteristics and other purposes.
     *
     * @return Option<QuantitativeValue>
     */
    public function getHeight(): Option
    {
        return $this->height;
    }

    /**
     * A point value or interval for product characteristics and other purposes.
     *
     * @return Option<QuantitativeValue>
     */
    public function getLength(): Option
    {
        return $this->length;
    }

    /**
     * A point value or interval for product characteristics and other purposes.
     *
     * @return Option<QuantitativeValue>
     */
    public function getWidth(): Option
    {
        return $this->width;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $height = None::create();
        $length = None::create();
        $width = None::create();
        if (array_key_exists('height', $data) && $data['height'] !== null) {
            $heightRaw = $data['height'];
            if (!is_array($heightRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "height" must be object, got %s.', get_debug_type($heightRaw)),
                );
            }
            /** @var array<string, mixed> $heightRawTyped */
            $heightRawTyped = $heightRaw;
            $height = Some::create(QuantitativeValue::fromArray($heightRawTyped));
        }
        if (array_key_exists('length', $data) && $data['length'] !== null) {
            $lengthRaw = $data['length'];
            if (!is_array($lengthRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "length" must be object, got %s.', get_debug_type($lengthRaw)),
                );
            }
            /** @var array<string, mixed> $lengthRawTyped */
            $lengthRawTyped = $lengthRaw;
            $length = Some::create(QuantitativeValue::fromArray($lengthRawTyped));
        }
        if (array_key_exists('width', $data) && $data['width'] !== null) {
            $widthRaw = $data['width'];
            if (!is_array($widthRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "width" must be object, got %s.', get_debug_type($widthRaw)),
                );
            }
            /** @var array<string, mixed> $widthRawTyped */
            $widthRawTyped = $widthRaw;
            $width = Some::create(QuantitativeValue::fromArray($widthRawTyped));
        }
        $additionalProperties = array_diff_key($data, ['height' => true, 'length' => true, 'width' => true]);

        return new self($height, $length, $width, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $heightOption = $this->height;
        if ($heightOption->isDefined()) {
            $height = $heightOption->get();
            $dataArray['height'] = $normalizationTarget->model($height);
        }
        $lengthOption = $this->length;
        if ($lengthOption->isDefined()) {
            $length = $lengthOption->get();
            $dataArray['length'] = $normalizationTarget->model($length);
        }
        $widthOption = $this->width;
        if ($widthOption->isDefined()) {
            $width = $widthOption->get();
            $dataArray['width'] = $normalizationTarget->model($width);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): DimensionsBuilder
    {
        return new DimensionsBuilder($this->height, $this->length, $this->width, $this->additionalProperties);
    }
}
