<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

/**
 * Builds a {@see EstimatedDeliveryTimeFrame}.
 */
final class EstimatedDeliveryTimeFrameBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $estimatedFrom
     * @param Option<string>           $estimatedThrough
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $estimatedFrom,
        private Option $estimatedThrough,
        private array $additionalProperties,
    ) {
    }

    /**
     * The start date of the estimated time frame.
     */
    public function setEstimatedFrom(string $estimatedFrom): self
    {
        $this->estimatedFrom = Some::create($estimatedFrom);

        return $this;
    }

    /**
     * The end date of the estimated time frame.
     */
    public function setEstimatedThrough(string $estimatedThrough): self
    {
        $this->estimatedThrough = Some::create($estimatedThrough);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): EstimatedDeliveryTimeFrame
    {
        return new EstimatedDeliveryTimeFrame(
            $this->estimatedFrom,
            $this->estimatedThrough,
            $this->additionalProperties,
        );
    }
}
