<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\MalformedDataException;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\None;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class EstimatedDeliveryTimeFrame implements SelfNormalizingModel
{
    /**
     * @param Option<string>           $estimatedFrom
     * @param Option<string>           $estimatedThrough
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $estimatedFrom,
        private Option $estimatedThrough,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): EstimatedDeliveryTimeFrameBuilder
    {
        return new EstimatedDeliveryTimeFrameBuilder(None::create(), None::create(), []);
    }

    /**
     * The start date of the estimated time frame.
     *
     * @return Option<string>
     */
    public function getEstimatedFrom(): Option
    {
        return $this->estimatedFrom;
    }

    /**
     * The end date of the estimated time frame.
     *
     * @return Option<string>
     */
    public function getEstimatedThrough(): Option
    {
        return $this->estimatedThrough;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $estimatedFrom = None::create();
        $estimatedThrough = None::create();
        if (array_key_exists('estimatedFrom', $data) && $data['estimatedFrom'] !== null) {
            $estimatedFromRaw = $data['estimatedFrom'];
            if (!is_string($estimatedFromRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "estimatedFrom" must be string, got %s.', get_debug_type($estimatedFromRaw)),
                );
            }
            $estimatedFrom = Some::create($estimatedFromRaw);
        }
        if (array_key_exists('estimatedThrough', $data) && $data['estimatedThrough'] !== null) {
            $estimatedThroughRaw = $data['estimatedThrough'];
            if (!is_string($estimatedThroughRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "estimatedThrough" must be string, got %s.',
                        get_debug_type($estimatedThroughRaw),
                    ),
                );
            }
            $estimatedThrough = Some::create($estimatedThroughRaw);
        }
        $additionalProperties = array_diff_key($data, ['estimatedFrom' => true, 'estimatedThrough' => true]);

        return new self($estimatedFrom, $estimatedThrough, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $estimatedFromOption = $this->estimatedFrom;
        if ($estimatedFromOption->isDefined()) {
            $estimatedFrom = $estimatedFromOption->get();
            $dataArray['estimatedFrom'] = $estimatedFrom;
        }
        $estimatedThroughOption = $this->estimatedThrough;
        if ($estimatedThroughOption->isDefined()) {
            $estimatedThrough = $estimatedThroughOption->get();
            $dataArray['estimatedThrough'] = $estimatedThrough;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): EstimatedDeliveryTimeFrameBuilder
    {
        return new EstimatedDeliveryTimeFrameBuilder(
            $this->estimatedFrom,
            $this->estimatedThrough,
            $this->additionalProperties,
        );
    }
}
