<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

/**
 * Builds a {@see Location}.
 */
final class LocationBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<float>            $lat
     * @param Option<float>            $lon
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private Option $lat, private Option $lon, private array $additionalProperties)
    {
    }

    /**
     * Latitude value.
     */
    public function setLat(float $lat): self
    {
        $this->lat = Some::create($lat);

        return $this;
    }

    /**
     * Longitude value.
     */
    public function setLon(float $lon): self
    {
        $this->lon = Some::create($lon);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): Location
    {
        return new Location($this->lat, $this->lon, $this->additionalProperties);
    }
}
