<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\MalformedDataException;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\None;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_float;
use function is_int;
use function sprintf;

final readonly class Location implements SelfNormalizingModel
{
    /**
     * @param Option<float>            $lat
     * @param Option<float>            $lon
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private Option $lat, private Option $lon, private array $additionalProperties)
    {
    }

    public static function builder(): LocationBuilder
    {
        return new LocationBuilder(None::create(), None::create(), []);
    }

    /**
     * Latitude value.
     *
     * @return Option<float>
     */
    public function getLat(): Option
    {
        return $this->lat;
    }

    /**
     * Longitude value.
     *
     * @return Option<float>
     */
    public function getLon(): Option
    {
        return $this->lon;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $lat = None::create();
        $lon = None::create();
        if (array_key_exists('lat', $data) && is_int($data['lat'])) {
            $data['lat'] = (float) $data['lat'];
        }
        if (array_key_exists('lon', $data) && is_int($data['lon'])) {
            $data['lon'] = (float) $data['lon'];
        }
        if (array_key_exists('lat', $data) && $data['lat'] !== null) {
            $latRaw = $data['lat'];
            if (!(is_float($latRaw) || is_int($latRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "lat" must be number, got %s.', get_debug_type($latRaw)),
                );
            }
            $lat = Some::create((float) $latRaw);
        }
        if (array_key_exists('lon', $data) && $data['lon'] !== null) {
            $lonRaw = $data['lon'];
            if (!(is_float($lonRaw) || is_int($lonRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "lon" must be number, got %s.', get_debug_type($lonRaw)),
                );
            }
            $lon = Some::create((float) $lonRaw);
        }
        $additionalProperties = array_diff_key($data, ['lat' => true, 'lon' => true]);

        return new self($lat, $lon, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $latOption = $this->lat;
        if ($latOption->isDefined()) {
            $lat = $latOption->get();
            $dataArray['lat'] = $lat;
        }
        $lonOption = $this->lon;
        if ($lonOption->isDefined()) {
            $lon = $lonOption->get();
            $dataArray['lon'] = $lon;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): LocationBuilder
    {
        return new LocationBuilder($this->lat, $this->lon, $this->additionalProperties);
    }
}
