<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

/**
 * Builds a {@see Measurement}.
 */
final class MeasurementBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<SecretPolicy|UnknownEnumValue<string>> $policy
     * @param Option<string>                                $timestamp
     * @param Option<string>                                $deviceId
     * @param Option<list<string>>                          $pieceIds
     * @param Option<Location>                              $location
     * @param Option<Humidity>                              $humidity
     * @param Option<Pressure>                              $pressure
     * @param Option<Temperature>                           $temperature
     * @param Option<Tilt>                                  $tilt
     * @param array<int|string, mixed>                      $additionalProperties
     */
    public function __construct(
        private Option $policy,
        private Option $timestamp,
        private Option $deviceId,
        private Option $pieceIds,
        private Option $location,
        private Option $humidity,
        private Option $pressure,
        private Option $temperature,
        private Option $tilt,
        private array $additionalProperties,
    ) {
    }

    /**
     * A secret policy protecting sensitive information.
     */
    public function setPolicy(SecretPolicy $policy): self
    {
        $this->policy = Some::create($policy);

        return $this;
    }

    /**
     * Date and time when the telemetry data was created by the origin system.
     */
    public function setTimestamp(string $timestamp): self
    {
        $this->timestamp = Some::create($timestamp);

        return $this;
    }

    /**
     * Sensor device id measured the humidity.
     */
    public function setDeviceId(string $deviceId): self
    {
        $this->deviceId = Some::create($deviceId);

        return $this;
    }

    /**
     * piece ids of shipment.
     *
     * @param list<string> $pieceIds
     */
    public function setPieceIds(array $pieceIds): self
    {
        $this->pieceIds = Some::create($pieceIds);

        return $this;
    }

    /**
     * location co-ordinates of shipment.
     */
    public function setLocation(Location $location): self
    {
        $this->location = Some::create($location);

        return $this;
    }

    /**
     * Humidity measurement.
     */
    public function setHumidity(Humidity $humidity): self
    {
        $this->humidity = Some::create($humidity);

        return $this;
    }

    /**
     * Pressure measurement.
     */
    public function setPressure(Pressure $pressure): self
    {
        $this->pressure = Some::create($pressure);

        return $this;
    }

    /**
     * Temperature measurement.
     */
    public function setTemperature(Temperature $temperature): self
    {
        $this->temperature = Some::create($temperature);

        return $this;
    }

    /**
     * Tilt measurement.
     */
    public function setTilt(Tilt $tilt): self
    {
        $this->tilt = Some::create($tilt);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): Measurement
    {
        return new Measurement(
            $this->policy,
            $this->timestamp,
            $this->deviceId,
            $this->pieceIds,
            $this->location,
            $this->humidity,
            $this->pressure,
            $this->temperature,
            $this->tilt,
            $this->additionalProperties,
        );
    }
}
