<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\MalformedDataException;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\None;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class Measurement implements SelfNormalizingModel
{
    /**
     * @param Option<SecretPolicy|UnknownEnumValue<string>> $policy
     * @param Option<string>                                $timestamp
     * @param Option<string>                                $deviceId
     * @param Option<list<string>>                          $pieceIds
     * @param Option<Location>                              $location
     * @param Option<Humidity>                              $humidity
     * @param Option<Pressure>                              $pressure
     * @param Option<Temperature>                           $temperature
     * @param Option<Tilt>                                  $tilt
     * @param array<int|string, mixed>                      $additionalProperties
     */
    public function __construct(
        private Option $policy,
        private Option $timestamp,
        private Option $deviceId,
        private Option $pieceIds,
        private Option $location,
        private Option $humidity,
        private Option $pressure,
        private Option $temperature,
        private Option $tilt,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): MeasurementBuilder
    {
        return new MeasurementBuilder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * A secret policy protecting sensitive information.
     *
     * Default: `"postal-code"`.
     *
     * @return Option<SecretPolicy|UnknownEnumValue<string>>
     */
    public function getPolicy(): Option
    {
        return $this->policy;
    }

    /**
     * Date and time when the telemetry data was created by the origin system.
     *
     * @return Option<string>
     */
    public function getTimestamp(): Option
    {
        return $this->timestamp;
    }

    /**
     * Sensor device id measured the humidity.
     *
     * @return Option<string>
     */
    public function getDeviceId(): Option
    {
        return $this->deviceId;
    }

    /**
     * piece ids of shipment.
     *
     * @return Option<list<string>>
     */
    public function getPieceIds(): Option
    {
        return $this->pieceIds;
    }

    /**
     * location co-ordinates of shipment.
     *
     * @return Option<Location>
     */
    public function getLocation(): Option
    {
        return $this->location;
    }

    /**
     * Humidity measurement.
     *
     * @return Option<Humidity>
     */
    public function getHumidity(): Option
    {
        return $this->humidity;
    }

    /**
     * Pressure measurement.
     *
     * @return Option<Pressure>
     */
    public function getPressure(): Option
    {
        return $this->pressure;
    }

    /**
     * Temperature measurement.
     *
     * @return Option<Temperature>
     */
    public function getTemperature(): Option
    {
        return $this->temperature;
    }

    /**
     * Tilt measurement.
     *
     * @return Option<Tilt>
     */
    public function getTilt(): Option
    {
        return $this->tilt;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $policy = None::create();
        $timestamp = None::create();
        $deviceId = None::create();
        $pieceIds = None::create();
        $location = None::create();
        $humidity = None::create();
        $pressure = None::create();
        $temperature = None::create();
        $tilt = None::create();
        if (array_key_exists('@policy', $data) && $data['@policy'] !== null) {
            $policyRaw = $data['@policy'];
            if (!is_string($policyRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "@policy" must be string, got %s.', get_debug_type($policyRaw)),
                );
            }
            $policy = Some::create(SecretPolicy::tryFrom($policyRaw) ?? UnknownEnumValue::of($policyRaw));
        }
        if (array_key_exists('timestamp', $data) && $data['timestamp'] !== null) {
            $timestampRaw = $data['timestamp'];
            if (!is_string($timestampRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "timestamp" must be string, got %s.', get_debug_type($timestampRaw)),
                );
            }
            $timestamp = Some::create($timestampRaw);
        }
        if (array_key_exists('deviceId', $data) && $data['deviceId'] !== null) {
            $deviceIdRaw = $data['deviceId'];
            if (!is_string($deviceIdRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "deviceId" must be string, got %s.', get_debug_type($deviceIdRaw)),
                );
            }
            $deviceId = Some::create($deviceIdRaw);
        }
        if (array_key_exists('pieceIds', $data) && $data['pieceIds'] !== null) {
            $pieceIdsRaw = $data['pieceIds'];
            if (!(is_array($pieceIdsRaw) && array_is_list($pieceIdsRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "pieceIds" must be list, got %s.', get_debug_type($pieceIdsRaw)),
                );
            }
            $pieceIds = Some::create(array_map(static function (mixed $value): string {
                if (!is_string($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be string, got %s.', get_debug_type($value)),
                    );
                }

                return $value;
            }, $pieceIdsRaw));
        }
        if (array_key_exists('location', $data) && $data['location'] !== null) {
            $locationRaw = $data['location'];
            if (!is_array($locationRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "location" must be object, got %s.', get_debug_type($locationRaw)),
                );
            }
            /** @var array<string, mixed> $locationRawTyped */
            $locationRawTyped = $locationRaw;
            $location = Some::create(Location::fromArray($locationRawTyped));
        }
        if (array_key_exists('humidity', $data) && $data['humidity'] !== null) {
            $humidityRaw = $data['humidity'];
            if (!is_array($humidityRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "humidity" must be object, got %s.', get_debug_type($humidityRaw)),
                );
            }
            /** @var array<string, mixed> $humidityRawTyped */
            $humidityRawTyped = $humidityRaw;
            $humidity = Some::create(Humidity::fromArray($humidityRawTyped));
        }
        if (array_key_exists('pressure', $data) && $data['pressure'] !== null) {
            $pressureRaw = $data['pressure'];
            if (!is_array($pressureRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "pressure" must be object, got %s.', get_debug_type($pressureRaw)),
                );
            }
            /** @var array<string, mixed> $pressureRawTyped */
            $pressureRawTyped = $pressureRaw;
            $pressure = Some::create(Pressure::fromArray($pressureRawTyped));
        }
        if (array_key_exists('temperature', $data) && $data['temperature'] !== null) {
            $temperatureRaw = $data['temperature'];
            if (!is_array($temperatureRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "temperature" must be object, got %s.', get_debug_type($temperatureRaw)),
                );
            }
            /** @var array<string, mixed> $temperatureRawTyped */
            $temperatureRawTyped = $temperatureRaw;
            $temperature = Some::create(Temperature::fromArray($temperatureRawTyped));
        }
        if (array_key_exists('tilt', $data) && $data['tilt'] !== null) {
            $tiltRaw = $data['tilt'];
            if (!is_array($tiltRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "tilt" must be object, got %s.', get_debug_type($tiltRaw)),
                );
            }
            /** @var array<string, mixed> $tiltRawTyped */
            $tiltRawTyped = $tiltRaw;
            $tilt = Some::create(Tilt::fromArray($tiltRawTyped));
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                '@policy' => true,
                'timestamp' => true,
                'deviceId' => true,
                'pieceIds' => true,
                'location' => true,
                'humidity' => true,
                'pressure' => true,
                'temperature' => true,
                'tilt' => true,
            ],
        );

        return new self(
            $policy,
            $timestamp,
            $deviceId,
            $pieceIds,
            $location,
            $humidity,
            $pressure,
            $temperature,
            $tilt,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $policyOption = $this->policy;
        if ($policyOption->isDefined()) {
            $policy = $policyOption->get();
            $dataArray['@policy'] = $policy->value;
        }
        $timestampOption = $this->timestamp;
        if ($timestampOption->isDefined()) {
            $timestamp = $timestampOption->get();
            $dataArray['timestamp'] = $timestamp;
        }
        $deviceIdOption = $this->deviceId;
        if ($deviceIdOption->isDefined()) {
            $deviceId = $deviceIdOption->get();
            $dataArray['deviceId'] = $deviceId;
        }
        $pieceIdsOption = $this->pieceIds;
        if ($pieceIdsOption->isDefined()) {
            $pieceIds = $pieceIdsOption->get();
            $values = [];
            foreach ($pieceIds as $value) {
                $values[] = $value;
            }
            $dataArray['pieceIds'] = $values;
        }
        $locationOption = $this->location;
        if ($locationOption->isDefined()) {
            $location = $locationOption->get();
            $dataArray['location'] = $normalizationTarget->model($location);
        }
        $humidityOption = $this->humidity;
        if ($humidityOption->isDefined()) {
            $humidity = $humidityOption->get();
            $dataArray['humidity'] = $normalizationTarget->model($humidity);
        }
        $pressureOption = $this->pressure;
        if ($pressureOption->isDefined()) {
            $pressure = $pressureOption->get();
            $dataArray['pressure'] = $normalizationTarget->model($pressure);
        }
        $temperatureOption = $this->temperature;
        if ($temperatureOption->isDefined()) {
            $temperature = $temperatureOption->get();
            $dataArray['temperature'] = $normalizationTarget->model($temperature);
        }
        $tiltOption = $this->tilt;
        if ($tiltOption->isDefined()) {
            $tilt = $tiltOption->get();
            $dataArray['tilt'] = $normalizationTarget->model($tilt);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): MeasurementBuilder
    {
        return new MeasurementBuilder(
            $this->policy,
            $this->timestamp,
            $this->deviceId,
            $this->pieceIds,
            $this->location,
            $this->humidity,
            $this->pressure,
            $this->temperature,
            $this->tilt,
            $this->additionalProperties,
        );
    }
}
