<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

/**
 * Builds a {@see Person}.
 */
final class PersonBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<SecretPolicy|UnknownEnumValue<string>> $policy
     * @param Option<string>                                $familyName
     * @param Option<string>                                $givenName
     * @param Option<string>                                $name
     * @param Option<SecuredAddress>                        $address
     * @param array<int|string, mixed>                      $additionalProperties
     */
    public function __construct(
        private string $type,
        private Option $policy,
        private Option $familyName,
        private Option $givenName,
        private Option $name,
        private Option $address,
        private array $additionalProperties,
    ) {
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function setPolicy(SecretPolicy $policy): self
    {
        $this->policy = Some::create($policy);

        return $this;
    }

    /**
     * Family name, the last name of a person.
     */
    public function setFamilyName(string $familyName): self
    {
        $this->familyName = Some::create($familyName);

        return $this;
    }

    /**
     * Given name, the first name of a person.
     */
    public function setGivenName(string $givenName): self
    {
        $this->givenName = Some::create($givenName);

        return $this;
    }

    /**
     * The name of the person.
     */
    public function setName(string $name): self
    {
        $this->name = Some::create($name);

        return $this;
    }

    /**
     * The mailing address secured by policy.
     */
    public function setAddress(SecuredAddress $address): self
    {
        $this->address = Some::create($address);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): Person
    {
        return new Person(
            $this->type,
            $this->policy,
            $this->familyName,
            $this->givenName,
            $this->name,
            $this->address,
            $this->additionalProperties,
        );
    }
}
