<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\MalformedDataException;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\None;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_float;
use function is_int;
use function is_string;
use function sprintf;

final readonly class ProblemDetail implements SelfNormalizingModel
{
    /**
     * @param Option<string>           $detail
     * @param Option<string>           $instance
     * @param Option<float>            $status
     * @param Option<string>           $title
     * @param Option<string>           $type
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $detail,
        private Option $instance,
        private Option $status,
        private Option $title,
        private Option $type,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): ProblemDetailBuilder
    {
        return new ProblemDetailBuilder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * A human-readable explanation specific to this occurrence of the problem.
     *
     * @return Option<string>
     */
    public function getDetail(): Option
    {
        return $this->detail;
    }

    /**
     * A URI reference that identifies the specific occurrence of the problem.
     *
     * @return Option<string>
     */
    public function getInstance(): Option
    {
        return $this->instance;
    }

    /**
     * The HTTP status code.
     *
     * @return Option<float>
     */
    public function getStatus(): Option
    {
        return $this->status;
    }

    /**
     * A short, human-readable summary of the problem type.
     *
     * @return Option<string>
     */
    public function getTitle(): Option
    {
        return $this->title;
    }

    /**
     * An identity of caused exception class.
     *
     * @return Option<string>
     */
    public function getType(): Option
    {
        return $this->type;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $detail = None::create();
        $instance = None::create();
        $status = None::create();
        $title = None::create();
        $type = None::create();
        if (array_key_exists('status', $data) && is_int($data['status'])) {
            $data['status'] = (float) $data['status'];
        }
        if (array_key_exists('detail', $data) && $data['detail'] !== null) {
            $detailRaw = $data['detail'];
            if (!is_string($detailRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "detail" must be string, got %s.', get_debug_type($detailRaw)),
                );
            }
            $detail = Some::create($detailRaw);
        }
        if (array_key_exists('instance', $data) && $data['instance'] !== null) {
            $instanceRaw = $data['instance'];
            if (!is_string($instanceRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "instance" must be string, got %s.', get_debug_type($instanceRaw)),
                );
            }
            $instance = Some::create($instanceRaw);
        }
        if (array_key_exists('status', $data) && $data['status'] !== null) {
            $statusRaw = $data['status'];
            if (!(is_float($statusRaw) || is_int($statusRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "status" must be number, got %s.', get_debug_type($statusRaw)),
                );
            }
            $status = Some::create((float) $statusRaw);
        }
        if (array_key_exists('title', $data) && $data['title'] !== null) {
            $titleRaw = $data['title'];
            if (!is_string($titleRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "title" must be string, got %s.', get_debug_type($titleRaw)),
                );
            }
            $title = Some::create($titleRaw);
        }
        if (array_key_exists('type', $data) && $data['type'] !== null) {
            $typeRaw = $data['type'];
            if (!is_string($typeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "type" must be string, got %s.', get_debug_type($typeRaw)),
                );
            }
            $type = Some::create($typeRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            ['detail' => true, 'instance' => true, 'status' => true, 'title' => true, 'type' => true],
        );

        return new self($detail, $instance, $status, $title, $type, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $detailOption = $this->detail;
        if ($detailOption->isDefined()) {
            $detail = $detailOption->get();
            $dataArray['detail'] = $detail;
        }
        $instanceOption = $this->instance;
        if ($instanceOption->isDefined()) {
            $instance = $instanceOption->get();
            $dataArray['instance'] = $instance;
        }
        $statusOption = $this->status;
        if ($statusOption->isDefined()) {
            $status = $statusOption->get();
            $dataArray['status'] = $status;
        }
        $titleOption = $this->title;
        if ($titleOption->isDefined()) {
            $title = $titleOption->get();
            $dataArray['title'] = $title;
        }
        $typeOption = $this->type;
        if ($typeOption->isDefined()) {
            $type = $typeOption->get();
            $dataArray['type'] = $type;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): ProblemDetailBuilder
    {
        return new ProblemDetailBuilder(
            $this->detail,
            $this->instance,
            $this->status,
            $this->title,
            $this->type,
            $this->additionalProperties,
        );
    }
}
