<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

/**
 * Builds a {@see ProblemDetail}.
 */
final class ProblemDetailBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $detail
     * @param Option<string>           $instance
     * @param Option<float>            $status
     * @param Option<string>           $title
     * @param Option<string>           $type
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $detail,
        private Option $instance,
        private Option $status,
        private Option $title,
        private Option $type,
        private array $additionalProperties,
    ) {
    }

    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    public function setDetail(string $detail): self
    {
        $this->detail = Some::create($detail);

        return $this;
    }

    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    public function setInstance(string $instance): self
    {
        $this->instance = Some::create($instance);

        return $this;
    }

    /**
     * The HTTP status code.
     */
    public function setStatus(float $status): self
    {
        $this->status = Some::create($status);

        return $this;
    }

    /**
     * A short, human-readable summary of the problem type.
     */
    public function setTitle(string $title): self
    {
        $this->title = Some::create($title);

        return $this;
    }

    /**
     * An identity of caused exception class.
     */
    public function setType(string $type): self
    {
        $this->type = Some::create($type);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ProblemDetail
    {
        return new ProblemDetail(
            $this->detail,
            $this->instance,
            $this->status,
            $this->title,
            $this->type,
            $this->additionalProperties,
        );
    }
}
