<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\MalformedDataException;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\None;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class Product implements SelfNormalizingModel
{
    /**
     * @param Option<string>           $deliveryMethodRemark
     * @param Option<string>           $productCode
     * @param Option<string>           $productName
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $deliveryMethodRemark,
        private Option $productCode,
        private Option $productName,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): ProductBuilder
    {
        return new ProductBuilder(None::create(), None::create(), None::create(), []);
    }

    /**
     * Specific detail of product.
     *
     * @return Option<string>
     */
    public function getDeliveryMethodRemark(): Option
    {
        return $this->deliveryMethodRemark;
    }

    /** @return Option<string> */
    public function getProductCode(): Option
    {
        return $this->productCode;
    }

    /**
     * Business unit product or service.
     *
     * @return Option<string>
     */
    public function getProductName(): Option
    {
        return $this->productName;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $deliveryMethodRemark = None::create();
        $productCode = None::create();
        $productName = None::create();
        if (array_key_exists('deliveryMethodRemark', $data) && $data['deliveryMethodRemark'] !== null) {
            $deliveryMethodRemarkRaw = $data['deliveryMethodRemark'];
            if (!is_string($deliveryMethodRemarkRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "deliveryMethodRemark" must be string, got %s.',
                        get_debug_type($deliveryMethodRemarkRaw),
                    ),
                );
            }
            $deliveryMethodRemark = Some::create($deliveryMethodRemarkRaw);
        }
        if (array_key_exists('productCode', $data) && $data['productCode'] !== null) {
            $productCodeRaw = $data['productCode'];
            if (!is_string($productCodeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "productCode" must be string, got %s.', get_debug_type($productCodeRaw)),
                );
            }
            $productCode = Some::create($productCodeRaw);
        }
        if (array_key_exists('productName', $data) && $data['productName'] !== null) {
            $productNameRaw = $data['productName'];
            if (!is_string($productNameRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "productName" must be string, got %s.', get_debug_type($productNameRaw)),
                );
            }
            $productName = Some::create($productNameRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            ['deliveryMethodRemark' => true, 'productCode' => true, 'productName' => true],
        );

        return new self($deliveryMethodRemark, $productCode, $productName, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $deliveryMethodRemarkOption = $this->deliveryMethodRemark;
        if ($deliveryMethodRemarkOption->isDefined()) {
            $deliveryMethodRemark = $deliveryMethodRemarkOption->get();
            $dataArray['deliveryMethodRemark'] = $deliveryMethodRemark;
        }
        $productCodeOption = $this->productCode;
        if ($productCodeOption->isDefined()) {
            $productCode = $productCodeOption->get();
            $dataArray['productCode'] = $productCode;
        }
        $productNameOption = $this->productName;
        if ($productNameOption->isDefined()) {
            $productName = $productNameOption->get();
            $dataArray['productName'] = $productName;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): ProductBuilder
    {
        return new ProductBuilder(
            $this->deliveryMethodRemark,
            $this->productCode,
            $this->productName,
            $this->additionalProperties,
        );
    }
}
