<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

/**
 * Builds a {@see Product}.
 */
final class ProductBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $deliveryMethodRemark
     * @param Option<string>           $productCode
     * @param Option<string>           $productName
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $deliveryMethodRemark,
        private Option $productCode,
        private Option $productName,
        private array $additionalProperties,
    ) {
    }

    /**
     * Specific detail of product.
     */
    public function setDeliveryMethodRemark(string $deliveryMethodRemark): self
    {
        $this->deliveryMethodRemark = Some::create($deliveryMethodRemark);

        return $this;
    }

    public function setProductCode(string $productCode): self
    {
        $this->productCode = Some::create($productCode);

        return $this;
    }

    /**
     * Business unit product or service.
     */
    public function setProductName(string $productName): self
    {
        $this->productName = Some::create($productName);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): Product
    {
        return new Product(
            $this->deliveryMethodRemark,
            $this->productCode,
            $this->productName,
            $this->additionalProperties,
        );
    }
}
