<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

/**
 * Builds a {@see ProofOfDelivery}.
 */
final class ProofOfDeliveryBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>                                    $documentUrl
     * @param Option<string>                                    $signatureUrl
     * @param Option<UnknownEntity|Organization|Company|Person> $signed
     * @param Option<string>                                    $timestamp
     * @param array<int|string, mixed>                          $additionalProperties
     */
    public function __construct(
        private Option $documentUrl,
        private Option $signatureUrl,
        private Option $signed,
        private Option $timestamp,
        private array $additionalProperties,
    ) {
    }

    /**
     * The link to related electronic proof of delivery document.
     */
    public function setDocumentUrl(string $documentUrl): self
    {
        $this->documentUrl = Some::create($documentUrl);

        return $this;
    }

    /**
     * The link to related electronic signature.
     */
    public function setSignatureUrl(string $signatureUrl): self
    {
        $this->signatureUrl = Some::create($signatureUrl);

        return $this;
    }

    /**
     * A real organization or personal entity, if type is not specified, a Organization
     * implementation is used.
     */
    public function setSigned(UnknownEntity|Organization|Company|Person $signed): self
    {
        $this->signed = Some::create($signed);

        return $this;
    }

    /**
     * Date and time of related proof of delivery document.
     */
    public function setTimestamp(string $timestamp): self
    {
        $this->timestamp = Some::create($timestamp);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ProofOfDelivery
    {
        return new ProofOfDelivery(
            $this->documentUrl,
            $this->signatureUrl,
            $this->signed,
            $this->timestamp,
            $this->additionalProperties,
        );
    }
}
