<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\MalformedDataException;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\None;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class ProofOfDelivery implements SelfNormalizingModel
{
    /**
     * @param Option<string>                                    $documentUrl
     * @param Option<string>                                    $signatureUrl
     * @param Option<UnknownEntity|Organization|Company|Person> $signed
     * @param Option<string>                                    $timestamp
     * @param array<int|string, mixed>                          $additionalProperties
     */
    public function __construct(
        private Option $documentUrl,
        private Option $signatureUrl,
        private Option $signed,
        private Option $timestamp,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): ProofOfDeliveryBuilder
    {
        return new ProofOfDeliveryBuilder(None::create(), None::create(), None::create(), None::create(), []);
    }

    /**
     * The link to related electronic proof of delivery document.
     *
     * @return Option<string>
     */
    public function getDocumentUrl(): Option
    {
        return $this->documentUrl;
    }

    /**
     * The link to related electronic signature.
     *
     * @return Option<string>
     */
    public function getSignatureUrl(): Option
    {
        return $this->signatureUrl;
    }

    /**
     * A real organization or personal entity, if type is not specified, a Organization
     * implementation is used.
     *
     * @return Option<UnknownEntity|Organization|Company|Person>
     */
    public function getSigned(): Option
    {
        return $this->signed;
    }

    /**
     * Date and time of related proof of delivery document.
     *
     * @return Option<string>
     */
    public function getTimestamp(): Option
    {
        return $this->timestamp;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $documentUrl = None::create();
        $signatureUrl = None::create();
        $signed = None::create();
        $timestamp = None::create();
        if (array_key_exists('documentUrl', $data) && $data['documentUrl'] !== null) {
            $documentUrlRaw = $data['documentUrl'];
            if (!is_string($documentUrlRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "documentUrl" must be string, got %s.', get_debug_type($documentUrlRaw)),
                );
            }
            $documentUrl = Some::create($documentUrlRaw);
        }
        if (array_key_exists('signatureUrl', $data) && $data['signatureUrl'] !== null) {
            $signatureUrlRaw = $data['signatureUrl'];
            if (!is_string($signatureUrlRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "signatureUrl" must be string, got %s.', get_debug_type($signatureUrlRaw)),
                );
            }
            $signatureUrl = Some::create($signatureUrlRaw);
        }
        if (array_key_exists('signed', $data) && $data['signed'] !== null) {
            if (
                is_array($data['signed'])
                && array_key_exists('@type', $data['signed'])
                && $data['signed']['@type'] === 'UnknownEntity'
            ) {
                /** @var non-empty-array<string, mixed> $signedTyped */
                $signedTyped = $data['signed'];
                $value = UnknownEntity::fromArray($signedTyped);
            } elseif (
                is_array($data['signed'])
                && array_key_exists('@type', $data['signed'])
                && $data['signed']['@type'] === 'Organization'
            ) {
                /** @var non-empty-array<string, mixed> $signedTyped_1 */
                $signedTyped_1 = $data['signed'];
                $value = Organization::fromArray($signedTyped_1);
            } elseif (
                is_array($data['signed'])
                && array_key_exists('@type', $data['signed'])
                && $data['signed']['@type'] === 'Company'
            ) {
                /** @var non-empty-array<string, mixed> $signedTyped_2 */
                $signedTyped_2 = $data['signed'];
                $value = Company::fromArray($signedTyped_2);
            } elseif (
                is_array($data['signed'])
                && array_key_exists('@type', $data['signed'])
                && $data['signed']['@type'] === 'Person'
            ) {
                /** @var non-empty-array<string, mixed> $signedTyped_3 */
                $signedTyped_3 = $data['signed'];
                $value = Person::fromArray($signedTyped_3);
            } else {
                throw new MalformedDataException('Property "signed" matched none of the expected shapes: UnknownEntity, Organization, Company, Person.');
            }
            $signed = Some::create($value);
        }
        if (array_key_exists('timestamp', $data) && $data['timestamp'] !== null) {
            $timestampRaw = $data['timestamp'];
            if (!is_string($timestampRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "timestamp" must be string, got %s.', get_debug_type($timestampRaw)),
                );
            }
            $timestamp = Some::create($timestampRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            ['documentUrl' => true, 'signatureUrl' => true, 'signed' => true, 'timestamp' => true],
        );

        return new self($documentUrl, $signatureUrl, $signed, $timestamp, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $documentUrlOption = $this->documentUrl;
        if ($documentUrlOption->isDefined()) {
            $documentUrl = $documentUrlOption->get();
            $dataArray['documentUrl'] = $documentUrl;
        }
        $signatureUrlOption = $this->signatureUrl;
        if ($signatureUrlOption->isDefined()) {
            $signatureUrl = $signatureUrlOption->get();
            $dataArray['signatureUrl'] = $signatureUrl;
        }
        $signedOption = $this->signed;
        if ($signedOption->isDefined()) {
            $signed = $signedOption->get();
            $value = $normalizationTarget->model($signed);
            $dataArray['signed'] = $value;
        }
        $timestampOption = $this->timestamp;
        if ($timestampOption->isDefined()) {
            $timestamp = $timestampOption->get();
            $dataArray['timestamp'] = $timestamp;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): ProofOfDeliveryBuilder
    {
        return new ProofOfDeliveryBuilder(
            $this->documentUrl,
            $this->signatureUrl,
            $this->signed,
            $this->timestamp,
            $this->additionalProperties,
        );
    }
}
