<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

/**
 * Builds a {@see Provider}.
 */
final class ProviderBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param ProviderDestinationProvider|UnknownEnumValue<string> $destinationProvider
     * @param array<int|string, mixed>                             $additionalProperties
     */
    public function __construct(
        private ProviderDestinationProvider|UnknownEnumValue $destinationProvider,
        private array $additionalProperties,
    ) {
    }

    /**
     * The name of the provider organization handling the delivery in the destination country.
     */
    public function setDestinationProvider(ProviderDestinationProvider $destinationProvider): self
    {
        $this->destinationProvider = $destinationProvider;

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): Provider
    {
        return new Provider($this->destinationProvider, $this->additionalProperties);
    }
}
