<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

enum ProviderDestinationProvider: string
{
    case acs_courier = 'acs-courier';
    case anpost = 'anpost';
    case bpost = 'bpost';
    case bring = 'bring';
    case chronopost = 'chronopost';
    case colis_prive = 'colis-prive';
    case econnect = 'econnect';
    case express = 'express';
    case fastway = 'fastway';
    case freight = 'freight';
    case freight_fr = 'freight-fr';
    case freight_se = 'freight-se';
    case hrvatska_posta = 'hrvatska-posta';
    case magyar_posta = 'magyar-posta';
    case oepag = 'oepag';
    case parcel_be = 'parcel-be';
    case parcel_bl = 'parcel-bl';
    case parcel_cz = 'parcel-cz';
    case parcel_de = 'parcel-de';
    case parcel_es = 'parcel-es';
    case parcel_iberia = 'parcel-iberia';
    case parcel_lu = 'parcel-lu';
    case parcel_nl = 'parcel-nl';
    case parcel_pl = 'parcel-pl';
    case parcel_pt = 'parcel-pt';
    case parcel_uk = 'parcel-uk';
    case posta = 'posta';
    case posta_slovenije = 'posta-slovenije';
    case posti = 'posti';
    case poste_italiane = 'poste-italiane';
    case ppl = 'ppl';
    case rapido = 'rapido';
    case relais_colis = 'relais-colis';
    case slovak_parcel_service = 'slovak-parcel-service';
    case speedy = 'speedy';
    case sps = 'sps';
    case trans_o_flex = 'trans-o-flex';
    case urgent_cargus = 'urgent-cargus';
}
