<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\MalformedDataException;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class Provider implements SelfNormalizingModel
{
    /**
     * @param ProviderDestinationProvider|UnknownEnumValue<string> $destinationProvider
     * @param array<int|string, mixed>                             $additionalProperties
     */
    public function __construct(
        private ProviderDestinationProvider|UnknownEnumValue $destinationProvider,
        private array $additionalProperties,
    ) {
    }

    public static function builder(ProviderDestinationProvider $destinationProvider): ProviderBuilder
    {
        return new ProviderBuilder($destinationProvider, []);
    }

    /**
     * The name of the provider organization handling the delivery in the destination country.
     *
     * @return ProviderDestinationProvider|UnknownEnumValue<string>
     */
    public function getDestinationProvider(): ProviderDestinationProvider|UnknownEnumValue
    {
        return $this->destinationProvider;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $destinationProvider = null;
        if (array_key_exists('destinationProvider', $data)) {
            $destinationProviderRaw = $data['destinationProvider'];
            if (!is_string($destinationProviderRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "destinationProvider" must be string, got %s.',
                        get_debug_type($destinationProviderRaw),
                    ),
                );
            }
            $destinationProvider = ProviderDestinationProvider::tryFrom($destinationProviderRaw)
                ?? UnknownEnumValue::of($destinationProviderRaw);
        }
        $additionalProperties = array_diff_key($data, ['destinationProvider' => true]);
        if ($destinationProvider === null) {
            throw new MalformedDataException('Required property "destinationProvider" is missing from the document.');
        }

        return new self($destinationProvider, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['destinationProvider'] = $this->destinationProvider->value;
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): ProviderBuilder
    {
        return new ProviderBuilder($this->destinationProvider, $this->additionalProperties);
    }
}
