<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\MalformedDataException;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\None;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_float;
use function is_int;
use function is_string;
use function sprintf;

final readonly class QuantitativeValue implements SelfNormalizingModel
{
    /**
     * @param Option<string>           $unitText
     * @param Option<float>            $value
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private Option $unitText, private Option $value, private array $additionalProperties)
    {
    }

    public static function builder(): QuantitativeValueBuilder
    {
        return new QuantitativeValueBuilder(None::create(), None::create(), []);
    }

    /**
     * A string or text indicating the unit of measurement.
     *
     * @return Option<string>
     */
    public function getUnitText(): Option
    {
        return $this->unitText;
    }

    /**
     * The value of the quantitative value or property value node.
     *
     * @return Option<float>
     */
    public function getValue(): Option
    {
        return $this->value;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $unitText = None::create();
        $value = None::create();
        if (array_key_exists('value', $data) && is_int($data['value'])) {
            $data['value'] = (float) $data['value'];
        }
        if (array_key_exists('unitText', $data) && $data['unitText'] !== null) {
            $unitTextRaw = $data['unitText'];
            if (!is_string($unitTextRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "unitText" must be string, got %s.', get_debug_type($unitTextRaw)),
                );
            }
            $unitText = Some::create($unitTextRaw);
        }
        if (array_key_exists('value', $data) && $data['value'] !== null) {
            $valueRaw = $data['value'];
            if (!(is_float($valueRaw) || is_int($valueRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "value" must be number, got %s.', get_debug_type($valueRaw)),
                );
            }
            $value = Some::create((float) $valueRaw);
        }
        $additionalProperties = array_diff_key($data, ['unitText' => true, 'value' => true]);

        return new self($unitText, $value, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $unitTextOption = $this->unitText;
        if ($unitTextOption->isDefined()) {
            $unitText = $unitTextOption->get();
            $dataArray['unitText'] = $unitText;
        }
        $valueOption = $this->value;
        if ($valueOption->isDefined()) {
            $value = $valueOption->get();
            $dataArray['value'] = $value;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): QuantitativeValueBuilder
    {
        return new QuantitativeValueBuilder($this->unitText, $this->value, $this->additionalProperties);
    }
}
