<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

/**
 * Builds a {@see QuantitativeValue}.
 */
final class QuantitativeValueBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $unitText
     * @param Option<float>            $value
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private Option $unitText, private Option $value, private array $additionalProperties)
    {
    }

    /**
     * A string or text indicating the unit of measurement.
     */
    public function setUnitText(string $unitText): self
    {
        $this->unitText = Some::create($unitText);

        return $this;
    }

    /**
     * The value of the quantitative value or property value node.
     */
    public function setValue(float $value): self
    {
        $this->value = Some::create($value);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): QuantitativeValue
    {
        return new QuantitativeValue($this->unitText, $this->value, $this->additionalProperties);
    }
}
