<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

/**
 * Builds a {@see Reference}.
 */
final class ReferenceBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param ReferenceType|UnknownEnumValue<string>       $type
     * @param Option<SecretScope|UnknownEnumValue<string>> $scope
     * @param Option<string>                               $number
     * @param array<int|string, mixed>                     $additionalProperties
     */
    public function __construct(
        private ReferenceType|UnknownEnumValue $type,
        private Option $scope,
        private Option $number,
        private array $additionalProperties,
    ) {
    }

    /**
     * Type of reference.
     */
    public function setType(ReferenceType $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * A secret scope of protected or sensitive information.
     */
    public function setScope(SecretScope $scope): self
    {
        $this->scope = Some::create($scope);

        return $this;
    }

    /**
     * A value of reference.
     */
    public function setNumber(string $number): self
    {
        $this->number = Some::create($number);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): Reference
    {
        return new Reference($this->type, $this->scope, $this->number, $this->additionalProperties);
    }
}
