<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

enum ReferenceType: string
{
    case container_number = 'container-number';
    case customer_confirmation_number = 'customer-confirmation-number';
    case customer_reference = 'customer-reference';
    case domestic_consignment_id = 'domestic-consignment-id';
    case ecommerce_number = 'ecommerce-number';
    case housebill = 'housebill';
    case local_tracking_number = 'local-tracking-number';
    case masterbill = 'masterbill';
    case payer_account_number = 'payer-account-number';
    case receiver_account_number = 'receiver-account-number';
    case reference = 'reference';
    case shipment_id = 'shipment-id';
    case shipper_account_number = 'shipper-account-number';
    case routing_code = 'routing-code';
    case customer_order_number = 'customer-order-number';
}
