<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\MalformedDataException;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\None;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class Reference implements SelfNormalizingModel
{
    /**
     * @param ReferenceType|UnknownEnumValue<string>       $type
     * @param Option<SecretScope|UnknownEnumValue<string>> $scope
     * @param Option<string>                               $number
     * @param array<int|string, mixed>                     $additionalProperties
     */
    public function __construct(
        private ReferenceType|UnknownEnumValue $type,
        private Option $scope,
        private Option $number,
        private array $additionalProperties,
    ) {
    }

    public static function builder(ReferenceType $type): ReferenceBuilder
    {
        return new ReferenceBuilder($type, None::create(), None::create(), []);
    }

    /**
     * A secret scope of protected or sensitive information.
     *
     * @return Option<SecretScope|UnknownEnumValue<string>>
     */
    public function getScope(): Option
    {
        return $this->scope;
    }

    /**
     * A value of reference.
     *
     * @return Option<string>
     */
    public function getNumber(): Option
    {
        return $this->number;
    }

    /**
     * Type of reference.
     *
     * @return ReferenceType|UnknownEnumValue<string>
     */
    public function getType(): ReferenceType|UnknownEnumValue
    {
        return $this->type;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $scope = None::create();
        $number = None::create();
        $type = null;
        if (array_key_exists('@scope', $data) && $data['@scope'] !== null) {
            $scopeRaw = $data['@scope'];
            if (!is_string($scopeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "@scope" must be string, got %s.', get_debug_type($scopeRaw)),
                );
            }
            $scope = Some::create(SecretScope::tryFrom($scopeRaw) ?? UnknownEnumValue::of($scopeRaw));
        }
        if (array_key_exists('number', $data) && $data['number'] !== null) {
            $numberRaw = $data['number'];
            if (!is_string($numberRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "number" must be string, got %s.', get_debug_type($numberRaw)),
                );
            }
            $number = Some::create($numberRaw);
        }
        if (array_key_exists('type', $data)) {
            $typeRaw = $data['type'];
            if (!is_string($typeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "type" must be string, got %s.', get_debug_type($typeRaw)),
                );
            }
            $type = ReferenceType::tryFrom($typeRaw) ?? UnknownEnumValue::of($typeRaw);
        }
        $additionalProperties = array_diff_key($data, ['@scope' => true, 'number' => true, 'type' => true]);
        if ($type === null) {
            throw new MalformedDataException('Required property "type" is missing from the document.');
        }

        return new self($type, $scope, $number, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $scopeOption = $this->scope;
        if ($scopeOption->isDefined()) {
            $scope = $scopeOption->get();
            $dataArray['@scope'] = $scope->value;
        }
        $numberOption = $this->number;
        if ($numberOption->isDefined()) {
            $number = $numberOption->get();
            $dataArray['number'] = $number;
        }
        $dataArray['type'] = $this->type->value;
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): ReferenceBuilder
    {
        return new ReferenceBuilder($this->type, $this->scope, $this->number, $this->additionalProperties);
    }
}
