<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

/**
 * Builds a {@see SecuredAddress}.
 */
final class SecuredAddressBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<SecretPolicy|UnknownEnumValue<string>> $policy
     * @param Option<string>                                $addressLocality
     * @param Option<string>                                $addressLocalityServicing
     * @param Option<string>                                $addressRegion
     * @param Option<string>                                $countryCode
     * @param Option<string>                                $postalCode
     * @param Option<string>                                $streetAddress
     * @param Option<string>                                $addressLine
     * @param array<int|string, mixed>                      $additionalProperties
     */
    public function __construct(
        private Option $policy,
        private Option $addressLocality,
        private Option $addressLocalityServicing,
        private Option $addressRegion,
        private Option $countryCode,
        private Option $postalCode,
        private Option $streetAddress,
        private Option $addressLine,
        private array $additionalProperties,
    ) {
    }

    /**
     * A secret policy protecting sensitive information.
     */
    public function setPolicy(SecretPolicy $policy): self
    {
        $this->policy = Some::create($policy);

        return $this;
    }

    /**
     * Text specifying the name of the locality, for example a city.
     */
    public function setAddressLocality(string $addressLocality): self
    {
        $this->addressLocality = Some::create($addressLocality);

        return $this;
    }

    /**
     * Text specifying a detail of address locality.
     */
    public function setAddressLocalityServicing(string $addressLocalityServicing): self
    {
        $this->addressLocalityServicing = Some::create($addressLocalityServicing);

        return $this;
    }

    /**
     * Text specifying a detail of country.
     */
    public function setAddressRegion(string $addressRegion): self
    {
        $this->addressRegion = Some::create($addressRegion);

        return $this;
    }

    /**
     * Code specifying the country using ISO 3166-1 alpha-2.
     */
    public function setCountryCode(string $countryCode): self
    {
        $this->countryCode = Some::create($countryCode);

        return $this;
    }

    /**
     * Text specifying the postal code for an address.
     */
    public function setPostalCode(string $postalCode): self
    {
        $this->postalCode = Some::create($postalCode);

        return $this;
    }

    /**
     * The street address expressed as free form text.
     */
    public function setStreetAddress(string $streetAddress): self
    {
        $this->streetAddress = Some::create($streetAddress);

        return $this;
    }

    /**
     * Text specifying the addressLine, for example an apartment, suite, or floor number.
     */
    public function setAddressLine(string $addressLine): self
    {
        $this->addressLine = Some::create($addressLine);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): SecuredAddress
    {
        return new SecuredAddress(
            $this->policy,
            $this->addressLocality,
            $this->addressLocalityServicing,
            $this->addressRegion,
            $this->countryCode,
            $this->postalCode,
            $this->streetAddress,
            $this->addressLine,
            $this->additionalProperties,
        );
    }
}
