<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\MalformedDataException;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\None;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function sprintf;

final readonly class SecuredPlace implements SelfNormalizingModel
{
    /**
     * @param Option<SecuredAddress>   $address
     * @param Option<ServicePoint>     $servicePoint
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $address,
        private Option $servicePoint,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): SecuredPlaceBuilder
    {
        return new SecuredPlaceBuilder(None::create(), None::create(), []);
    }

    /**
     * The mailing address secured by policy.
     *
     * @return Option<SecuredAddress>
     */
    public function getAddress(): Option
    {
        return $this->address;
    }

    /** @return Option<ServicePoint> */
    public function getServicePoint(): Option
    {
        return $this->servicePoint;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $address = None::create();
        $servicePoint = None::create();
        if (array_key_exists('address', $data) && $data['address'] !== null) {
            $addressRaw = $data['address'];
            if (!is_array($addressRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "address" must be object, got %s.', get_debug_type($addressRaw)),
                );
            }
            /** @var array<string, mixed> $addressRawTyped */
            $addressRawTyped = $addressRaw;
            $address = Some::create(SecuredAddress::fromArray($addressRawTyped));
        }
        if (array_key_exists('servicePoint', $data) && $data['servicePoint'] !== null) {
            $servicePointRaw = $data['servicePoint'];
            if (!is_array($servicePointRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "servicePoint" must be object, got %s.', get_debug_type($servicePointRaw)),
                );
            }
            /** @var array<string, mixed> $servicePointRawTyped */
            $servicePointRawTyped = $servicePointRaw;
            $servicePoint = Some::create(ServicePoint::fromArray($servicePointRawTyped));
        }
        $additionalProperties = array_diff_key($data, ['address' => true, 'servicePoint' => true]);

        return new self($address, $servicePoint, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $addressOption = $this->address;
        if ($addressOption->isDefined()) {
            $address = $addressOption->get();
            $dataArray['address'] = $normalizationTarget->model($address);
        }
        $servicePointOption = $this->servicePoint;
        if ($servicePointOption->isDefined()) {
            $servicePoint = $servicePointOption->get();
            $dataArray['servicePoint'] = $normalizationTarget->model($servicePoint);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): SecuredPlaceBuilder
    {
        return new SecuredPlaceBuilder($this->address, $this->servicePoint, $this->additionalProperties);
    }
}
