<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\MalformedDataException;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\None;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class SecuredAddress implements SelfNormalizingModel
{
    /**
     * @param Option<SecretPolicy|UnknownEnumValue<string>> $policy
     * @param Option<string>                                $addressLocality
     * @param Option<string>                                $addressLocalityServicing
     * @param Option<string>                                $addressRegion
     * @param Option<string>                                $countryCode
     * @param Option<string>                                $postalCode
     * @param Option<string>                                $streetAddress
     * @param Option<string>                                $addressLine
     * @param array<int|string, mixed>                      $additionalProperties
     */
    public function __construct(
        private Option $policy,
        private Option $addressLocality,
        private Option $addressLocalityServicing,
        private Option $addressRegion,
        private Option $countryCode,
        private Option $postalCode,
        private Option $streetAddress,
        private Option $addressLine,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): SecuredAddressBuilder
    {
        return new SecuredAddressBuilder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * A secret policy protecting sensitive information.
     *
     * Default: `"postal-code"`.
     *
     * @return Option<SecretPolicy|UnknownEnumValue<string>>
     */
    public function getPolicy(): Option
    {
        return $this->policy;
    }

    /**
     * Text specifying the name of the locality, for example a city.
     *
     * @return Option<string>
     */
    public function getAddressLocality(): Option
    {
        return $this->addressLocality;
    }

    /**
     * Text specifying a detail of address locality.
     *
     * @return Option<string>
     */
    public function getAddressLocalityServicing(): Option
    {
        return $this->addressLocalityServicing;
    }

    /**
     * Text specifying a detail of country.
     *
     * @return Option<string>
     */
    public function getAddressRegion(): Option
    {
        return $this->addressRegion;
    }

    /**
     * Code specifying the country using ISO 3166-1 alpha-2.
     *
     * @return Option<string>
     */
    public function getCountryCode(): Option
    {
        return $this->countryCode;
    }

    /**
     * Text specifying the postal code for an address.
     *
     * @return Option<string>
     */
    public function getPostalCode(): Option
    {
        return $this->postalCode;
    }

    /**
     * The street address expressed as free form text.
     *
     * @return Option<string>
     */
    public function getStreetAddress(): Option
    {
        return $this->streetAddress;
    }

    /**
     * Text specifying the addressLine, for example an apartment, suite, or floor number.
     *
     * @return Option<string>
     */
    public function getAddressLine(): Option
    {
        return $this->addressLine;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $policy = None::create();
        $addressLocality = None::create();
        $addressLocalityServicing = None::create();
        $addressRegion = None::create();
        $countryCode = None::create();
        $postalCode = None::create();
        $streetAddress = None::create();
        $addressLine = None::create();
        if (array_key_exists('@policy', $data) && $data['@policy'] !== null) {
            $policyRaw = $data['@policy'];
            if (!is_string($policyRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "@policy" must be string, got %s.', get_debug_type($policyRaw)),
                );
            }
            $policy = Some::create(SecretPolicy::tryFrom($policyRaw) ?? UnknownEnumValue::of($policyRaw));
        }
        if (array_key_exists('addressLocality', $data) && $data['addressLocality'] !== null) {
            $addressLocalityRaw = $data['addressLocality'];
            if (!is_string($addressLocalityRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "addressLocality" must be string, got %s.', get_debug_type($addressLocalityRaw)),
                );
            }
            $addressLocality = Some::create($addressLocalityRaw);
        }
        if (array_key_exists('addressLocalityServicing', $data) && $data['addressLocalityServicing'] !== null) {
            $addressLocalityServicingRaw = $data['addressLocalityServicing'];
            if (!is_string($addressLocalityServicingRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "addressLocalityServicing" must be string, got %s.',
                        get_debug_type($addressLocalityServicingRaw),
                    ),
                );
            }
            $addressLocalityServicing = Some::create($addressLocalityServicingRaw);
        }
        if (array_key_exists('addressRegion', $data) && $data['addressRegion'] !== null) {
            $addressRegionRaw = $data['addressRegion'];
            if (!is_string($addressRegionRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "addressRegion" must be string, got %s.', get_debug_type($addressRegionRaw)),
                );
            }
            $addressRegion = Some::create($addressRegionRaw);
        }
        if (array_key_exists('countryCode', $data) && $data['countryCode'] !== null) {
            $countryCodeRaw = $data['countryCode'];
            if (!is_string($countryCodeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "countryCode" must be string, got %s.', get_debug_type($countryCodeRaw)),
                );
            }
            $countryCode = Some::create($countryCodeRaw);
        }
        if (array_key_exists('postalCode', $data) && $data['postalCode'] !== null) {
            $postalCodeRaw = $data['postalCode'];
            if (!is_string($postalCodeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "postalCode" must be string, got %s.', get_debug_type($postalCodeRaw)),
                );
            }
            $postalCode = Some::create($postalCodeRaw);
        }
        if (array_key_exists('streetAddress', $data) && $data['streetAddress'] !== null) {
            $streetAddressRaw = $data['streetAddress'];
            if (!is_string($streetAddressRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "streetAddress" must be string, got %s.', get_debug_type($streetAddressRaw)),
                );
            }
            $streetAddress = Some::create($streetAddressRaw);
        }
        if (array_key_exists('addressLine', $data) && $data['addressLine'] !== null) {
            $addressLineRaw = $data['addressLine'];
            if (!is_string($addressLineRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "addressLine" must be string, got %s.', get_debug_type($addressLineRaw)),
                );
            }
            $addressLine = Some::create($addressLineRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                '@policy' => true,
                'addressLocality' => true,
                'addressLocalityServicing' => true,
                'addressRegion' => true,
                'countryCode' => true,
                'postalCode' => true,
                'streetAddress' => true,
                'addressLine' => true,
            ],
        );

        return new self(
            $policy,
            $addressLocality,
            $addressLocalityServicing,
            $addressRegion,
            $countryCode,
            $postalCode,
            $streetAddress,
            $addressLine,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $policyOption = $this->policy;
        if ($policyOption->isDefined()) {
            $policy = $policyOption->get();
            $dataArray['@policy'] = $policy->value;
        }
        $addressLocalityOption = $this->addressLocality;
        if ($addressLocalityOption->isDefined()) {
            $addressLocality = $addressLocalityOption->get();
            $dataArray['addressLocality'] = $addressLocality;
        }
        $addressLocalityServicingOption = $this->addressLocalityServicing;
        if ($addressLocalityServicingOption->isDefined()) {
            $addressLocalityServicing = $addressLocalityServicingOption->get();
            $dataArray['addressLocalityServicing'] = $addressLocalityServicing;
        }
        $addressRegionOption = $this->addressRegion;
        if ($addressRegionOption->isDefined()) {
            $addressRegion = $addressRegionOption->get();
            $dataArray['addressRegion'] = $addressRegion;
        }
        $countryCodeOption = $this->countryCode;
        if ($countryCodeOption->isDefined()) {
            $countryCode = $countryCodeOption->get();
            $dataArray['countryCode'] = $countryCode;
        }
        $postalCodeOption = $this->postalCode;
        if ($postalCodeOption->isDefined()) {
            $postalCode = $postalCodeOption->get();
            $dataArray['postalCode'] = $postalCode;
        }
        $streetAddressOption = $this->streetAddress;
        if ($streetAddressOption->isDefined()) {
            $streetAddress = $streetAddressOption->get();
            $dataArray['streetAddress'] = $streetAddress;
        }
        $addressLineOption = $this->addressLine;
        if ($addressLineOption->isDefined()) {
            $addressLine = $addressLineOption->get();
            $dataArray['addressLine'] = $addressLine;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): SecuredAddressBuilder
    {
        return new SecuredAddressBuilder(
            $this->policy,
            $this->addressLocality,
            $this->addressLocalityServicing,
            $this->addressRegion,
            $this->countryCode,
            $this->postalCode,
            $this->streetAddress,
            $this->addressLine,
            $this->additionalProperties,
        );
    }
}
