<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

/**
 * Builds a {@see SecuredPlace}.
 */
final class SecuredPlaceBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<SecuredAddress>   $address
     * @param Option<ServicePoint>     $servicePoint
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $address,
        private Option $servicePoint,
        private array $additionalProperties,
    ) {
    }

    /**
     * The mailing address secured by policy.
     */
    public function setAddress(SecuredAddress $address): self
    {
        $this->address = Some::create($address);

        return $this;
    }

    public function setServicePoint(ServicePoint $servicePoint): self
    {
        $this->servicePoint = Some::create($servicePoint);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): SecuredPlace
    {
        return new SecuredPlace($this->address, $this->servicePoint, $this->additionalProperties);
    }
}
