<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\MalformedDataException;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\None;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class ServicePoint implements SelfNormalizingModel
{
    /**
     * @param Option<string>           $url
     * @param Option<string>           $label
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private Option $url, private Option $label, private array $additionalProperties)
    {
    }

    public static function builder(): ServicePointBuilder
    {
        return new ServicePointBuilder(None::create(), None::create(), []);
    }

    /** @return Option<string> */
    public function getUrl(): Option
    {
        return $this->url;
    }

    /** @return Option<string> */
    public function getLabel(): Option
    {
        return $this->label;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $url = None::create();
        $label = None::create();
        if (array_key_exists('url', $data) && $data['url'] !== null) {
            $urlRaw = $data['url'];
            if (!is_string($urlRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "url" must be string, got %s.', get_debug_type($urlRaw)),
                );
            }
            $url = Some::create($urlRaw);
        }
        if (array_key_exists('label', $data) && $data['label'] !== null) {
            $labelRaw = $data['label'];
            if (!is_string($labelRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "label" must be string, got %s.', get_debug_type($labelRaw)),
                );
            }
            $label = Some::create($labelRaw);
        }
        $additionalProperties = array_diff_key($data, ['url' => true, 'label' => true]);

        return new self($url, $label, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $urlOption = $this->url;
        if ($urlOption->isDefined()) {
            $url = $urlOption->get();
            $dataArray['url'] = $url;
        }
        $labelOption = $this->label;
        if ($labelOption->isDefined()) {
            $label = $labelOption->get();
            $dataArray['label'] = $label;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): ServicePointBuilder
    {
        return new ServicePointBuilder($this->url, $this->label, $this->additionalProperties);
    }
}
