<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

enum Service: string
{
    case dgf = 'dgf';
    case dsc = 'dsc';
    case ecommerce = 'ecommerce';
    case ecommerce_apac = 'ecommerce-apac';
    case ecommerce_europe = 'ecommerce-europe';
    case ecommerce_ppl = 'ecommerce-ppl';
    case ecommerce_iberia = 'ecommerce-iberia';
    case express = 'express';
    case freight = 'freight';
    case parcel_de = 'parcel-de';
    case parcel_nl = 'parcel-nl';
    case parcel_pl = 'parcel-pl';
    case parcel_uk = 'parcel-uk';
    case post_de = 'post-de';
    case post_international = 'post-international';
    case sameday = 'sameday';
    case svb = 'svb';
}
