<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

/**
 * Builds a {@see ServicePoint}.
 */
final class ServicePointBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $url
     * @param Option<string>           $label
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private Option $url, private Option $label, private array $additionalProperties)
    {
    }

    public function setUrl(string $url): self
    {
        $this->url = Some::create($url);

        return $this;
    }

    public function setLabel(string $label): self
    {
        $this->label = Some::create($label);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ServicePoint
    {
        return new ServicePoint($this->url, $this->label, $this->additionalProperties);
    }
}
