<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

enum StatusCode: string
{
    case delivered = 'delivered';
    case failure = 'failure';
    case pre_transit = 'pre-transit';
    case transit = 'transit';
    case unknown = 'unknown';
}
