<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

enum TemperatureUnit: string
{
    case celsius = 'celsius';
    case fahrenheit = 'fahrenheit';
    case kelvin = 'kelvin';
}
