<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\MalformedDataException;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\None;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class Temperature implements SelfNormalizingModel
{
    /**
     * @param Option<string>                                   $value
     * @param Option<TemperatureUnit|UnknownEnumValue<string>> $unit
     * @param Option<string>                                   $deviceId
     * @param array<int|string, mixed>                         $additionalProperties
     */
    public function __construct(
        private Option $value,
        private Option $unit,
        private Option $deviceId,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): TemperatureBuilder
    {
        return new TemperatureBuilder(None::create(), None::create(), None::create(), []);
    }

    /**
     * Temperature value.
     *
     * @return Option<string>
     */
    public function getValue(): Option
    {
        return $this->value;
    }

    /**
     * Unit of measurement.
     *
     * @return Option<TemperatureUnit|UnknownEnumValue<string>>
     */
    public function getUnit(): Option
    {
        return $this->unit;
    }

    /**
     * Sensor device id measured the temperature.
     *
     * @return Option<string>
     */
    public function getDeviceId(): Option
    {
        return $this->deviceId;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $value = None::create();
        $unit = None::create();
        $deviceId = None::create();
        if (array_key_exists('value', $data) && $data['value'] !== null) {
            $valueRaw = $data['value'];
            if (!is_string($valueRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "value" must be string, got %s.', get_debug_type($valueRaw)),
                );
            }
            $value = Some::create($valueRaw);
        }
        if (array_key_exists('unit', $data) && $data['unit'] !== null) {
            $unitRaw = $data['unit'];
            if (!is_string($unitRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "unit" must be string, got %s.', get_debug_type($unitRaw)),
                );
            }
            $unit = Some::create(TemperatureUnit::tryFrom($unitRaw) ?? UnknownEnumValue::of($unitRaw));
        }
        if (array_key_exists('deviceId', $data) && $data['deviceId'] !== null) {
            $deviceIdRaw = $data['deviceId'];
            if (!is_string($deviceIdRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "deviceId" must be string, got %s.', get_debug_type($deviceIdRaw)),
                );
            }
            $deviceId = Some::create($deviceIdRaw);
        }
        $additionalProperties = array_diff_key($data, ['value' => true, 'unit' => true, 'deviceId' => true]);

        return new self($value, $unit, $deviceId, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $valueOption = $this->value;
        if ($valueOption->isDefined()) {
            $value = $valueOption->get();
            $dataArray['value'] = $value;
        }
        $unitOption = $this->unit;
        if ($unitOption->isDefined()) {
            $unit = $unitOption->get();
            $dataArray['unit'] = $unit->value;
        }
        $deviceIdOption = $this->deviceId;
        if ($deviceIdOption->isDefined()) {
            $deviceId = $deviceIdOption->get();
            $dataArray['deviceId'] = $deviceId;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): TemperatureBuilder
    {
        return new TemperatureBuilder($this->value, $this->unit, $this->deviceId, $this->additionalProperties);
    }
}
