<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

/**
 * Builds a {@see Temperature}.
 */
final class TemperatureBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>                                   $value
     * @param Option<TemperatureUnit|UnknownEnumValue<string>> $unit
     * @param Option<string>                                   $deviceId
     * @param array<int|string, mixed>                         $additionalProperties
     */
    public function __construct(
        private Option $value,
        private Option $unit,
        private Option $deviceId,
        private array $additionalProperties,
    ) {
    }

    /**
     * Temperature value.
     */
    public function setValue(string $value): self
    {
        $this->value = Some::create($value);

        return $this;
    }

    /**
     * Unit of measurement.
     */
    public function setUnit(TemperatureUnit $unit): self
    {
        $this->unit = Some::create($unit);

        return $this;
    }

    /**
     * Sensor device id measured the temperature.
     */
    public function setDeviceId(string $deviceId): self
    {
        $this->deviceId = Some::create($deviceId);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): Temperature
    {
        return new Temperature($this->value, $this->unit, $this->deviceId, $this->additionalProperties);
    }
}
