<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\MalformedDataException;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\None;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class TrackingShipmentEvent implements SelfNormalizingModel
{
    /**
     * @param StatusCode|UnknownEnumValue<string> $statusCode
     * @param Option<SecuredPlace>                $location
     * @param Option<string>                      $status
     * @param Option<string>                      $statusDetailed
     * @param Option<string>                      $description
     * @param Option<string>                      $remark
     * @param Option<string>                      $nextSteps
     * @param Option<list<string>>                $pieceIds
     * @param array<int|string, mixed>            $additionalProperties
     */
    public function __construct(
        private string $timestamp,
        private StatusCode|UnknownEnumValue $statusCode,
        private Option $location,
        private Option $status,
        private Option $statusDetailed,
        private Option $description,
        private Option $remark,
        private Option $nextSteps,
        private Option $pieceIds,
        private array $additionalProperties,
    ) {
    }

    public static function builder(string $timestamp, StatusCode $statusCode): TrackingShipmentEventBuilder
    {
        return new TrackingShipmentEventBuilder(
            $timestamp,
            $statusCode,
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * A combination of date and time of day.
     */
    public function getTimestamp(): string
    {
        return $this->timestamp;
    }

    /**
     * The location of object.
     *
     * @return Option<SecuredPlace>
     */
    public function getLocation(): Option
    {
        return $this->location;
    }

    /**
     * Code of the status (high-level grouping statuses).
     *
     * @return StatusCode|UnknownEnumValue<string>
     */
    public function getStatusCode(): StatusCode|UnknownEnumValue
    {
        return $this->statusCode;
    }

    /**
     * Short description of the status - title.
     *
     * @return Option<string>
     */
    public function getStatus(): Option
    {
        return $this->status;
    }

    /**
     * Detailed status of the shipment.
     *
     * @return Option<string>
     */
    public function getStatusDetailed(): Option
    {
        return $this->statusDetailed;
    }

    /**
     * Human-readable detailed description.
     *
     * @return Option<string>
     */
    public function getDescription(): Option
    {
        return $this->description;
    }

    /**
     * Remark regarding the shipment status.
     *
     * @return Option<string>
     */
    public function getRemark(): Option
    {
        return $this->remark;
    }

    /**
     * Description of the next steps.
     *
     * @return Option<string>
     */
    public function getNextSteps(): Option
    {
        return $this->nextSteps;
    }

    /**
     * Ids of all the items or pieces in the shipment.
     *
     * @return Option<list<string>>
     */
    public function getPieceIds(): Option
    {
        return $this->pieceIds;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $timestamp = null;
        $location = None::create();
        $statusCode = null;
        $status = None::create();
        $statusDetailed = None::create();
        $description = None::create();
        $remark = None::create();
        $nextSteps = None::create();
        $pieceIds = None::create();
        if (array_key_exists('timestamp', $data)) {
            $timestampRaw = $data['timestamp'];
            if (!is_string($timestampRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "timestamp" must be string, got %s.', get_debug_type($timestampRaw)),
                );
            }
            $timestamp = $timestampRaw;
        }
        if (array_key_exists('location', $data) && $data['location'] !== null) {
            $locationRaw = $data['location'];
            if (!is_array($locationRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "location" must be object, got %s.', get_debug_type($locationRaw)),
                );
            }
            /** @var array<string, mixed> $locationRawTyped */
            $locationRawTyped = $locationRaw;
            $location = Some::create(SecuredPlace::fromArray($locationRawTyped));
        }
        if (array_key_exists('statusCode', $data)) {
            $statusCodeRaw = $data['statusCode'];
            if (!is_string($statusCodeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "statusCode" must be string, got %s.', get_debug_type($statusCodeRaw)),
                );
            }
            $statusCode = StatusCode::tryFrom($statusCodeRaw) ?? UnknownEnumValue::of($statusCodeRaw);
        }
        if (array_key_exists('status', $data) && $data['status'] !== null) {
            $statusRaw = $data['status'];
            if (!is_string($statusRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "status" must be string, got %s.', get_debug_type($statusRaw)),
                );
            }
            $status = Some::create($statusRaw);
        }
        if (array_key_exists('statusDetailed', $data) && $data['statusDetailed'] !== null) {
            $statusDetailedRaw = $data['statusDetailed'];
            if (!is_string($statusDetailedRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "statusDetailed" must be string, got %s.', get_debug_type($statusDetailedRaw)),
                );
            }
            $statusDetailed = Some::create($statusDetailedRaw);
        }
        if (array_key_exists('description', $data) && $data['description'] !== null) {
            $descriptionRaw = $data['description'];
            if (!is_string($descriptionRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "description" must be string, got %s.', get_debug_type($descriptionRaw)),
                );
            }
            $description = Some::create($descriptionRaw);
        }
        if (array_key_exists('remark', $data) && $data['remark'] !== null) {
            $remarkRaw = $data['remark'];
            if (!is_string($remarkRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "remark" must be string, got %s.', get_debug_type($remarkRaw)),
                );
            }
            $remark = Some::create($remarkRaw);
        }
        if (array_key_exists('nextSteps', $data) && $data['nextSteps'] !== null) {
            $nextStepsRaw = $data['nextSteps'];
            if (!is_string($nextStepsRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "nextSteps" must be string, got %s.', get_debug_type($nextStepsRaw)),
                );
            }
            $nextSteps = Some::create($nextStepsRaw);
        }
        if (array_key_exists('pieceIds', $data) && $data['pieceIds'] !== null) {
            $pieceIdsRaw = $data['pieceIds'];
            if (!(is_array($pieceIdsRaw) && array_is_list($pieceIdsRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "pieceIds" must be list, got %s.', get_debug_type($pieceIdsRaw)),
                );
            }
            $pieceIds = Some::create(array_map(static function (mixed $value): string {
                if (!is_string($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be string, got %s.', get_debug_type($value)),
                    );
                }

                return $value;
            }, $pieceIdsRaw));
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'timestamp' => true,
                'location' => true,
                'statusCode' => true,
                'status' => true,
                'statusDetailed' => true,
                'description' => true,
                'remark' => true,
                'nextSteps' => true,
                'pieceIds' => true,
            ],
        );
        if ($timestamp === null) {
            throw new MalformedDataException('Required property "timestamp" is missing from the document.');
        }
        if ($statusCode === null) {
            throw new MalformedDataException('Required property "statusCode" is missing from the document.');
        }

        return new self(
            $timestamp,
            $statusCode,
            $location,
            $status,
            $statusDetailed,
            $description,
            $remark,
            $nextSteps,
            $pieceIds,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['timestamp'] = $this->timestamp;
        $locationOption = $this->location;
        if ($locationOption->isDefined()) {
            $location = $locationOption->get();
            $dataArray['location'] = $normalizationTarget->model($location);
        }
        $dataArray['statusCode'] = $this->statusCode->value;
        $statusOption = $this->status;
        if ($statusOption->isDefined()) {
            $status = $statusOption->get();
            $dataArray['status'] = $status;
        }
        $statusDetailedOption = $this->statusDetailed;
        if ($statusDetailedOption->isDefined()) {
            $statusDetailed = $statusDetailedOption->get();
            $dataArray['statusDetailed'] = $statusDetailed;
        }
        $descriptionOption = $this->description;
        if ($descriptionOption->isDefined()) {
            $description = $descriptionOption->get();
            $dataArray['description'] = $description;
        }
        $remarkOption = $this->remark;
        if ($remarkOption->isDefined()) {
            $remark = $remarkOption->get();
            $dataArray['remark'] = $remark;
        }
        $nextStepsOption = $this->nextSteps;
        if ($nextStepsOption->isDefined()) {
            $nextSteps = $nextStepsOption->get();
            $dataArray['nextSteps'] = $nextSteps;
        }
        $pieceIdsOption = $this->pieceIds;
        if ($pieceIdsOption->isDefined()) {
            $pieceIds = $pieceIdsOption->get();
            $values = [];
            foreach ($pieceIds as $value) {
                $values[] = $value;
            }
            $dataArray['pieceIds'] = $values;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): TrackingShipmentEventBuilder
    {
        return new TrackingShipmentEventBuilder(
            $this->timestamp,
            $this->statusCode,
            $this->location,
            $this->status,
            $this->statusDetailed,
            $this->description,
            $this->remark,
            $this->nextSteps,
            $this->pieceIds,
            $this->additionalProperties,
        );
    }
}
