<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

/**
 * Builds a {@see TrackingShipmentStatus}.
 */
final class TrackingShipmentStatusBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param StatusCode|UnknownEnumValue<string> $statusCode
     * @param Option<SecuredPlace>                $location
     * @param Option<string>                      $status
     * @param Option<string>                      $statusDetailed
     * @param Option<string>                      $description
     * @param Option<string>                      $remark
     * @param Option<string>                      $nextSteps
     * @param array<int|string, mixed>            $additionalProperties
     */
    public function __construct(
        private string $timestamp,
        private StatusCode|UnknownEnumValue $statusCode,
        private Option $location,
        private Option $status,
        private Option $statusDetailed,
        private Option $description,
        private Option $remark,
        private Option $nextSteps,
        private array $additionalProperties,
    ) {
    }

    /**
     * A combination of date and time of day.
     */
    public function setTimestamp(string $timestamp): self
    {
        $this->timestamp = $timestamp;

        return $this;
    }

    /**
     * Code of the status (high-level grouping statuses).
     */
    public function setStatusCode(StatusCode $statusCode): self
    {
        $this->statusCode = $statusCode;

        return $this;
    }

    /**
     * The location of object.
     */
    public function setLocation(SecuredPlace $location): self
    {
        $this->location = Some::create($location);

        return $this;
    }

    /**
     * Short description of the status - title.
     */
    public function setStatus(string $status): self
    {
        $this->status = Some::create($status);

        return $this;
    }

    /**
     * Detailed status of the shipment.
     */
    public function setStatusDetailed(string $statusDetailed): self
    {
        $this->statusDetailed = Some::create($statusDetailed);

        return $this;
    }

    /**
     * Human-readable detailed description.
     */
    public function setDescription(string $description): self
    {
        $this->description = Some::create($description);

        return $this;
    }

    /**
     * Remark regarding the shipment status.
     */
    public function setRemark(string $remark): self
    {
        $this->remark = Some::create($remark);

        return $this;
    }

    /**
     * Description of the next steps.
     */
    public function setNextSteps(string $nextSteps): self
    {
        $this->nextSteps = Some::create($nextSteps);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): TrackingShipmentStatus
    {
        return new TrackingShipmentStatus(
            $this->timestamp,
            $this->statusCode,
            $this->location,
            $this->status,
            $this->statusDetailed,
            $this->description,
            $this->remark,
            $this->nextSteps,
            $this->additionalProperties,
        );
    }
}
