<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\MalformedDataException;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\None;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function is_bool;
use function is_float;
use function is_int;
use function is_string;
use function sprintf;

final readonly class TrackingShipmentDetails implements SelfNormalizingModel
{
    /**
     * @param Option<Product>                                           $product
     * @param Option<Provider>                                          $provider
     * @param Option<UnknownEntity|Organization|Company|Person>         $receiver
     * @param Option<UnknownEntity|Organization|Company|Person>         $sender
     * @param Option<UnknownEntity|Organization|Company|Person>         $carrier
     * @param Option<UnknownEntity|Organization|Company|Person>         $shipper
     * @param Option<UnknownEntity|Organization|Company|Person>         $consignee
     * @param Option<ProofOfDelivery>                                   $proofOfDelivery
     * @param Option<bool>                                              $proofOfDeliverySignedAvailable
     * @param Option<int>                                               $totalNumberOfPieces
     * @param Option<list<string>>                                      $pieceIds
     * @param Option<QuantitativeValue>                                 $weight
     * @param Option<QuantitativeValue>                                 $volume
     * @param Option<float>                                             $loadingMeters
     * @param Option<Dimensions>                                        $dimensions
     * @param Option<list<Reference>>                                   $references
     * @param Option<ValueAddedServices>                                $valueAddedServices
     * @param Option<list<ControlledDataCode|UnknownEnumValue<string>>> $controlledDataCodes
     * @param Option<string>                                            $shipmentActivationDate
     * @param Option<list<DgfRoute>>                                    $dgfRoutes
     * @param Option<list<Measurement>>                                 $telemetry
     * @param array<int|string, mixed>                                  $additionalProperties
     */
    public function __construct(
        private Option $product,
        private Option $provider,
        private Option $receiver,
        private Option $sender,
        private Option $carrier,
        private Option $shipper,
        private Option $consignee,
        private Option $proofOfDelivery,
        private Option $proofOfDeliverySignedAvailable,
        private Option $totalNumberOfPieces,
        private Option $pieceIds,
        private Option $weight,
        private Option $volume,
        private Option $loadingMeters,
        private Option $dimensions,
        private Option $references,
        private Option $valueAddedServices,
        private Option $controlledDataCodes,
        private Option $shipmentActivationDate,
        private Option $dgfRoutes,
        private Option $telemetry,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): TrackingShipmentDetailsBuilder
    {
        return new TrackingShipmentDetailsBuilder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * Offered product or service.
     *
     * @return Option<Product>
     */
    public function getProduct(): Option
    {
        return $this->product;
    }

    /**
     * The service provider, service operator, or service performer.
     *
     * @return Option<Provider>
     */
    public function getProvider(): Option
    {
        return $this->provider;
    }

    /**
     * A real organization or personal entity, if type is not specified, a Organization
     * implementation is used.
     *
     * @return Option<UnknownEntity|Organization|Company|Person>
     */
    public function getReceiver(): Option
    {
        return $this->receiver;
    }

    /**
     * A real organization or personal entity, if type is not specified, a Organization
     * implementation is used.
     *
     * @return Option<UnknownEntity|Organization|Company|Person>
     */
    public function getSender(): Option
    {
        return $this->sender;
    }

    /**
     * A real organization or personal entity, if type is not specified, a Organization
     * implementation is used.
     *
     * @return Option<UnknownEntity|Organization|Company|Person>
     */
    public function getCarrier(): Option
    {
        return $this->carrier;
    }

    /**
     * A real organization or personal entity, if type is not specified, a Organization
     * implementation is used.
     *
     * @return Option<UnknownEntity|Organization|Company|Person>
     */
    public function getShipper(): Option
    {
        return $this->shipper;
    }

    /**
     * A real organization or personal entity, if type is not specified, a Organization
     * implementation is used.
     *
     * @return Option<UnknownEntity|Organization|Company|Person>
     */
    public function getConsignee(): Option
    {
        return $this->consignee;
    }

    /**
     * An acknowledgment that an order successfully arrived at its intended destination.
     *
     * @return Option<ProofOfDelivery>
     */
    public function getProofOfDelivery(): Option
    {
        return $this->proofOfDelivery;
    }

    /**
     * \'Yes\' if signer identification is available.
     *
     * @return Option<bool>
     */
    public function getProofOfDeliverySignedAvailable(): Option
    {
        return $this->proofOfDeliverySignedAvailable;
    }

    /**
     * Total number of items or pieces in the shipment.
     *
     * @return Option<int>
     */
    public function getTotalNumberOfPieces(): Option
    {
        return $this->totalNumberOfPieces;
    }

    /**
     * Ids of all the items or pieces in the shipment.
     *
     * @return Option<list<string>>
     */
    public function getPieceIds(): Option
    {
        return $this->pieceIds;
    }

    /**
     * A point value or interval for product characteristics and other purposes.
     *
     * @return Option<QuantitativeValue>
     */
    public function getWeight(): Option
    {
        return $this->weight;
    }

    /**
     * A point value or interval for product characteristics and other purposes.
     *
     * @return Option<QuantitativeValue>
     */
    public function getVolume(): Option
    {
        return $this->volume;
    }

    /**
     * A loading meter standard unit of measurement for transport by truck.
     *
     * @return Option<float>
     */
    public function getLoadingMeters(): Option
    {
        return $this->loadingMeters;
    }

    /**
     * A measurable extent of a particular kind of delivery.
     *
     * @return Option<Dimensions>
     */
    public function getDimensions(): Option
    {
        return $this->dimensions;
    }

    /**
     * A list of indications that refers to related shipment.
     *
     * @return Option<list<Reference>>
     */
    public function getReferences(): Option
    {
        return $this->references;
    }

    /**
     * Services I booked together with my Tracking details.
     *
     * @return Option<ValueAddedServices>
     */
    public function getValueAddedServices(): Option
    {
        return $this->valueAddedServices;
    }

    /**
     * Extra Controlled Access Data Codes.
     *
     * @return Option<list<ControlledDataCode|UnknownEnumValue<string>>>
     */
    public function getControlledDataCodes(): Option
    {
        return $this->controlledDataCodes;
    }

    /**
     * Shipment Activation date.
     *
     * @return Option<string>
     */
    public function getShipmentActivationDate(): Option
    {
        return $this->shipmentActivationDate;
    }

    /**
     * DHL Global Forwarding routing Details.
     *
     * @return Option<list<DgfRoute>>
     */
    public function getDgfRoutes(): Option
    {
        return $this->dgfRoutes;
    }

    /**
     * list of all sensor measurements from devices.
     *
     * @return Option<list<Measurement>>
     */
    public function getTelemetry(): Option
    {
        return $this->telemetry;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $product = None::create();
        $provider = None::create();
        $receiver = None::create();
        $sender = None::create();
        $carrier = None::create();
        $shipper = None::create();
        $consignee = None::create();
        $proofOfDelivery = None::create();
        $proofOfDeliverySignedAvailable = None::create();
        $totalNumberOfPieces = None::create();
        $pieceIds = None::create();
        $weight = None::create();
        $volume = None::create();
        $loadingMeters = None::create();
        $dimensions = None::create();
        $references = None::create();
        $valueAddedServices = None::create();
        $controlledDataCodes = None::create();
        $shipmentActivationDate = None::create();
        $dgfRoutes = None::create();
        $telemetry = None::create();
        if (array_key_exists('loadingMeters', $data) && is_int($data['loadingMeters'])) {
            $data['loadingMeters'] = (float) $data['loadingMeters'];
        }
        if (array_key_exists('product', $data) && $data['product'] !== null) {
            $productRaw = $data['product'];
            if (!is_array($productRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "product" must be object, got %s.', get_debug_type($productRaw)),
                );
            }
            /** @var array<string, mixed> $productRawTyped */
            $productRawTyped = $productRaw;
            $product = Some::create(Product::fromArray($productRawTyped));
        }
        if (array_key_exists('provider', $data) && $data['provider'] !== null) {
            $providerRaw = $data['provider'];
            if (!is_array($providerRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "provider" must be object, got %s.', get_debug_type($providerRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $providerRawTyped */
            $providerRawTyped = $providerRaw;
            $provider = Some::create(Provider::fromArray($providerRawTyped));
        }
        if (array_key_exists('receiver', $data) && $data['receiver'] !== null) {
            if (
                is_array($data['receiver'])
                && array_key_exists('@type', $data['receiver'])
                && $data['receiver']['@type'] === 'UnknownEntity'
            ) {
                /** @var non-empty-array<string, mixed> $receiverTyped */
                $receiverTyped = $data['receiver'];
                $value = UnknownEntity::fromArray($receiverTyped);
            } elseif (
                is_array($data['receiver'])
                && array_key_exists('@type', $data['receiver'])
                && $data['receiver']['@type'] === 'Organization'
            ) {
                /** @var non-empty-array<string, mixed> $receiverTyped_1 */
                $receiverTyped_1 = $data['receiver'];
                $value = Organization::fromArray($receiverTyped_1);
            } elseif (
                is_array($data['receiver'])
                && array_key_exists('@type', $data['receiver'])
                && $data['receiver']['@type'] === 'Company'
            ) {
                /** @var non-empty-array<string, mixed> $receiverTyped_2 */
                $receiverTyped_2 = $data['receiver'];
                $value = Company::fromArray($receiverTyped_2);
            } elseif (
                is_array($data['receiver'])
                && array_key_exists('@type', $data['receiver'])
                && $data['receiver']['@type'] === 'Person'
            ) {
                /** @var non-empty-array<string, mixed> $receiverTyped_3 */
                $receiverTyped_3 = $data['receiver'];
                $value = Person::fromArray($receiverTyped_3);
            } else {
                throw new MalformedDataException('Property "receiver" matched none of the expected shapes: UnknownEntity, Organization, Company, Person.');
            }
            $receiver = Some::create($value);
        }
        if (array_key_exists('sender', $data) && $data['sender'] !== null) {
            if (
                is_array($data['sender'])
                && array_key_exists('@type', $data['sender'])
                && $data['sender']['@type'] === 'UnknownEntity'
            ) {
                /** @var non-empty-array<string, mixed> $senderTyped */
                $senderTyped = $data['sender'];
                $value_1 = UnknownEntity::fromArray($senderTyped);
            } elseif (
                is_array($data['sender'])
                && array_key_exists('@type', $data['sender'])
                && $data['sender']['@type'] === 'Organization'
            ) {
                /** @var non-empty-array<string, mixed> $senderTyped_1 */
                $senderTyped_1 = $data['sender'];
                $value_1 = Organization::fromArray($senderTyped_1);
            } elseif (
                is_array($data['sender'])
                && array_key_exists('@type', $data['sender'])
                && $data['sender']['@type'] === 'Company'
            ) {
                /** @var non-empty-array<string, mixed> $senderTyped_2 */
                $senderTyped_2 = $data['sender'];
                $value_1 = Company::fromArray($senderTyped_2);
            } elseif (
                is_array($data['sender'])
                && array_key_exists('@type', $data['sender'])
                && $data['sender']['@type'] === 'Person'
            ) {
                /** @var non-empty-array<string, mixed> $senderTyped_3 */
                $senderTyped_3 = $data['sender'];
                $value_1 = Person::fromArray($senderTyped_3);
            } else {
                throw new MalformedDataException('Property "sender" matched none of the expected shapes: UnknownEntity, Organization, Company, Person.');
            }
            $sender = Some::create($value_1);
        }
        if (array_key_exists('carrier', $data) && $data['carrier'] !== null) {
            if (
                is_array($data['carrier'])
                && array_key_exists('@type', $data['carrier'])
                && $data['carrier']['@type'] === 'UnknownEntity'
            ) {
                /** @var non-empty-array<string, mixed> $carrierTyped */
                $carrierTyped = $data['carrier'];
                $value_2 = UnknownEntity::fromArray($carrierTyped);
            } elseif (
                is_array($data['carrier'])
                && array_key_exists('@type', $data['carrier'])
                && $data['carrier']['@type'] === 'Organization'
            ) {
                /** @var non-empty-array<string, mixed> $carrierTyped_1 */
                $carrierTyped_1 = $data['carrier'];
                $value_2 = Organization::fromArray($carrierTyped_1);
            } elseif (
                is_array($data['carrier'])
                && array_key_exists('@type', $data['carrier'])
                && $data['carrier']['@type'] === 'Company'
            ) {
                /** @var non-empty-array<string, mixed> $carrierTyped_2 */
                $carrierTyped_2 = $data['carrier'];
                $value_2 = Company::fromArray($carrierTyped_2);
            } elseif (
                is_array($data['carrier'])
                && array_key_exists('@type', $data['carrier'])
                && $data['carrier']['@type'] === 'Person'
            ) {
                /** @var non-empty-array<string, mixed> $carrierTyped_3 */
                $carrierTyped_3 = $data['carrier'];
                $value_2 = Person::fromArray($carrierTyped_3);
            } else {
                throw new MalformedDataException('Property "carrier" matched none of the expected shapes: UnknownEntity, Organization, Company, Person.');
            }
            $carrier = Some::create($value_2);
        }
        if (array_key_exists('shipper', $data) && $data['shipper'] !== null) {
            if (
                is_array($data['shipper'])
                && array_key_exists('@type', $data['shipper'])
                && $data['shipper']['@type'] === 'UnknownEntity'
            ) {
                /** @var non-empty-array<string, mixed> $shipperTyped */
                $shipperTyped = $data['shipper'];
                $value_3 = UnknownEntity::fromArray($shipperTyped);
            } elseif (
                is_array($data['shipper'])
                && array_key_exists('@type', $data['shipper'])
                && $data['shipper']['@type'] === 'Organization'
            ) {
                /** @var non-empty-array<string, mixed> $shipperTyped_1 */
                $shipperTyped_1 = $data['shipper'];
                $value_3 = Organization::fromArray($shipperTyped_1);
            } elseif (
                is_array($data['shipper'])
                && array_key_exists('@type', $data['shipper'])
                && $data['shipper']['@type'] === 'Company'
            ) {
                /** @var non-empty-array<string, mixed> $shipperTyped_2 */
                $shipperTyped_2 = $data['shipper'];
                $value_3 = Company::fromArray($shipperTyped_2);
            } elseif (
                is_array($data['shipper'])
                && array_key_exists('@type', $data['shipper'])
                && $data['shipper']['@type'] === 'Person'
            ) {
                /** @var non-empty-array<string, mixed> $shipperTyped_3 */
                $shipperTyped_3 = $data['shipper'];
                $value_3 = Person::fromArray($shipperTyped_3);
            } else {
                throw new MalformedDataException('Property "shipper" matched none of the expected shapes: UnknownEntity, Organization, Company, Person.');
            }
            $shipper = Some::create($value_3);
        }
        if (array_key_exists('consignee', $data) && $data['consignee'] !== null) {
            if (
                is_array($data['consignee'])
                && array_key_exists('@type', $data['consignee'])
                && $data['consignee']['@type'] === 'UnknownEntity'
            ) {
                /** @var non-empty-array<string, mixed> $consigneeTyped */
                $consigneeTyped = $data['consignee'];
                $value_4 = UnknownEntity::fromArray($consigneeTyped);
            } elseif (
                is_array($data['consignee'])
                && array_key_exists('@type', $data['consignee'])
                && $data['consignee']['@type'] === 'Organization'
            ) {
                /** @var non-empty-array<string, mixed> $consigneeTyped_1 */
                $consigneeTyped_1 = $data['consignee'];
                $value_4 = Organization::fromArray($consigneeTyped_1);
            } elseif (
                is_array($data['consignee'])
                && array_key_exists('@type', $data['consignee'])
                && $data['consignee']['@type'] === 'Company'
            ) {
                /** @var non-empty-array<string, mixed> $consigneeTyped_2 */
                $consigneeTyped_2 = $data['consignee'];
                $value_4 = Company::fromArray($consigneeTyped_2);
            } elseif (
                is_array($data['consignee'])
                && array_key_exists('@type', $data['consignee'])
                && $data['consignee']['@type'] === 'Person'
            ) {
                /** @var non-empty-array<string, mixed> $consigneeTyped_3 */
                $consigneeTyped_3 = $data['consignee'];
                $value_4 = Person::fromArray($consigneeTyped_3);
            } else {
                throw new MalformedDataException('Property "consignee" matched none of the expected shapes: UnknownEntity, Organization, Company, Person.');
            }
            $consignee = Some::create($value_4);
        }
        if (array_key_exists('proofOfDelivery', $data) && $data['proofOfDelivery'] !== null) {
            $proofOfDeliveryRaw = $data['proofOfDelivery'];
            if (!is_array($proofOfDeliveryRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "proofOfDelivery" must be object, got %s.', get_debug_type($proofOfDeliveryRaw)),
                );
            }
            /** @var array<string, mixed> $proofOfDeliveryRawTyped */
            $proofOfDeliveryRawTyped = $proofOfDeliveryRaw;
            $proofOfDelivery = Some::create(ProofOfDelivery::fromArray($proofOfDeliveryRawTyped));
        }
        if (
            array_key_exists('proofOfDeliverySignedAvailable', $data)
            && $data['proofOfDeliverySignedAvailable'] !== null
        ) {
            $proofOfDeliverySignedAvailableRaw = $data['proofOfDeliverySignedAvailable'];
            if (!is_bool($proofOfDeliverySignedAvailableRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "proofOfDeliverySignedAvailable" must be bool, got %s.',
                        get_debug_type($proofOfDeliverySignedAvailableRaw),
                    ),
                );
            }
            $proofOfDeliverySignedAvailable = Some::create($proofOfDeliverySignedAvailableRaw);
        }
        if (array_key_exists('totalNumberOfPieces', $data) && $data['totalNumberOfPieces'] !== null) {
            $totalNumberOfPiecesRaw = $data['totalNumberOfPieces'];
            if (!is_int($totalNumberOfPiecesRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "totalNumberOfPieces" must be int, got %s.',
                        get_debug_type($totalNumberOfPiecesRaw),
                    ),
                );
            }
            $totalNumberOfPieces = Some::create($totalNumberOfPiecesRaw);
        }
        if (array_key_exists('pieceIds', $data) && $data['pieceIds'] !== null) {
            $pieceIdsRaw = $data['pieceIds'];
            if (!(is_array($pieceIdsRaw) && array_is_list($pieceIdsRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "pieceIds" must be list, got %s.', get_debug_type($pieceIdsRaw)),
                );
            }
            $pieceIds = Some::create(array_map(static function (mixed $value_5): string {
                if (!is_string($value_5)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be string, got %s.', get_debug_type($value_5)),
                    );
                }

                return $value_5;
            }, $pieceIdsRaw));
        }
        if (array_key_exists('weight', $data) && $data['weight'] !== null) {
            $weightRaw = $data['weight'];
            if (!is_array($weightRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "weight" must be object, got %s.', get_debug_type($weightRaw)),
                );
            }
            /** @var array<string, mixed> $weightRawTyped */
            $weightRawTyped = $weightRaw;
            $weight = Some::create(QuantitativeValue::fromArray($weightRawTyped));
        }
        if (array_key_exists('volume', $data) && $data['volume'] !== null) {
            $volumeRaw = $data['volume'];
            if (!is_array($volumeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "volume" must be object, got %s.', get_debug_type($volumeRaw)),
                );
            }
            /** @var array<string, mixed> $volumeRawTyped */
            $volumeRawTyped = $volumeRaw;
            $volume = Some::create(QuantitativeValue::fromArray($volumeRawTyped));
        }
        if (array_key_exists('loadingMeters', $data) && $data['loadingMeters'] !== null) {
            $loadingMetersRaw = $data['loadingMeters'];
            if (!(is_float($loadingMetersRaw) || is_int($loadingMetersRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "loadingMeters" must be number, got %s.', get_debug_type($loadingMetersRaw)),
                );
            }
            $loadingMeters = Some::create((float) $loadingMetersRaw);
        }
        if (array_key_exists('dimensions', $data) && $data['dimensions'] !== null) {
            $dimensionsRaw = $data['dimensions'];
            if (!is_array($dimensionsRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "dimensions" must be object, got %s.', get_debug_type($dimensionsRaw)),
                );
            }
            /** @var array<string, mixed> $dimensionsRawTyped */
            $dimensionsRawTyped = $dimensionsRaw;
            $dimensions = Some::create(Dimensions::fromArray($dimensionsRawTyped));
        }
        if (array_key_exists('references', $data) && $data['references'] !== null) {
            $referencesRaw = $data['references'];
            if (!(is_array($referencesRaw) && array_is_list($referencesRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "references" must be list, got %s.', get_debug_type($referencesRaw)),
                );
            }
            $references = Some::create(array_map(static function (mixed $value_6): Reference {
                if (!is_array($value_6)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value_6)),
                    );
                }
                /** @var non-empty-array<string, mixed> $value_6Typed */
                $value_6Typed = $value_6;

                return Reference::fromArray($value_6Typed);
            }, $referencesRaw));
        }
        if (array_key_exists('valueAddedServices', $data) && $data['valueAddedServices'] !== null) {
            $valueAddedServicesRaw = $data['valueAddedServices'];
            if (!is_array($valueAddedServicesRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "valueAddedServices" must be object, got %s.',
                        get_debug_type($valueAddedServicesRaw),
                    ),
                );
            }
            /** @var array<string, mixed> $valueAddedServicesRawTyped */
            $valueAddedServicesRawTyped = $valueAddedServicesRaw;
            $valueAddedServices = Some::create(ValueAddedServices::fromArray($valueAddedServicesRawTyped));
        }
        if (array_key_exists('controlledDataCodes', $data) && $data['controlledDataCodes'] !== null) {
            $controlledDataCodesRaw = $data['controlledDataCodes'];
            if (!(is_array($controlledDataCodesRaw) && array_is_list($controlledDataCodesRaw))) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "controlledDataCodes" must be list, got %s.',
                        get_debug_type($controlledDataCodesRaw),
                    ),
                );
            }
            $controlledDataCodes = Some::create(
                array_map(static function (mixed $value_7): ControlledDataCode|UnknownEnumValue {
                    if (!is_string($value_7)) {
                        throw new MalformedDataException(
                            sprintf('Array item must be string, got %s.', get_debug_type($value_7)),
                        );
                    }

                    return ControlledDataCode::tryFrom($value_7) ?? UnknownEnumValue::of($value_7);
                }, $controlledDataCodesRaw),
            );
        }
        if (array_key_exists('shipmentActivationDate', $data) && $data['shipmentActivationDate'] !== null) {
            $shipmentActivationDateRaw = $data['shipmentActivationDate'];
            if (!is_string($shipmentActivationDateRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "shipmentActivationDate" must be string, got %s.',
                        get_debug_type($shipmentActivationDateRaw),
                    ),
                );
            }
            $shipmentActivationDate = Some::create($shipmentActivationDateRaw);
        }
        if (array_key_exists('dgf:routes', $data) && $data['dgf:routes'] !== null) {
            $dgfRoutesRaw = $data['dgf:routes'];
            if (!(is_array($dgfRoutesRaw) && array_is_list($dgfRoutesRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "dgf:routes" must be list, got %s.', get_debug_type($dgfRoutesRaw)),
                );
            }
            $dgfRoutes = Some::create(array_map(static function (mixed $value_8): DgfRoute {
                if (!is_array($value_8)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value_8)),
                    );
                }
                /** @var array<string, mixed> $value_8Typed */
                $value_8Typed = $value_8;

                return DgfRoute::fromArray($value_8Typed);
            }, $dgfRoutesRaw));
        }
        if (array_key_exists('telemetry', $data) && $data['telemetry'] !== null) {
            $telemetryRaw = $data['telemetry'];
            if (!(is_array($telemetryRaw) && array_is_list($telemetryRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "telemetry" must be list, got %s.', get_debug_type($telemetryRaw)),
                );
            }
            $telemetry = Some::create(array_map(static function (mixed $value_9): Measurement {
                if (!is_array($value_9)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value_9)),
                    );
                }
                /** @var array<string, mixed> $value_9Typed */
                $value_9Typed = $value_9;

                return Measurement::fromArray($value_9Typed);
            }, $telemetryRaw));
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'product' => true,
                'provider' => true,
                'receiver' => true,
                'sender' => true,
                'carrier' => true,
                'shipper' => true,
                'consignee' => true,
                'proofOfDelivery' => true,
                'proofOfDeliverySignedAvailable' => true,
                'totalNumberOfPieces' => true,
                'pieceIds' => true,
                'weight' => true,
                'volume' => true,
                'loadingMeters' => true,
                'dimensions' => true,
                'references' => true,
                'valueAddedServices' => true,
                'controlledDataCodes' => true,
                'shipmentActivationDate' => true,
                'dgf:routes' => true,
                'telemetry' => true,
            ],
        );

        return new self(
            $product,
            $provider,
            $receiver,
            $sender,
            $carrier,
            $shipper,
            $consignee,
            $proofOfDelivery,
            $proofOfDeliverySignedAvailable,
            $totalNumberOfPieces,
            $pieceIds,
            $weight,
            $volume,
            $loadingMeters,
            $dimensions,
            $references,
            $valueAddedServices,
            $controlledDataCodes,
            $shipmentActivationDate,
            $dgfRoutes,
            $telemetry,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $productOption = $this->product;
        if ($productOption->isDefined()) {
            $product = $productOption->get();
            $dataArray['product'] = $normalizationTarget->model($product);
        }
        $providerOption = $this->provider;
        if ($providerOption->isDefined()) {
            $provider = $providerOption->get();
            $dataArray['provider'] = $normalizationTarget->model($provider);
        }
        $receiverOption = $this->receiver;
        if ($receiverOption->isDefined()) {
            $receiver = $receiverOption->get();
            $value = $normalizationTarget->model($receiver);
            $dataArray['receiver'] = $value;
        }
        $senderOption = $this->sender;
        if ($senderOption->isDefined()) {
            $sender = $senderOption->get();
            $value_1 = $normalizationTarget->model($sender);
            $dataArray['sender'] = $value_1;
        }
        $carrierOption = $this->carrier;
        if ($carrierOption->isDefined()) {
            $carrier = $carrierOption->get();
            $value_2 = $normalizationTarget->model($carrier);
            $dataArray['carrier'] = $value_2;
        }
        $shipperOption = $this->shipper;
        if ($shipperOption->isDefined()) {
            $shipper = $shipperOption->get();
            $value_3 = $normalizationTarget->model($shipper);
            $dataArray['shipper'] = $value_3;
        }
        $consigneeOption = $this->consignee;
        if ($consigneeOption->isDefined()) {
            $consignee = $consigneeOption->get();
            $value_4 = $normalizationTarget->model($consignee);
            $dataArray['consignee'] = $value_4;
        }
        $proofOfDeliveryOption = $this->proofOfDelivery;
        if ($proofOfDeliveryOption->isDefined()) {
            $proofOfDelivery = $proofOfDeliveryOption->get();
            $dataArray['proofOfDelivery'] = $normalizationTarget->model($proofOfDelivery);
        }
        $proofOfDeliverySignedAvailableOption = $this->proofOfDeliverySignedAvailable;
        if ($proofOfDeliverySignedAvailableOption->isDefined()) {
            $proofOfDeliverySignedAvailable = $proofOfDeliverySignedAvailableOption->get();
            $dataArray['proofOfDeliverySignedAvailable'] = $proofOfDeliverySignedAvailable;
        }
        $totalNumberOfPiecesOption = $this->totalNumberOfPieces;
        if ($totalNumberOfPiecesOption->isDefined()) {
            $totalNumberOfPieces = $totalNumberOfPiecesOption->get();
            $dataArray['totalNumberOfPieces'] = $totalNumberOfPieces;
        }
        $pieceIdsOption = $this->pieceIds;
        if ($pieceIdsOption->isDefined()) {
            $pieceIds = $pieceIdsOption->get();
            $values = [];
            foreach ($pieceIds as $value_5) {
                $values[] = $value_5;
            }
            $dataArray['pieceIds'] = $values;
        }
        $weightOption = $this->weight;
        if ($weightOption->isDefined()) {
            $weight = $weightOption->get();
            $dataArray['weight'] = $normalizationTarget->model($weight);
        }
        $volumeOption = $this->volume;
        if ($volumeOption->isDefined()) {
            $volume = $volumeOption->get();
            $dataArray['volume'] = $normalizationTarget->model($volume);
        }
        $loadingMetersOption = $this->loadingMeters;
        if ($loadingMetersOption->isDefined()) {
            $loadingMeters = $loadingMetersOption->get();
            $dataArray['loadingMeters'] = $loadingMeters;
        }
        $dimensionsOption = $this->dimensions;
        if ($dimensionsOption->isDefined()) {
            $dimensions = $dimensionsOption->get();
            $dataArray['dimensions'] = $normalizationTarget->model($dimensions);
        }
        $referencesOption = $this->references;
        if ($referencesOption->isDefined()) {
            $references = $referencesOption->get();
            $values_1 = [];
            foreach ($references as $value_6) {
                $values_1[] = $normalizationTarget->model($value_6);
            }
            $dataArray['references'] = $values_1;
        }
        $valueAddedServicesOption = $this->valueAddedServices;
        if ($valueAddedServicesOption->isDefined()) {
            $valueAddedServices = $valueAddedServicesOption->get();
            $dataArray['valueAddedServices'] = $normalizationTarget->model($valueAddedServices);
        }
        $controlledDataCodesOption = $this->controlledDataCodes;
        if ($controlledDataCodesOption->isDefined()) {
            $controlledDataCodes = $controlledDataCodesOption->get();
            $values_2 = [];
            foreach ($controlledDataCodes as $value_7) {
                $values_2[] = $value_7->value;
            }
            $dataArray['controlledDataCodes'] = $values_2;
        }
        $shipmentActivationDateOption = $this->shipmentActivationDate;
        if ($shipmentActivationDateOption->isDefined()) {
            $shipmentActivationDate = $shipmentActivationDateOption->get();
            $dataArray['shipmentActivationDate'] = $shipmentActivationDate;
        }
        $dgfRoutesOption = $this->dgfRoutes;
        if ($dgfRoutesOption->isDefined()) {
            $dgfRoutes = $dgfRoutesOption->get();
            $values_3 = [];
            foreach ($dgfRoutes as $value_8) {
                $values_3[] = $normalizationTarget->model($value_8);
            }
            $dataArray['dgf:routes'] = $values_3;
        }
        $telemetryOption = $this->telemetry;
        if ($telemetryOption->isDefined()) {
            $telemetry = $telemetryOption->get();
            $values_4 = [];
            foreach ($telemetry as $value_9) {
                $values_4[] = $normalizationTarget->model($value_9);
            }
            $dataArray['telemetry'] = $values_4;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): TrackingShipmentDetailsBuilder
    {
        return new TrackingShipmentDetailsBuilder(
            $this->product,
            $this->provider,
            $this->receiver,
            $this->sender,
            $this->carrier,
            $this->shipper,
            $this->consignee,
            $this->proofOfDelivery,
            $this->proofOfDeliverySignedAvailable,
            $this->totalNumberOfPieces,
            $this->pieceIds,
            $this->weight,
            $this->volume,
            $this->loadingMeters,
            $this->dimensions,
            $this->references,
            $this->valueAddedServices,
            $this->controlledDataCodes,
            $this->shipmentActivationDate,
            $this->dgfRoutes,
            $this->telemetry,
            $this->additionalProperties,
        );
    }
}
