<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

/**
 * Builds a {@see TrackingShipment}.
 */
final class TrackingShipmentBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<int>                              $ttl
     * @param Option<string>                           $id
     * @param Option<Service|UnknownEnumValue<string>> $service
     * @param Option<string>                           $division
     * @param Option<SecuredPlace>                     $origin
     * @param Option<SecuredPlace>                     $destination
     * @param Option<TrackingShipmentStatus>           $status
     * @param Option<string>                           $pickUpDate
     * @param Option<string>                           $estimatedTimeOfDelivery
     * @param Option<EstimatedDeliveryTimeFrame>       $estimatedDeliveryTimeFrame
     * @param Option<string>                           $estimatedTimeOfDeliveryRemark
     * @param Option<string>                           $serviceUrl
     * @param Option<string>                           $rerouteUrl
     * @param Option<bool>                             $returnFlag
     * @param Option<TrackingShipmentDetails>          $details
     * @param Option<list<TrackingShipmentEvent>>      $events
     * @param array<int|string, mixed>                 $additionalProperties
     */
    public function __construct(
        private Option $ttl,
        private Option $id,
        private Option $service,
        private Option $division,
        private Option $origin,
        private Option $destination,
        private Option $status,
        private Option $pickUpDate,
        private Option $estimatedTimeOfDelivery,
        private Option $estimatedDeliveryTimeFrame,
        private Option $estimatedTimeOfDeliveryRemark,
        private Option $serviceUrl,
        private Option $rerouteUrl,
        private Option $returnFlag,
        private Option $details,
        private Option $events,
        private array $additionalProperties,
    ) {
    }

    /**
     * Define the TTL value in seconds of shipment between 30 and 365 days.
     */
    public function setTtl(int $ttl): self
    {
        $this->ttl = Some::create($ttl);

        return $this;
    }

    /**
     * Shipment identification tracking number.
     */
    public function setId(string $id): self
    {
        $this->id = Some::create($id);

        return $this;
    }

    /**
     * Service (provider) used to resolve this tracking number (id).
     */
    public function setService(Service $service): self
    {
        $this->service = Some::create($service);

        return $this;
    }

    /**
     * The (sub)division of service provider that owns the shipment.
     */
    public function setDivision(string $division): self
    {
        $this->division = Some::create($division);

        return $this;
    }

    /**
     * The location of object.
     */
    public function setOrigin(SecuredPlace $origin): self
    {
        $this->origin = Some::create($origin);

        return $this;
    }

    /**
     * The location of object.
     */
    public function setDestination(SecuredPlace $destination): self
    {
        $this->destination = Some::create($destination);

        return $this;
    }

    /**
     * High-level shipment status.
     */
    public function setStatus(TrackingShipmentStatus $status): self
    {
        $this->status = Some::create($status);

        return $this;
    }

    /**
     * Shipment pickup date.
     */
    public function setPickUpDate(string $pickUpDate): self
    {
        $this->pickUpDate = Some::create($pickUpDate);

        return $this;
    }

    /**
     * Estimated time of delivery.
     */
    public function setEstimatedTimeOfDelivery(string $estimatedTimeOfDelivery): self
    {
        $this->estimatedTimeOfDelivery = Some::create($estimatedTimeOfDelivery);

        return $this;
    }

    /**
     * A term when shipment is expected to arrive.
     */
    public function setEstimatedDeliveryTimeFrame(EstimatedDeliveryTimeFrame $estimatedDeliveryTimeFrame): self
    {
        $this->estimatedDeliveryTimeFrame = Some::create($estimatedDeliveryTimeFrame);

        return $this;
    }

    /**
     * Human-readable description of the estimated delivery time.
     */
    public function setEstimatedTimeOfDeliveryRemark(string $estimatedTimeOfDeliveryRemark): self
    {
        $this->estimatedTimeOfDeliveryRemark = Some::create($estimatedTimeOfDeliveryRemark);

        return $this;
    }

    /**
     * Custom link to BU tracking service.
     */
    public function setServiceUrl(string $serviceUrl): self
    {
        $this->serviceUrl = Some::create($serviceUrl);

        return $this;
    }

    /**
     * Custom link to BU rerouting service, if available for the current status of the shipment.
     */
    public function setRerouteUrl(string $rerouteUrl): self
    {
        $this->rerouteUrl = Some::create($rerouteUrl);

        return $this;
    }

    /**
     * A flag whether the delivery is returned back to consignor.
     */
    public function setReturnFlag(bool $returnFlag): self
    {
        $this->returnFlag = Some::create($returnFlag);

        return $this;
    }

    /**
     * Shipment Details.
     */
    public function setDetails(TrackingShipmentDetails $details): self
    {
        $this->details = Some::create($details);

        return $this;
    }

    /**
     * Historical list of events & timestamps.
     *
     * @param list<TrackingShipmentEvent> $events
     */
    public function setEvents(array $events): self
    {
        $this->events = Some::create($events);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): TrackingShipment
    {
        return new TrackingShipment(
            $this->ttl,
            $this->id,
            $this->service,
            $this->division,
            $this->origin,
            $this->destination,
            $this->status,
            $this->pickUpDate,
            $this->estimatedTimeOfDelivery,
            $this->estimatedDeliveryTimeFrame,
            $this->estimatedTimeOfDeliveryRemark,
            $this->serviceUrl,
            $this->rerouteUrl,
            $this->returnFlag,
            $this->details,
            $this->events,
            $this->additionalProperties,
        );
    }
}
