<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\MalformedDataException;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\None;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function is_bool;
use function is_int;
use function is_string;
use function sprintf;

final readonly class TrackingShipment implements SelfNormalizingModel
{
    /**
     * @param Option<int>                              $ttl
     * @param Option<string>                           $id
     * @param Option<Service|UnknownEnumValue<string>> $service
     * @param Option<string>                           $division
     * @param Option<SecuredPlace>                     $origin
     * @param Option<SecuredPlace>                     $destination
     * @param Option<TrackingShipmentStatus>           $status
     * @param Option<string>                           $pickUpDate
     * @param Option<string>                           $estimatedTimeOfDelivery
     * @param Option<EstimatedDeliveryTimeFrame>       $estimatedDeliveryTimeFrame
     * @param Option<string>                           $estimatedTimeOfDeliveryRemark
     * @param Option<string>                           $serviceUrl
     * @param Option<string>                           $rerouteUrl
     * @param Option<bool>                             $returnFlag
     * @param Option<TrackingShipmentDetails>          $details
     * @param Option<list<TrackingShipmentEvent>>      $events
     * @param array<int|string, mixed>                 $additionalProperties
     */
    public function __construct(
        private Option $ttl,
        private Option $id,
        private Option $service,
        private Option $division,
        private Option $origin,
        private Option $destination,
        private Option $status,
        private Option $pickUpDate,
        private Option $estimatedTimeOfDelivery,
        private Option $estimatedDeliveryTimeFrame,
        private Option $estimatedTimeOfDeliveryRemark,
        private Option $serviceUrl,
        private Option $rerouteUrl,
        private Option $returnFlag,
        private Option $details,
        private Option $events,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): TrackingShipmentBuilder
    {
        return new TrackingShipmentBuilder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * Define the TTL value in seconds of shipment between 30 and 365 days.
     *
     * Default: `15552000`.
     *
     * @return Option<int>
     */
    public function getTtl(): Option
    {
        return $this->ttl;
    }

    /**
     * Shipment identification tracking number.
     *
     * @return Option<string>
     */
    public function getId(): Option
    {
        return $this->id;
    }

    /**
     * Service (provider) used to resolve this tracking number (id).
     *
     * @return Option<Service|UnknownEnumValue<string>>
     */
    public function getService(): Option
    {
        return $this->service;
    }

    /**
     * The (sub)division of service provider that owns the shipment.
     *
     * @return Option<string>
     */
    public function getDivision(): Option
    {
        return $this->division;
    }

    /**
     * The location of object.
     *
     * @return Option<SecuredPlace>
     */
    public function getOrigin(): Option
    {
        return $this->origin;
    }

    /**
     * The location of object.
     *
     * @return Option<SecuredPlace>
     */
    public function getDestination(): Option
    {
        return $this->destination;
    }

    /**
     * High-level shipment status.
     *
     * @return Option<TrackingShipmentStatus>
     */
    public function getStatus(): Option
    {
        return $this->status;
    }

    /**
     * Shipment pickup date.
     *
     * @return Option<string>
     */
    public function getPickUpDate(): Option
    {
        return $this->pickUpDate;
    }

    /**
     * Estimated time of delivery.
     *
     * @return Option<string>
     */
    public function getEstimatedTimeOfDelivery(): Option
    {
        return $this->estimatedTimeOfDelivery;
    }

    /**
     * A term when shipment is expected to arrive.
     *
     * @return Option<EstimatedDeliveryTimeFrame>
     */
    public function getEstimatedDeliveryTimeFrame(): Option
    {
        return $this->estimatedDeliveryTimeFrame;
    }

    /**
     * Human-readable description of the estimated delivery time.
     *
     * @return Option<string>
     */
    public function getEstimatedTimeOfDeliveryRemark(): Option
    {
        return $this->estimatedTimeOfDeliveryRemark;
    }

    /**
     * Custom link to BU tracking service.
     *
     * @return Option<string>
     */
    public function getServiceUrl(): Option
    {
        return $this->serviceUrl;
    }

    /**
     * Custom link to BU rerouting service, if available for the current status of the shipment.
     *
     * @return Option<string>
     */
    public function getRerouteUrl(): Option
    {
        return $this->rerouteUrl;
    }

    /**
     * A flag whether the delivery is returned back to consignor.
     *
     * Default: `false`.
     *
     * @return Option<bool>
     */
    public function getReturnFlag(): Option
    {
        return $this->returnFlag;
    }

    /**
     * Shipment Details.
     *
     * @return Option<TrackingShipmentDetails>
     */
    public function getDetails(): Option
    {
        return $this->details;
    }

    /**
     * Historical list of events & timestamps.
     *
     * @return Option<list<TrackingShipmentEvent>>
     */
    public function getEvents(): Option
    {
        return $this->events;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $ttl = None::create();
        $id = None::create();
        $service = None::create();
        $division = None::create();
        $origin = None::create();
        $destination = None::create();
        $status = None::create();
        $pickUpDate = None::create();
        $estimatedTimeOfDelivery = None::create();
        $estimatedDeliveryTimeFrame = None::create();
        $estimatedTimeOfDeliveryRemark = None::create();
        $serviceUrl = None::create();
        $rerouteUrl = None::create();
        $returnFlag = None::create();
        $details = None::create();
        $events = None::create();
        if (array_key_exists('@ttl', $data) && $data['@ttl'] !== null) {
            $ttlRaw = $data['@ttl'];
            if (!is_int($ttlRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "@ttl" must be int, got %s.', get_debug_type($ttlRaw)),
                );
            }
            $ttl = Some::create($ttlRaw);
        }
        if (array_key_exists('id', $data) && $data['id'] !== null) {
            $idRaw = $data['id'];
            if (!is_string($idRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "id" must be string, got %s.', get_debug_type($idRaw)),
                );
            }
            $id = Some::create($idRaw);
        }
        if (array_key_exists('service', $data) && $data['service'] !== null) {
            $serviceRaw = $data['service'];
            if (!is_string($serviceRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "service" must be string, got %s.', get_debug_type($serviceRaw)),
                );
            }
            $service = Some::create(Service::tryFrom($serviceRaw) ?? UnknownEnumValue::of($serviceRaw));
        }
        if (array_key_exists('division', $data) && $data['division'] !== null) {
            $divisionRaw = $data['division'];
            if (!is_string($divisionRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "division" must be string, got %s.', get_debug_type($divisionRaw)),
                );
            }
            $division = Some::create($divisionRaw);
        }
        if (array_key_exists('origin', $data) && $data['origin'] !== null) {
            $originRaw = $data['origin'];
            if (!is_array($originRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "origin" must be object, got %s.', get_debug_type($originRaw)),
                );
            }
            /** @var array<string, mixed> $originRawTyped */
            $originRawTyped = $originRaw;
            $origin = Some::create(SecuredPlace::fromArray($originRawTyped));
        }
        if (array_key_exists('destination', $data) && $data['destination'] !== null) {
            $destinationRaw = $data['destination'];
            if (!is_array($destinationRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "destination" must be object, got %s.', get_debug_type($destinationRaw)),
                );
            }
            /** @var array<string, mixed> $destinationRawTyped */
            $destinationRawTyped = $destinationRaw;
            $destination = Some::create(SecuredPlace::fromArray($destinationRawTyped));
        }
        if (array_key_exists('status', $data) && $data['status'] !== null) {
            $statusRaw = $data['status'];
            if (!is_array($statusRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "status" must be object, got %s.', get_debug_type($statusRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $statusRawTyped */
            $statusRawTyped = $statusRaw;
            $status = Some::create(TrackingShipmentStatus::fromArray($statusRawTyped));
        }
        if (array_key_exists('pickUpDate', $data) && $data['pickUpDate'] !== null) {
            $pickUpDateRaw = $data['pickUpDate'];
            if (!is_string($pickUpDateRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "pickUpDate" must be string, got %s.', get_debug_type($pickUpDateRaw)),
                );
            }
            $pickUpDate = Some::create($pickUpDateRaw);
        }
        if (array_key_exists('estimatedTimeOfDelivery', $data) && $data['estimatedTimeOfDelivery'] !== null) {
            $estimatedTimeOfDeliveryRaw = $data['estimatedTimeOfDelivery'];
            if (!is_string($estimatedTimeOfDeliveryRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "estimatedTimeOfDelivery" must be string, got %s.',
                        get_debug_type($estimatedTimeOfDeliveryRaw),
                    ),
                );
            }
            $estimatedTimeOfDelivery = Some::create($estimatedTimeOfDeliveryRaw);
        }
        if (array_key_exists('estimatedDeliveryTimeFrame', $data) && $data['estimatedDeliveryTimeFrame'] !== null) {
            $estimatedDeliveryTimeFrameRaw = $data['estimatedDeliveryTimeFrame'];
            if (!is_array($estimatedDeliveryTimeFrameRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "estimatedDeliveryTimeFrame" must be object, got %s.',
                        get_debug_type($estimatedDeliveryTimeFrameRaw),
                    ),
                );
            }
            /** @var array<string, mixed> $estimatedDeliveryTimeFrameRawTyped */
            $estimatedDeliveryTimeFrameRawTyped = $estimatedDeliveryTimeFrameRaw;
            $estimatedDeliveryTimeFrame = Some::create(
                EstimatedDeliveryTimeFrame::fromArray($estimatedDeliveryTimeFrameRawTyped),
            );
        }
        if (
            array_key_exists('estimatedTimeOfDeliveryRemark', $data)
            && $data['estimatedTimeOfDeliveryRemark'] !== null
        ) {
            $estimatedTimeOfDeliveryRemarkRaw = $data['estimatedTimeOfDeliveryRemark'];
            if (!is_string($estimatedTimeOfDeliveryRemarkRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "estimatedTimeOfDeliveryRemark" must be string, got %s.',
                        get_debug_type($estimatedTimeOfDeliveryRemarkRaw),
                    ),
                );
            }
            $estimatedTimeOfDeliveryRemark = Some::create($estimatedTimeOfDeliveryRemarkRaw);
        }
        if (array_key_exists('serviceUrl', $data) && $data['serviceUrl'] !== null) {
            $serviceUrlRaw = $data['serviceUrl'];
            if (!is_string($serviceUrlRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "serviceUrl" must be string, got %s.', get_debug_type($serviceUrlRaw)),
                );
            }
            $serviceUrl = Some::create($serviceUrlRaw);
        }
        if (array_key_exists('rerouteUrl', $data) && $data['rerouteUrl'] !== null) {
            $rerouteUrlRaw = $data['rerouteUrl'];
            if (!is_string($rerouteUrlRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "rerouteUrl" must be string, got %s.', get_debug_type($rerouteUrlRaw)),
                );
            }
            $rerouteUrl = Some::create($rerouteUrlRaw);
        }
        if (array_key_exists('returnFlag', $data) && $data['returnFlag'] !== null) {
            $returnFlagRaw = $data['returnFlag'];
            if (!is_bool($returnFlagRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "returnFlag" must be bool, got %s.', get_debug_type($returnFlagRaw)),
                );
            }
            $returnFlag = Some::create($returnFlagRaw);
        }
        if (array_key_exists('details', $data) && $data['details'] !== null) {
            $detailsRaw = $data['details'];
            if (!is_array($detailsRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "details" must be object, got %s.', get_debug_type($detailsRaw)),
                );
            }
            /** @var array<string, mixed> $detailsRawTyped */
            $detailsRawTyped = $detailsRaw;
            $details = Some::create(TrackingShipmentDetails::fromArray($detailsRawTyped));
        }
        if (array_key_exists('events', $data) && $data['events'] !== null) {
            $eventsRaw = $data['events'];
            if (!(is_array($eventsRaw) && array_is_list($eventsRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "events" must be list, got %s.', get_debug_type($eventsRaw)),
                );
            }
            $events = Some::create(array_map(static function (mixed $value): TrackingShipmentEvent {
                if (!is_array($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value)),
                    );
                }
                /** @var non-empty-array<string, mixed> $valueTyped */
                $valueTyped = $value;

                return TrackingShipmentEvent::fromArray($valueTyped);
            }, $eventsRaw));
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                '@ttl' => true,
                'id' => true,
                'service' => true,
                'division' => true,
                'origin' => true,
                'destination' => true,
                'status' => true,
                'pickUpDate' => true,
                'estimatedTimeOfDelivery' => true,
                'estimatedDeliveryTimeFrame' => true,
                'estimatedTimeOfDeliveryRemark' => true,
                'serviceUrl' => true,
                'rerouteUrl' => true,
                'returnFlag' => true,
                'details' => true,
                'events' => true,
            ],
        );

        return new self(
            $ttl,
            $id,
            $service,
            $division,
            $origin,
            $destination,
            $status,
            $pickUpDate,
            $estimatedTimeOfDelivery,
            $estimatedDeliveryTimeFrame,
            $estimatedTimeOfDeliveryRemark,
            $serviceUrl,
            $rerouteUrl,
            $returnFlag,
            $details,
            $events,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $ttlOption = $this->ttl;
        if ($ttlOption->isDefined()) {
            $ttl = $ttlOption->get();
            $dataArray['@ttl'] = $ttl;
        }
        $idOption = $this->id;
        if ($idOption->isDefined()) {
            $id = $idOption->get();
            $dataArray['id'] = $id;
        }
        $serviceOption = $this->service;
        if ($serviceOption->isDefined()) {
            $service = $serviceOption->get();
            $dataArray['service'] = $service->value;
        }
        $divisionOption = $this->division;
        if ($divisionOption->isDefined()) {
            $division = $divisionOption->get();
            $dataArray['division'] = $division;
        }
        $originOption = $this->origin;
        if ($originOption->isDefined()) {
            $origin = $originOption->get();
            $dataArray['origin'] = $normalizationTarget->model($origin);
        }
        $destinationOption = $this->destination;
        if ($destinationOption->isDefined()) {
            $destination = $destinationOption->get();
            $dataArray['destination'] = $normalizationTarget->model($destination);
        }
        $statusOption = $this->status;
        if ($statusOption->isDefined()) {
            $status = $statusOption->get();
            $dataArray['status'] = $normalizationTarget->model($status);
        }
        $pickUpDateOption = $this->pickUpDate;
        if ($pickUpDateOption->isDefined()) {
            $pickUpDate = $pickUpDateOption->get();
            $dataArray['pickUpDate'] = $pickUpDate;
        }
        $estimatedTimeOfDeliveryOption = $this->estimatedTimeOfDelivery;
        if ($estimatedTimeOfDeliveryOption->isDefined()) {
            $estimatedTimeOfDelivery = $estimatedTimeOfDeliveryOption->get();
            $dataArray['estimatedTimeOfDelivery'] = $estimatedTimeOfDelivery;
        }
        $estimatedDeliveryTimeFrameOption = $this->estimatedDeliveryTimeFrame;
        if ($estimatedDeliveryTimeFrameOption->isDefined()) {
            $estimatedDeliveryTimeFrame = $estimatedDeliveryTimeFrameOption->get();
            $dataArray['estimatedDeliveryTimeFrame'] = $normalizationTarget->model($estimatedDeliveryTimeFrame);
        }
        $estimatedTimeOfDeliveryRemarkOption = $this->estimatedTimeOfDeliveryRemark;
        if ($estimatedTimeOfDeliveryRemarkOption->isDefined()) {
            $estimatedTimeOfDeliveryRemark = $estimatedTimeOfDeliveryRemarkOption->get();
            $dataArray['estimatedTimeOfDeliveryRemark'] = $estimatedTimeOfDeliveryRemark;
        }
        $serviceUrlOption = $this->serviceUrl;
        if ($serviceUrlOption->isDefined()) {
            $serviceUrl = $serviceUrlOption->get();
            $dataArray['serviceUrl'] = $serviceUrl;
        }
        $rerouteUrlOption = $this->rerouteUrl;
        if ($rerouteUrlOption->isDefined()) {
            $rerouteUrl = $rerouteUrlOption->get();
            $dataArray['rerouteUrl'] = $rerouteUrl;
        }
        $returnFlagOption = $this->returnFlag;
        if ($returnFlagOption->isDefined()) {
            $returnFlag = $returnFlagOption->get();
            $dataArray['returnFlag'] = $returnFlag;
        }
        $detailsOption = $this->details;
        if ($detailsOption->isDefined()) {
            $details = $detailsOption->get();
            $dataArray['details'] = $normalizationTarget->model($details);
        }
        $eventsOption = $this->events;
        if ($eventsOption->isDefined()) {
            $events = $eventsOption->get();
            $values = [];
            foreach ($events as $value) {
                $values[] = $normalizationTarget->model($value);
            }
            $dataArray['events'] = $values;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): TrackingShipmentBuilder
    {
        return new TrackingShipmentBuilder(
            $this->ttl,
            $this->id,
            $this->service,
            $this->division,
            $this->origin,
            $this->destination,
            $this->status,
            $this->pickUpDate,
            $this->estimatedTimeOfDelivery,
            $this->estimatedDeliveryTimeFrame,
            $this->estimatedTimeOfDeliveryRemark,
            $this->serviceUrl,
            $this->rerouteUrl,
            $this->returnFlag,
            $this->details,
            $this->events,
            $this->additionalProperties,
        );
    }
}
