<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\MalformedDataException;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\None;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class TrackingShipments implements SelfNormalizingModel
{
    /**
     * @param Option<string>                 $url
     * @param Option<string>                 $prevUrl
     * @param Option<string>                 $nextUrl
     * @param Option<string>                 $firstUrl
     * @param Option<string>                 $lastUrl
     * @param Option<list<TrackingShipment>> $shipments
     * @param Option<list<string>>           $possibleAdditionalShipmentsUrl
     * @param array<int|string, mixed>       $additionalProperties
     */
    public function __construct(
        private Option $url,
        private Option $prevUrl,
        private Option $nextUrl,
        private Option $firstUrl,
        private Option $lastUrl,
        private Option $shipments,
        private Option $possibleAdditionalShipmentsUrl,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): TrackingShipmentsBuilder
    {
        return new TrackingShipmentsBuilder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * A link to current page.
     *
     * @return Option<string>
     */
    public function getUrl(): Option
    {
        return $this->url;
    }

    /**
     * A link to the previous page.
     *
     * @return Option<string>
     */
    public function getPrevUrl(): Option
    {
        return $this->prevUrl;
    }

    /**
     * A link to the next page.
     *
     * @return Option<string>
     */
    public function getNextUrl(): Option
    {
        return $this->nextUrl;
    }

    /**
     * A link to the first page.
     *
     * @return Option<string>
     */
    public function getFirstUrl(): Option
    {
        return $this->firstUrl;
    }

    /**
     * A link to the last page.
     *
     * @return Option<string>
     */
    public function getLastUrl(): Option
    {
        return $this->lastUrl;
    }

    /**
     * An array of unified tracking shipments.
     *
     * @return Option<list<TrackingShipment>>
     */
    public function getShipments(): Option
    {
        return $this->shipments;
    }

    /**
     * An array of business services, where should be potentially shipment found.
     *
     * @return Option<list<string>>
     */
    public function getPossibleAdditionalShipmentsUrl(): Option
    {
        return $this->possibleAdditionalShipmentsUrl;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $url = None::create();
        $prevUrl = None::create();
        $nextUrl = None::create();
        $firstUrl = None::create();
        $lastUrl = None::create();
        $shipments = None::create();
        $possibleAdditionalShipmentsUrl = None::create();
        if (array_key_exists('url', $data) && $data['url'] !== null) {
            $urlRaw = $data['url'];
            if (!is_string($urlRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "url" must be string, got %s.', get_debug_type($urlRaw)),
                );
            }
            $url = Some::create($urlRaw);
        }
        if (array_key_exists('prevUrl', $data) && $data['prevUrl'] !== null) {
            $prevUrlRaw = $data['prevUrl'];
            if (!is_string($prevUrlRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "prevUrl" must be string, got %s.', get_debug_type($prevUrlRaw)),
                );
            }
            $prevUrl = Some::create($prevUrlRaw);
        }
        if (array_key_exists('nextUrl', $data) && $data['nextUrl'] !== null) {
            $nextUrlRaw = $data['nextUrl'];
            if (!is_string($nextUrlRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "nextUrl" must be string, got %s.', get_debug_type($nextUrlRaw)),
                );
            }
            $nextUrl = Some::create($nextUrlRaw);
        }
        if (array_key_exists('firstUrl', $data) && $data['firstUrl'] !== null) {
            $firstUrlRaw = $data['firstUrl'];
            if (!is_string($firstUrlRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "firstUrl" must be string, got %s.', get_debug_type($firstUrlRaw)),
                );
            }
            $firstUrl = Some::create($firstUrlRaw);
        }
        if (array_key_exists('lastUrl', $data) && $data['lastUrl'] !== null) {
            $lastUrlRaw = $data['lastUrl'];
            if (!is_string($lastUrlRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "lastUrl" must be string, got %s.', get_debug_type($lastUrlRaw)),
                );
            }
            $lastUrl = Some::create($lastUrlRaw);
        }
        if (array_key_exists('shipments', $data) && $data['shipments'] !== null) {
            $shipmentsRaw = $data['shipments'];
            if (!(is_array($shipmentsRaw) && array_is_list($shipmentsRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "shipments" must be list, got %s.', get_debug_type($shipmentsRaw)),
                );
            }
            $shipments = Some::create(array_map(static function (mixed $value): TrackingShipment {
                if (!is_array($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value)),
                    );
                }
                /** @var array<string, mixed> $valueTyped */
                $valueTyped = $value;

                return TrackingShipment::fromArray($valueTyped);
            }, $shipmentsRaw));
        }
        if (
            array_key_exists('possibleAdditionalShipmentsUrl', $data)
            && $data['possibleAdditionalShipmentsUrl'] !== null
        ) {
            $possibleAdditionalShipmentsUrlRaw = $data['possibleAdditionalShipmentsUrl'];
            if (!(is_array($possibleAdditionalShipmentsUrlRaw) && array_is_list($possibleAdditionalShipmentsUrlRaw))) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "possibleAdditionalShipmentsUrl" must be list, got %s.',
                        get_debug_type($possibleAdditionalShipmentsUrlRaw),
                    ),
                );
            }
            $possibleAdditionalShipmentsUrl = Some::create(array_map(static function (mixed $value_1): string {
                if (!is_string($value_1)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be string, got %s.', get_debug_type($value_1)),
                    );
                }

                return $value_1;
            }, $possibleAdditionalShipmentsUrlRaw));
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'url' => true,
                'prevUrl' => true,
                'nextUrl' => true,
                'firstUrl' => true,
                'lastUrl' => true,
                'shipments' => true,
                'possibleAdditionalShipmentsUrl' => true,
            ],
        );

        return new self(
            $url,
            $prevUrl,
            $nextUrl,
            $firstUrl,
            $lastUrl,
            $shipments,
            $possibleAdditionalShipmentsUrl,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $urlOption = $this->url;
        if ($urlOption->isDefined()) {
            $url = $urlOption->get();
            $dataArray['url'] = $url;
        }
        $prevUrlOption = $this->prevUrl;
        if ($prevUrlOption->isDefined()) {
            $prevUrl = $prevUrlOption->get();
            $dataArray['prevUrl'] = $prevUrl;
        }
        $nextUrlOption = $this->nextUrl;
        if ($nextUrlOption->isDefined()) {
            $nextUrl = $nextUrlOption->get();
            $dataArray['nextUrl'] = $nextUrl;
        }
        $firstUrlOption = $this->firstUrl;
        if ($firstUrlOption->isDefined()) {
            $firstUrl = $firstUrlOption->get();
            $dataArray['firstUrl'] = $firstUrl;
        }
        $lastUrlOption = $this->lastUrl;
        if ($lastUrlOption->isDefined()) {
            $lastUrl = $lastUrlOption->get();
            $dataArray['lastUrl'] = $lastUrl;
        }
        $shipmentsOption = $this->shipments;
        if ($shipmentsOption->isDefined()) {
            $shipments = $shipmentsOption->get();
            $values = [];
            foreach ($shipments as $value) {
                $values[] = $normalizationTarget->model($value);
            }
            $dataArray['shipments'] = $values;
        }
        $possibleAdditionalShipmentsUrlOption = $this->possibleAdditionalShipmentsUrl;
        if ($possibleAdditionalShipmentsUrlOption->isDefined()) {
            $possibleAdditionalShipmentsUrl = $possibleAdditionalShipmentsUrlOption->get();
            $values_1 = [];
            foreach ($possibleAdditionalShipmentsUrl as $value_1) {
                $values_1[] = $value_1;
            }
            $dataArray['possibleAdditionalShipmentsUrl'] = $values_1;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): TrackingShipmentsBuilder
    {
        return new TrackingShipmentsBuilder(
            $this->url,
            $this->prevUrl,
            $this->nextUrl,
            $this->firstUrl,
            $this->lastUrl,
            $this->shipments,
            $this->possibleAdditionalShipmentsUrl,
            $this->additionalProperties,
        );
    }
}
