<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

/**
 * Builds a {@see TrackingShipmentDetails}.
 */
final class TrackingShipmentDetailsBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<Product>                                           $product
     * @param Option<Provider>                                          $provider
     * @param Option<UnknownEntity|Organization|Company|Person>         $receiver
     * @param Option<UnknownEntity|Organization|Company|Person>         $sender
     * @param Option<UnknownEntity|Organization|Company|Person>         $carrier
     * @param Option<UnknownEntity|Organization|Company|Person>         $shipper
     * @param Option<UnknownEntity|Organization|Company|Person>         $consignee
     * @param Option<ProofOfDelivery>                                   $proofOfDelivery
     * @param Option<bool>                                              $proofOfDeliverySignedAvailable
     * @param Option<int>                                               $totalNumberOfPieces
     * @param Option<list<string>>                                      $pieceIds
     * @param Option<QuantitativeValue>                                 $weight
     * @param Option<QuantitativeValue>                                 $volume
     * @param Option<float>                                             $loadingMeters
     * @param Option<Dimensions>                                        $dimensions
     * @param Option<list<Reference>>                                   $references
     * @param Option<ValueAddedServices>                                $valueAddedServices
     * @param Option<list<ControlledDataCode|UnknownEnumValue<string>>> $controlledDataCodes
     * @param Option<string>                                            $shipmentActivationDate
     * @param Option<list<DgfRoute>>                                    $dgfRoutes
     * @param Option<list<Measurement>>                                 $telemetry
     * @param array<int|string, mixed>                                  $additionalProperties
     */
    public function __construct(
        private Option $product,
        private Option $provider,
        private Option $receiver,
        private Option $sender,
        private Option $carrier,
        private Option $shipper,
        private Option $consignee,
        private Option $proofOfDelivery,
        private Option $proofOfDeliverySignedAvailable,
        private Option $totalNumberOfPieces,
        private Option $pieceIds,
        private Option $weight,
        private Option $volume,
        private Option $loadingMeters,
        private Option $dimensions,
        private Option $references,
        private Option $valueAddedServices,
        private Option $controlledDataCodes,
        private Option $shipmentActivationDate,
        private Option $dgfRoutes,
        private Option $telemetry,
        private array $additionalProperties,
    ) {
    }

    /**
     * Offered product or service.
     */
    public function setProduct(Product $product): self
    {
        $this->product = Some::create($product);

        return $this;
    }

    /**
     * The service provider, service operator, or service performer.
     */
    public function setProvider(Provider $provider): self
    {
        $this->provider = Some::create($provider);

        return $this;
    }

    /**
     * A real organization or personal entity, if type is not specified, a Organization
     * implementation is used.
     */
    public function setReceiver(UnknownEntity|Organization|Company|Person $receiver): self
    {
        $this->receiver = Some::create($receiver);

        return $this;
    }

    /**
     * A real organization or personal entity, if type is not specified, a Organization
     * implementation is used.
     */
    public function setSender(UnknownEntity|Organization|Company|Person $sender): self
    {
        $this->sender = Some::create($sender);

        return $this;
    }

    /**
     * A real organization or personal entity, if type is not specified, a Organization
     * implementation is used.
     */
    public function setCarrier(UnknownEntity|Organization|Company|Person $carrier): self
    {
        $this->carrier = Some::create($carrier);

        return $this;
    }

    /**
     * A real organization or personal entity, if type is not specified, a Organization
     * implementation is used.
     */
    public function setShipper(UnknownEntity|Organization|Company|Person $shipper): self
    {
        $this->shipper = Some::create($shipper);

        return $this;
    }

    /**
     * A real organization or personal entity, if type is not specified, a Organization
     * implementation is used.
     */
    public function setConsignee(UnknownEntity|Organization|Company|Person $consignee): self
    {
        $this->consignee = Some::create($consignee);

        return $this;
    }

    /**
     * An acknowledgment that an order successfully arrived at its intended destination.
     */
    public function setProofOfDelivery(ProofOfDelivery $proofOfDelivery): self
    {
        $this->proofOfDelivery = Some::create($proofOfDelivery);

        return $this;
    }

    /**
     * \'Yes\' if signer identification is available.
     */
    public function setProofOfDeliverySignedAvailable(bool $proofOfDeliverySignedAvailable): self
    {
        $this->proofOfDeliverySignedAvailable = Some::create($proofOfDeliverySignedAvailable);

        return $this;
    }

    /**
     * Total number of items or pieces in the shipment.
     */
    public function setTotalNumberOfPieces(int $totalNumberOfPieces): self
    {
        $this->totalNumberOfPieces = Some::create($totalNumberOfPieces);

        return $this;
    }

    /**
     * Ids of all the items or pieces in the shipment.
     *
     * @param list<string> $pieceIds
     */
    public function setPieceIds(array $pieceIds): self
    {
        $this->pieceIds = Some::create($pieceIds);

        return $this;
    }

    /**
     * A point value or interval for product characteristics and other purposes.
     */
    public function setWeight(QuantitativeValue $weight): self
    {
        $this->weight = Some::create($weight);

        return $this;
    }

    /**
     * A point value or interval for product characteristics and other purposes.
     */
    public function setVolume(QuantitativeValue $volume): self
    {
        $this->volume = Some::create($volume);

        return $this;
    }

    /**
     * A loading meter standard unit of measurement for transport by truck.
     */
    public function setLoadingMeters(float $loadingMeters): self
    {
        $this->loadingMeters = Some::create($loadingMeters);

        return $this;
    }

    /**
     * A measurable extent of a particular kind of delivery.
     */
    public function setDimensions(Dimensions $dimensions): self
    {
        $this->dimensions = Some::create($dimensions);

        return $this;
    }

    /**
     * A list of indications that refers to related shipment.
     *
     * @param list<Reference> $references
     */
    public function setReferences(array $references): self
    {
        $this->references = Some::create($references);

        return $this;
    }

    /**
     * Services I booked together with my Tracking details.
     */
    public function setValueAddedServices(ValueAddedServices $valueAddedServices): self
    {
        $this->valueAddedServices = Some::create($valueAddedServices);

        return $this;
    }

    /**
     * Extra Controlled Access Data Codes.
     *
     * @param list<ControlledDataCode> $controlledDataCodes
     */
    public function setControlledDataCodes(array $controlledDataCodes): self
    {
        $this->controlledDataCodes = Some::create($controlledDataCodes);

        return $this;
    }

    /**
     * Shipment Activation date.
     */
    public function setShipmentActivationDate(string $shipmentActivationDate): self
    {
        $this->shipmentActivationDate = Some::create($shipmentActivationDate);

        return $this;
    }

    /**
     * DHL Global Forwarding routing Details.
     *
     * @param list<DgfRoute> $dgfRoutes
     */
    public function setDgfRoutes(array $dgfRoutes): self
    {
        $this->dgfRoutes = Some::create($dgfRoutes);

        return $this;
    }

    /**
     * list of all sensor measurements from devices.
     *
     * @param list<Measurement> $telemetry
     */
    public function setTelemetry(array $telemetry): self
    {
        $this->telemetry = Some::create($telemetry);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): TrackingShipmentDetails
    {
        return new TrackingShipmentDetails(
            $this->product,
            $this->provider,
            $this->receiver,
            $this->sender,
            $this->carrier,
            $this->shipper,
            $this->consignee,
            $this->proofOfDelivery,
            $this->proofOfDeliverySignedAvailable,
            $this->totalNumberOfPieces,
            $this->pieceIds,
            $this->weight,
            $this->volume,
            $this->loadingMeters,
            $this->dimensions,
            $this->references,
            $this->valueAddedServices,
            $this->controlledDataCodes,
            $this->shipmentActivationDate,
            $this->dgfRoutes,
            $this->telemetry,
            $this->additionalProperties,
        );
    }
}
