<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

/**
 * Builds a {@see TrackingShipments}.
 */
final class TrackingShipmentsBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>                 $url
     * @param Option<string>                 $prevUrl
     * @param Option<string>                 $nextUrl
     * @param Option<string>                 $firstUrl
     * @param Option<string>                 $lastUrl
     * @param Option<list<TrackingShipment>> $shipments
     * @param Option<list<string>>           $possibleAdditionalShipmentsUrl
     * @param array<int|string, mixed>       $additionalProperties
     */
    public function __construct(
        private Option $url,
        private Option $prevUrl,
        private Option $nextUrl,
        private Option $firstUrl,
        private Option $lastUrl,
        private Option $shipments,
        private Option $possibleAdditionalShipmentsUrl,
        private array $additionalProperties,
    ) {
    }

    /**
     * A link to current page.
     */
    public function setUrl(string $url): self
    {
        $this->url = Some::create($url);

        return $this;
    }

    /**
     * A link to the previous page.
     */
    public function setPrevUrl(string $prevUrl): self
    {
        $this->prevUrl = Some::create($prevUrl);

        return $this;
    }

    /**
     * A link to the next page.
     */
    public function setNextUrl(string $nextUrl): self
    {
        $this->nextUrl = Some::create($nextUrl);

        return $this;
    }

    /**
     * A link to the first page.
     */
    public function setFirstUrl(string $firstUrl): self
    {
        $this->firstUrl = Some::create($firstUrl);

        return $this;
    }

    /**
     * A link to the last page.
     */
    public function setLastUrl(string $lastUrl): self
    {
        $this->lastUrl = Some::create($lastUrl);

        return $this;
    }

    /**
     * An array of unified tracking shipments.
     *
     * @param list<TrackingShipment> $shipments
     */
    public function setShipments(array $shipments): self
    {
        $this->shipments = Some::create($shipments);

        return $this;
    }

    /**
     * An array of business services, where should be potentially shipment found.
     *
     * @param list<string> $possibleAdditionalShipmentsUrl
     */
    public function setPossibleAdditionalShipmentsUrl(array $possibleAdditionalShipmentsUrl): self
    {
        $this->possibleAdditionalShipmentsUrl = Some::create($possibleAdditionalShipmentsUrl);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): TrackingShipments
    {
        return new TrackingShipments(
            $this->url,
            $this->prevUrl,
            $this->nextUrl,
            $this->firstUrl,
            $this->lastUrl,
            $this->shipments,
            $this->possibleAdditionalShipmentsUrl,
            $this->additionalProperties,
        );
    }
}
