<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\MalformedDataException;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\None;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class UnknownEntity implements SelfNormalizingModel
{
    /**
     * @param Option<SecretPolicy|UnknownEnumValue<string>|null> $policy
     * @param Option<string>                                     $familyName
     * @param Option<string>                                     $givenName
     * @param Option<string>                                     $name
     * @param Option<string>                                     $organizationName
     * @param Option<SecuredAddress>                             $address
     * @param array<int|string, mixed>                           $additionalProperties
     */
    public function __construct(
        private string $type,
        private Option $policy,
        private Option $familyName,
        private Option $givenName,
        private Option $name,
        private Option $organizationName,
        private Option $address,
        private array $additionalProperties,
    ) {
    }

    public static function builder(string $type): UnknownEntityBuilder
    {
        return new UnknownEntityBuilder(
            $type,
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * Default: `"UnknownEntity"`.
     */
    public function getType(): string
    {
        return $this->type;
    }

    /** @return Option<SecretPolicy|UnknownEnumValue<string>|null> */
    public function getPolicy(): Option
    {
        return $this->policy;
    }

    /** @return Option<string> */
    public function getFamilyName(): Option
    {
        return $this->familyName;
    }

    /** @return Option<string> */
    public function getGivenName(): Option
    {
        return $this->givenName;
    }

    /** @return Option<string> */
    public function getName(): Option
    {
        return $this->name;
    }

    /** @return Option<string> */
    public function getOrganizationName(): Option
    {
        return $this->organizationName;
    }

    /**
     * The mailing address secured by policy.
     *
     * @return Option<SecuredAddress>
     */
    public function getAddress(): Option
    {
        return $this->address;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $type = null;
        $policy = None::create();
        $familyName = None::create();
        $givenName = None::create();
        $name = None::create();
        $organizationName = None::create();
        $address = None::create();
        if (array_key_exists('@type', $data)) {
            $typeRaw = $data['@type'];
            if (!is_string($typeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "@type" must be string, got %s.', get_debug_type($typeRaw)),
                );
            }
            $type = $typeRaw;
        }
        if (array_key_exists('@policy', $data) && $data['@policy'] !== null) {
            $policyRaw = $data['@policy'];
            if (!is_string($policyRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "@policy" must be string, got %s.', get_debug_type($policyRaw)),
                );
            }
            $policy = Some::create(SecretPolicy::tryFrom($policyRaw) ?? UnknownEnumValue::of($policyRaw));
        } elseif (array_key_exists('@policy', $data)) {
            $policy = Some::create(null);
        }
        if (array_key_exists('familyName', $data) && $data['familyName'] !== null) {
            $familyNameRaw = $data['familyName'];
            if (!is_string($familyNameRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "familyName" must be string, got %s.', get_debug_type($familyNameRaw)),
                );
            }
            $familyName = Some::create($familyNameRaw);
        }
        if (array_key_exists('givenName', $data) && $data['givenName'] !== null) {
            $givenNameRaw = $data['givenName'];
            if (!is_string($givenNameRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "givenName" must be string, got %s.', get_debug_type($givenNameRaw)),
                );
            }
            $givenName = Some::create($givenNameRaw);
        }
        if (array_key_exists('name', $data) && $data['name'] !== null) {
            $nameRaw = $data['name'];
            if (!is_string($nameRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "name" must be string, got %s.', get_debug_type($nameRaw)),
                );
            }
            $name = Some::create($nameRaw);
        }
        if (array_key_exists('organizationName', $data) && $data['organizationName'] !== null) {
            $organizationNameRaw = $data['organizationName'];
            if (!is_string($organizationNameRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "organizationName" must be string, got %s.',
                        get_debug_type($organizationNameRaw),
                    ),
                );
            }
            $organizationName = Some::create($organizationNameRaw);
        }
        if (array_key_exists('address', $data) && $data['address'] !== null) {
            $addressRaw = $data['address'];
            if (!is_array($addressRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "address" must be object, got %s.', get_debug_type($addressRaw)),
                );
            }
            /** @var array<string, mixed> $addressRawTyped */
            $addressRawTyped = $addressRaw;
            $address = Some::create(SecuredAddress::fromArray($addressRawTyped));
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                '@type' => true,
                '@policy' => true,
                'familyName' => true,
                'givenName' => true,
                'name' => true,
                'organizationName' => true,
                'address' => true,
            ],
        );
        if ($type === null) {
            throw new MalformedDataException('Required property "@type" is missing from the document.');
        }

        return new self(
            $type,
            $policy,
            $familyName,
            $givenName,
            $name,
            $organizationName,
            $address,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['@type'] = $this->type;
        $policyOption = $this->policy;
        if ($policyOption->isDefined()) {
            $policy = $policyOption->get();
            if ($policy !== null) {
                $dataArray['@policy'] = $policy->value;
            } else {
                $dataArray['@policy'] = null;
            }
        }
        $familyNameOption = $this->familyName;
        if ($familyNameOption->isDefined()) {
            $familyName = $familyNameOption->get();
            $dataArray['familyName'] = $familyName;
        }
        $givenNameOption = $this->givenName;
        if ($givenNameOption->isDefined()) {
            $givenName = $givenNameOption->get();
            $dataArray['givenName'] = $givenName;
        }
        $nameOption = $this->name;
        if ($nameOption->isDefined()) {
            $name = $nameOption->get();
            $dataArray['name'] = $name;
        }
        $organizationNameOption = $this->organizationName;
        if ($organizationNameOption->isDefined()) {
            $organizationName = $organizationNameOption->get();
            $dataArray['organizationName'] = $organizationName;
        }
        $addressOption = $this->address;
        if ($addressOption->isDefined()) {
            $address = $addressOption->get();
            $dataArray['address'] = $normalizationTarget->model($address);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): UnknownEntityBuilder
    {
        return new UnknownEntityBuilder(
            $this->type,
            $this->policy,
            $this->familyName,
            $this->givenName,
            $this->name,
            $this->organizationName,
            $this->address,
            $this->additionalProperties,
        );
    }
}
