<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\MalformedDataException;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\None;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function sprintf;

final readonly class ValueAddedServices implements SelfNormalizingModel
{
    /**
     * @param Option<list<ValueAddedService>> $services
     * @param array<int|string, mixed>        $additionalProperties
     */
    public function __construct(private Option $services, private array $additionalProperties)
    {
    }

    public static function builder(): ValueAddedServicesBuilder
    {
        return new ValueAddedServicesBuilder(None::create(), []);
    }

    /**
     * List of customer services.
     *
     * @return Option<list<ValueAddedService>>
     */
    public function getServices(): Option
    {
        return $this->services;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $services = None::create();
        if (array_key_exists('services', $data) && $data['services'] !== null) {
            $servicesRaw = $data['services'];
            if (!(is_array($servicesRaw) && array_is_list($servicesRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "services" must be list, got %s.', get_debug_type($servicesRaw)),
                );
            }
            $services = Some::create(array_map(static function (mixed $value): ValueAddedService {
                if (!is_array($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value)),
                    );
                }
                /** @var array<string, mixed> $valueTyped */
                $valueTyped = $value;

                return ValueAddedService::fromArray($valueTyped);
            }, $servicesRaw));
        }
        $additionalProperties = array_diff_key($data, ['services' => true]);

        return new self($services, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $servicesOption = $this->services;
        if ($servicesOption->isDefined()) {
            $services = $servicesOption->get();
            $values = [];
            foreach ($services as $value) {
                $values[] = $normalizationTarget->model($value);
            }
            $dataArray['services'] = $values;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): ValueAddedServicesBuilder
    {
        return new ValueAddedServicesBuilder($this->services, $this->additionalProperties);
    }
}
