<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\MalformedDataException;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\None;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_bool;
use function is_string;
use function sprintf;

final readonly class ValueAddedService implements SelfNormalizingModel
{
    /**
     * @param Option<ValueAddedServiceServiceType|UnknownEnumValue<string>> $serviceType
     * @param Option<string>                                                $serviceCriteria
     * @param Option<bool>                                                  $serviceFlag
     * @param array<int|string, mixed>                                      $additionalProperties
     */
    public function __construct(
        private Option $serviceType,
        private Option $serviceCriteria,
        private Option $serviceFlag,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): ValueAddedServiceBuilder
    {
        return new ValueAddedServiceBuilder(None::create(), None::create(), None::create(), []);
    }

    /** @return Option<ValueAddedServiceServiceType|UnknownEnumValue<string>> */
    public function getServiceType(): Option
    {
        return $this->serviceType;
    }

    /** @return Option<string> */
    public function getServiceCriteria(): Option
    {
        return $this->serviceCriteria;
    }

    /** @return Option<bool> */
    public function getServiceFlag(): Option
    {
        return $this->serviceFlag;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $serviceType = None::create();
        $serviceCriteria = None::create();
        $serviceFlag = None::create();
        if (array_key_exists('serviceType', $data) && $data['serviceType'] !== null) {
            $serviceTypeRaw = $data['serviceType'];
            if (!is_string($serviceTypeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "serviceType" must be string, got %s.', get_debug_type($serviceTypeRaw)),
                );
            }
            $serviceType = Some::create(
                ValueAddedServiceServiceType::tryFrom($serviceTypeRaw) ?? UnknownEnumValue::of($serviceTypeRaw),
            );
        }
        if (array_key_exists('serviceCriteria', $data) && $data['serviceCriteria'] !== null) {
            $serviceCriteriaRaw = $data['serviceCriteria'];
            if (!is_string($serviceCriteriaRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "serviceCriteria" must be string, got %s.', get_debug_type($serviceCriteriaRaw)),
                );
            }
            $serviceCriteria = Some::create($serviceCriteriaRaw);
        }
        if (array_key_exists('serviceFlag', $data) && $data['serviceFlag'] !== null) {
            $serviceFlagRaw = $data['serviceFlag'];
            if (!is_bool($serviceFlagRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "serviceFlag" must be bool, got %s.', get_debug_type($serviceFlagRaw)),
                );
            }
            $serviceFlag = Some::create($serviceFlagRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            ['serviceType' => true, 'serviceCriteria' => true, 'serviceFlag' => true],
        );

        return new self($serviceType, $serviceCriteria, $serviceFlag, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $serviceTypeOption = $this->serviceType;
        if ($serviceTypeOption->isDefined()) {
            $serviceType = $serviceTypeOption->get();
            $dataArray['serviceType'] = $serviceType->value;
        }
        $serviceCriteriaOption = $this->serviceCriteria;
        if ($serviceCriteriaOption->isDefined()) {
            $serviceCriteria = $serviceCriteriaOption->get();
            $dataArray['serviceCriteria'] = $serviceCriteria;
        }
        $serviceFlagOption = $this->serviceFlag;
        if ($serviceFlagOption->isDefined()) {
            $serviceFlag = $serviceFlagOption->get();
            $dataArray['serviceFlag'] = $serviceFlag;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): ValueAddedServiceBuilder
    {
        return new ValueAddedServiceBuilder(
            $this->serviceType,
            $this->serviceCriteria,
            $this->serviceFlag,
            $this->additionalProperties,
        );
    }
}
