<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

enum ValueAddedServiceServiceType: string
{
    case bulky = 'bulky';
    case pickup = 'pickup';
    case gogreen = 'gogreen';
    case priority = 'priority';
    case extraInsurance = 'extraInsurance';
    case directInjection = 'directInjection';
    case cashOnDelivery = 'cashOnDelivery';
    case importFees = 'importFees';
}
