<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

/**
 * Builds a {@see ValueAddedService}.
 */
final class ValueAddedServiceBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<ValueAddedServiceServiceType|UnknownEnumValue<string>> $serviceType
     * @param Option<string>                                                $serviceCriteria
     * @param Option<bool>                                                  $serviceFlag
     * @param array<int|string, mixed>                                      $additionalProperties
     */
    public function __construct(
        private Option $serviceType,
        private Option $serviceCriteria,
        private Option $serviceFlag,
        private array $additionalProperties,
    ) {
    }

    public function setServiceType(ValueAddedServiceServiceType $serviceType): self
    {
        $this->serviceType = Some::create($serviceType);

        return $this;
    }

    public function setServiceCriteria(string $serviceCriteria): self
    {
        $this->serviceCriteria = Some::create($serviceCriteria);

        return $this;
    }

    public function setServiceFlag(bool $serviceFlag): self
    {
        $this->serviceFlag = Some::create($serviceFlag);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ValueAddedService
    {
        return new ValueAddedService(
            $this->serviceType,
            $this->serviceCriteria,
            $this->serviceFlag,
            $this->additionalProperties,
        );
    }
}
