<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Model;

use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

/**
 * Builds a {@see ValueAddedServices}.
 */
final class ValueAddedServicesBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<list<ValueAddedService>> $services
     * @param array<int|string, mixed>        $additionalProperties
     */
    public function __construct(private Option $services, private array $additionalProperties)
    {
    }

    /**
     * List of customer services.
     *
     * @param list<ValueAddedService> $services
     */
    public function setServices(array $services): self
    {
        $this->services = Some::create($services);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ValueAddedServices
    {
        return new ValueAddedServices($this->services, $this->additionalProperties);
    }
}
