<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Operation;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\GetTrackingShipmentNotFoundException;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\MalformedDataException;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\MalformedResponseException;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\ResponseValidationException;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\UnexpectedContentTypeException;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\UnexpectedStatusCodeException;
use Prefabcortex\DhlUnifiedShipmentTracking\Http\BaseOperationTrait;
use Prefabcortex\DhlUnifiedShipmentTracking\Http\ContentType;
use Prefabcortex\DhlUnifiedShipmentTracking\Http\JsonBody;
use Prefabcortex\DhlUnifiedShipmentTracking\Http\Operation;
use Prefabcortex\DhlUnifiedShipmentTracking\Http\OperationTrait;
use Prefabcortex\DhlUnifiedShipmentTracking\Http\Payload;
use Prefabcortex\DhlUnifiedShipmentTracking\Http\QueryParameters;
use Prefabcortex\DhlUnifiedShipmentTracking\Http\ResponseValidation;
use Prefabcortex\DhlUnifiedShipmentTracking\Model\ProblemDetail;
use Prefabcortex\DhlUnifiedShipmentTracking\Model\TrackingShipments;
use Prefabcortex\DhlUnifiedShipmentTracking\Parameter\GetTrackingShipmentQueryParameters;
use Prefabcortex\DhlUnifiedShipmentTracking\Validation\ValidationException;
use Prefabcortex\DhlUnifiedShipmentTracking\Validation\ValidatorTrait;
use Prefabcortex\DhlUnifiedShipmentTracking\Validator\ProblemDetailConstraint;
use Prefabcortex\DhlUnifiedShipmentTracking\Validator\TrackingShipmentsConstraint;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\StreamFactoryInterface;

use function in_array;

/**
 * @internal plumbing of the generated package, not part of its public contract: only the
 *                    generated operations and client touch this, and it may change in any release
 *
 * @implements Operation<TrackingShipments>
 */
final class GetTrackingShipment implements Operation
{
    use BaseOperationTrait;
    use OperationTrait;
    use ValidatorTrait;
    private readonly GetTrackingShipmentQueryParameters $queryParameters;

    /**
     * Retrieves the tracking information for shipments(s). The shipments are identified using the
     * required `trackingNumber` query parameter.
     */
    public function __construct(GetTrackingShipmentQueryParameters $queryParameters)
    {
        $this->queryParameters = $queryParameters;
    }

    #[Override]
    public function getMethod(): string
    {
        return 'GET';
    }

    #[Override]
    public function getUri(): string
    {
        return '/shipments';
    }

    #[Override]
    public function getPayload(StreamFactoryInterface $streamFactory): Payload
    {
        return new Payload([], '');
    }

    /** @return array<string, list<string>> */
    public function getExtraHeaders(): array
    {
        return ['Accept' => ['application/json', 'application/problem+json']];
    }

    protected function getQueryParameters(): QueryParameters
    {
        return $this->queryParameters->toQueryParameters();
    }

    /**
     * {@inheritdoc}.
     *
     * @throws ValidationException
     * @throws MalformedDataException
     * @throws GetTrackingShipmentNotFoundException
     * @throws UnexpectedContentTypeException
     * @throws UnexpectedStatusCodeException
     */
    #[Override]
    protected function transformResponseBody(
        ResponseInterface $response,
        ContentType $contentType,
        string $body,
        ResponseValidation $responseValidation,
    ): TrackingShipments {
        $status = $response->getStatusCode();
        if (200 === $status && $contentType->is('application/json')) {
            $typedData = JsonBody::toArray($body);
            if (ResponseValidation::Strict === $responseValidation) {
                $this->validate($typedData, TrackingShipmentsConstraint::constraints());
            }

            return TrackingShipments::fromArray($typedData);
        }
        if (404 === $status && $contentType->is('application/problem+json')) {
            $typedData = JsonBody::toArray($body);
            if (ResponseValidation::Strict === $responseValidation) {
                $this->validate($typedData, ProblemDetailConstraint::constraints());
            }
            throw new GetTrackingShipmentNotFoundException(ProblemDetail::fromArray($typedData), $response, $body);
        }
        if (in_array($status, [200, 404], true)) {
            throw new UnexpectedContentTypeException($response, $body);
        }
        throw UnexpectedStatusCodeException::of($response, $body);
    }

    /**
     * @throws ResponseValidationException
     * @throws MalformedResponseException
     * @throws GetTrackingShipmentNotFoundException
     * @throws UnexpectedContentTypeException
     * @throws UnexpectedStatusCodeException
     */
    #[Override]
    public function parseResponse(
        ResponseInterface $response,
        ResponseValidation $responseValidation,
    ): TrackingShipments {
        $contentType = ContentType::fromHeader($response->getHeader('Content-Type')[0] ?? '');
        $body = self::readBody($response);
        try {
            return $this->transformResponseBody($response, $contentType, $body, $responseValidation);
        } catch (ValidationException $exception) {
            if ($response->getStatusCode() >= 400) {
                throw UnexpectedStatusCodeException::ofUnreadableBody($response, $body, $exception);
            }
            throw new ResponseValidationException($exception, $response, $body);
        } catch (MalformedDataException $exception) {
            if ($response->getStatusCode() >= 400) {
                throw UnexpectedStatusCodeException::ofUnreadableBody($response, $body, $exception);
            }
            throw new MalformedResponseException($exception, $response, $body);
        }
    }

    /** @return list<list<string>> */
    #[Override]
    public function getSecurityRequirements(): array
    {
        return [['DHL-API-Key']];
    }
}
