<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Http;

/**
 * How closely a response is held to the API description before it is read into a model.
 *
 * The description says what the API *should* send; the API is the one that actually sends it, and
 * the two drift apart — a `detail` one character past its `maxLength`, a `pattern` the server never
 * enforced. `Strict` holds every response to every constraint the description declares, so that
 * drift surfaces the first time it happens instead of somewhere downstream. `Lax` is the way to
 * keep using an API that does not keep to its own description until its provider fixes it.
 *
 * Neither setting touches requests: what this package sends is checked in full before it leaves,
 * whichever is chosen. And neither can switch off what a typed model needs to exist at all — a
 * property of the declared type, a required property present, an enum value it has a case for.
 *
 * The two differ only in a package generated with validation. Without it there are no constraints
 * to hold a response to, and both read it the same way.
 */
enum ResponseValidation
{
    /**
     * Every constraint the description declares for a response is checked before the response is
     * read. A response that breaks one raises `ResponseValidationException`.
     */
    case Strict;
    /**
     * The constraints are skipped: a response is read as far as its model can hold it. Lengths,
     * patterns, ranges and formats reject nothing, and `null` in an optional property reads as
     * absent.
     */
    case Lax;
}
