<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Exception;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Http\ErrorMessage;
use Prefabcortex\DhlUnifiedShipmentTracking\Model\ProblemDetail;
use Psr\Http\Message\ResponseInterface;

final class GetTrackingShipmentNotFoundException extends NotFoundException
{
    public function __construct(
        private readonly ProblemDetail $problemDetail,
        private readonly ResponseInterface $response,
        private readonly string $rawResponse,
    ) {
        parent::__construct(ErrorMessage::describe($rawResponse, 'Shipment was not found'));
    }

    public function getProblemDetail(): ProblemDetail
    {
        return $this->problemDetail;
    }

    #[Override]
    public function getResponse(): ResponseInterface
    {
        return $this->response;
    }

    #[Override]
    public function getRawResponse(): string
    {
        return $this->rawResponse;
    }
}
