<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Parameter;

use Prefabcortex\DhlUnifiedShipmentTracking\Http\QueryParameter;
use Prefabcortex\DhlUnifiedShipmentTracking\Http\QueryParameters;
use Prefabcortex\DhlUnifiedShipmentTracking\Http\ScalarValue;
use Prefabcortex\DhlUnifiedShipmentTracking\Model\Service;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\None;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;

final class GetTrackingShipmentQueryParameters
{
    /**
     * Hint which service (provider) should be used to resolve the tracking number.
     *
     * @var Option<Service>
     */
    private Option $service;
    /**
     * Optional [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country code
     * represents country of the consumer of the API response. It optimizes the return of the API
     * response.
     *
     * @var Option<string>
     */
    private Option $requesterCountryCode;
    /**
     * Optional [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country code
     * of the shipment origin to further qualify the shipment tracking number (`trackingNumber`)
     * parameter of the request.
     *
     * @var Option<string>
     */
    private Option $originCountryCode;
    /**
     * Postal code of the destination address to
     * * further qualify the shipment tracking number (trackingNumber) parameter of the request or
     * * parcel-nl and parcel-de services to display full set of data in the response.
     *
     * @var Option<string>
     */
    private Option $recipientPostalCode;
    /**
     * ISO 639-1 2-character language code for the response. This parameter serves as an indication
     * of the client preferences ONLY. Language availability depends on the service used. The actual
     * response language is indicated by the Content-Language header.
     *
     * @var Option<string>
     */
    private Option $language;
    /**
     * Pagination parameter. Offset from the start of the result set at which to retrieve the
     * remainder of the results (if any).
     *
     * @var Option<float>
     */
    private Option $offset;
    /**
     * Pagination parameter. Maximal number of results to retireve.
     *
     * @var Option<float>
     */
    private Option $limit;

    /**
     * @param string $trackingNumber the tracking number of the shipment for which to return the
     *                               information
     */
    public function __construct(private readonly string $trackingNumber)
    {
        $this->service = None::create();
        $this->requesterCountryCode = None::create();
        $this->originCountryCode = None::create();
        $this->recipientPostalCode = None::create();
        $this->language = None::create();
        $this->offset = None::create();
        $this->limit = None::create();
    }

    public function getTrackingNumber(): string
    {
        return $this->trackingNumber;
    }

    /** @return Option<Service> */
    public function getService(): Option
    {
        return $this->service;
    }

    public function withService(Service $service): self
    {
        $copy = clone $this;
        $copy->service = Some::create($service);

        return $copy;
    }

    /** @return Option<string> */
    public function getRequesterCountryCode(): Option
    {
        return $this->requesterCountryCode;
    }

    public function withRequesterCountryCode(string $requesterCountryCode): self
    {
        $copy = clone $this;
        $copy->requesterCountryCode = Some::create($requesterCountryCode);

        return $copy;
    }

    /** @return Option<string> */
    public function getOriginCountryCode(): Option
    {
        return $this->originCountryCode;
    }

    public function withOriginCountryCode(string $originCountryCode): self
    {
        $copy = clone $this;
        $copy->originCountryCode = Some::create($originCountryCode);

        return $copy;
    }

    /** @return Option<string> */
    public function getRecipientPostalCode(): Option
    {
        return $this->recipientPostalCode;
    }

    public function withRecipientPostalCode(string $recipientPostalCode): self
    {
        $copy = clone $this;
        $copy->recipientPostalCode = Some::create($recipientPostalCode);

        return $copy;
    }

    public function getLanguage(): string
    {
        return $this->language->getOrElse('en');
    }

    public function withLanguage(string $language): self
    {
        $copy = clone $this;
        $copy->language = Some::create($language);

        return $copy;
    }

    public function getOffset(): float
    {
        return $this->offset->getOrElse(0.0);
    }

    public function withOffset(float $offset): self
    {
        $copy = clone $this;
        $copy->offset = Some::create($offset);

        return $copy;
    }

    public function getLimit(): float
    {
        return $this->limit->getOrElse(5.0);
    }

    public function withLimit(float $limit): self
    {
        $copy = clone $this;
        $copy->limit = Some::create($limit);

        return $copy;
    }

    /**
     * @internal called by the generated operation, not part of this package's public
     *                  contract: it may change in any release
     */
    public function toQueryParameters(): QueryParameters
    {
        $parameters = [];
        $parameters[] = new QueryParameter('trackingNumber', new ScalarValue($this->trackingNumber), false);
        if ($this->service->isDefined()) {
            $parameters[] = new QueryParameter('service', new ScalarValue($this->service->get()->value), false);
        }
        if ($this->requesterCountryCode->isDefined()) {
            $parameters[] = new QueryParameter(
                'requesterCountryCode',
                new ScalarValue($this->requesterCountryCode->get()),
                false,
            );
        }
        if ($this->originCountryCode->isDefined()) {
            $parameters[] = new QueryParameter(
                'originCountryCode',
                new ScalarValue($this->originCountryCode->get()),
                false,
            );
        }
        if ($this->recipientPostalCode->isDefined()) {
            $parameters[] = new QueryParameter(
                'recipientPostalCode',
                new ScalarValue($this->recipientPostalCode->get()),
                false,
            );
        }
        if ($this->language->isDefined()) {
            $parameters[] = new QueryParameter('language', new ScalarValue($this->language->get()), false);
        }
        if ($this->offset->isDefined()) {
            $parameters[] = new QueryParameter('offset', new ScalarValue($this->offset->get()), false);
        }
        if ($this->limit->isDefined()) {
            $parameters[] = new QueryParameter('limit', new ScalarValue($this->limit->get()), false);
        }

        return new QueryParameters(...$parameters);
    }
}
