<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking;

use Nyholm\Psr7\Factory\Psr17Factory;
use Prefabcortex\DhlUnifiedShipmentTracking\Authentication\Authenticator;
use Prefabcortex\DhlUnifiedShipmentTracking\Authentication\AuthenticatorRegistry;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\ApiException;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\GetTrackingShipmentNotFoundException;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\MalformedResponseException;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\NoHttpClientException;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\ResponseValidationException;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\TransportException;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\UnexpectedContentTypeException;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\UnexpectedStatusCodeException;
use Prefabcortex\DhlUnifiedShipmentTracking\Exception\UnsupportedValueException;
use Prefabcortex\DhlUnifiedShipmentTracking\Http\ClientTrait;
use Prefabcortex\DhlUnifiedShipmentTracking\Http\HttpClientResolver;
use Prefabcortex\DhlUnifiedShipmentTracking\Model\TrackingShipments;
use Prefabcortex\DhlUnifiedShipmentTracking\Operation\GetTrackingShipment;
use Prefabcortex\DhlUnifiedShipmentTracking\Parameter\GetTrackingShipmentQueryParameters;
use Psr\Http\Message\ResponseInterface;
use SensitiveParameter;

use function array_values;

final class Client
{
    use ClientTrait;

    /**
     * Retrieves the tracking information for shipments(s). The shipments are identified using the
     * required `trackingNumber` query parameter.
     *
     * @throws ApiException
     * @throws UnsupportedValueException
     * @throws TransportException
     * @throws ResponseValidationException
     * @throws MalformedResponseException
     * @throws GetTrackingShipmentNotFoundException
     * @throws UnexpectedContentTypeException
     * @throws UnexpectedStatusCodeException
     */
    public function getTrackingShipment(GetTrackingShipmentQueryParameters $queryParameters): TrackingShipments
    {
        return $this->executeOperation(new GetTrackingShipment($queryParameters));
    }

    /**
     * Retrieves the tracking information for shipments(s). The shipments are identified using the
     * required `trackingNumber` query parameter.
     *
     * @throws ApiException
     * @throws UnsupportedValueException
     * @throws TransportException
     */
    public function getTrackingShipmentRaw(GetTrackingShipmentQueryParameters $queryParameters): ResponseInterface
    {
        return $this->executeRawOperation(new GetTrackingShipment($queryParameters));
    }

    /**
     * @throws UnsupportedValueException
     * @throws NoHttpClientException
     */
    public static function withDHLAPIKey(#[SensitiveParameter] string $apiKey, ClientConfig $config): self
    {
        return self::withAuthenticators($config, new Authentication\DHLAPIKeyAuthentication($apiKey));
    }

    /**
     * A client signing with authenticators you assemble yourself.
     *
     * Every other factory on this class is a shorthand for this one. Reach for it directly for a
     * scheme this package generates no authenticator for: implement `Authentication\Authenticator`
     * under the scheme's name and pass it. A request is signed by the authenticators for the
     * schemes its operation requires; one for a scheme no operation requires is refused. To sign
     * every request your own way, pass an HTTP client that does so to
     * `ClientConfig::withHttpClient()`.
     *
     * Note the argument order: `$config` comes first, because the authenticators are variadic and
     * have to come last.
     *
     * @throws UnsupportedValueException
     * @throws NoHttpClientException
     */
    public static function withAuthenticators(ClientConfig $config, Authenticator ...$authenticators): self
    {
        $factory = new Psr17Factory();
        $httpClient = $config->httpClient->isDefined() ? $config->httpClient->get() : HttpClientResolver::resolve(
            $factory,
            $factory,
            $config->timeout,
        );

        return new self(
            $config->servers,
            $httpClient,
            $factory,
            $factory,
            new AuthenticatorRegistry(array_values($authenticators), ['DHL-API-Key']),
            $config->responseValidation,
        );
    }

    /**
     * A client that signs nothing.
     *
     * For operations the description leaves without a security requirement, and for callers whose
     * own HTTP client already authenticates — see `ClientConfig::withHttpClient()`. A request whose
     * requirements no registered authenticator satisfies goes out unsigned, which is the point here
     * and a mistake anywhere else: to send credentials, use one of the `with…()` factories above,
     * or `withAuthenticators()` for a scheme they do not cover.
     *
     * @throws UnsupportedValueException
     * @throws NoHttpClientException
     */
    public static function create(ClientConfig $config): self
    {
        return self::withAuthenticators($config);
    }
}
