<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking;

use Prefabcortex\DhlUnifiedShipmentTracking\Exception\UnsupportedValueException;
use Prefabcortex\DhlUnifiedShipmentTracking\Http\ResponseValidation;
use Prefabcortex\DhlUnifiedShipmentTracking\Http\ServerSelection;
use Prefabcortex\DhlUnifiedShipmentTracking\Http\ServerUrl;
use Prefabcortex\DhlUnifiedShipmentTracking\Http\Timeout;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\None;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Option;
use Prefabcortex\DhlUnifiedShipmentTracking\Optional\Some;
use Psr\Http\Client\ClientInterface;

final readonly class ClientConfig
{
    /**
     * Which server each operation goes to.
     *
     * @internal plumbing of the generated package, not part of its public contract: only the
     *                    generated operations and client touch this, and it may change in any release
     */
    public ServerSelection $servers;
    /** @var Option<ClientInterface> */
    public Option $httpClient;
    public Timeout $timeout;
    public ResponseValidation $responseValidation;

    /** @param Option<ClientInterface> $httpClient */
    private function __construct(
        ServerSelection $servers,
        Option $httpClient,
        Timeout $timeout,
        ResponseValidation $responseValidation,
    ) {
        $this->servers = $servers;
        $this->httpClient = $httpClient;
        $this->timeout = $timeout;
        $this->responseValidation = $responseValidation;
    }

    /**
     * A configuration for one of the servers the API description names.
     *
     * Each is named after what the description says of it, and their order means nothing: pick the
     * one your credentials belong to.
     */
    public static function forServer(Server $server): self
    {
        return new self(self::selection($server), None::create(), Timeout::defaults(), ResponseValidation::Strict);
    }

    /**
     * Every request to one address — a mock server, a proxy, a recorded fixture — including the
     * operations the description sends to servers of their own. Scheme and host included:
     * `https://api.example.com/v2`; each operation's path is appended to it.
     */
    public static function forBaseUrl(string $baseUrl): self
    {
        return new self(
            ServerSelection::everywhere($baseUrl),
            None::create(),
            Timeout::defaults(),
            ResponseValidation::Strict,
        );
    }

    public function withHttpClient(ClientInterface $httpClient): self
    {
        return new self($this->servers, Some::create($httpClient), $this->timeout, $this->responseValidation);
    }

    /**
     * How long a request may take: `Timeout::seconds(30)`, or `Timeout::of($connect, $total)`.
     *
     * The default is ten seconds to connect and sixty in all. It applies to the HTTP client this
     * package finds by itself; one handed over through `withHttpClient()` keeps its own.
     */
    public function withTimeout(Timeout $timeout): self
    {
        return new self($this->servers, $this->httpClient, $timeout, $this->responseValidation);
    }

    /**
     * How closely responses are held to the API description. `Strict` is the default.
     *
     * Strict checks every response against every constraint the description declares, so a response
     * the API should not have sent fails loudly, as `ResponseValidationException`. If the API does
     * not keep to its own description — a text longer than its declared maximum, a `null` where a
     * value was promised — `Lax` reads such responses anyway, until its provider fixes them, and
     * reads an enum value no case names as `UnknownEnumValue`. What a typed model needs in order to
     * exist (the type of a property, a required property) is still checked either way.
     *
     * Requests are always checked in full before they are sent.
     */
    public function withResponseValidation(ResponseValidation $responseValidation): self
    {
        return new self($this->servers, $this->httpClient, $this->timeout, $responseValidation);
    }

    /**
     * A URL the description gives relative to its server — an OAuth token endpoint — resolved
     * against the chosen server as RFC 3986 resolves a reference: `/oauth/token` keeps only its
     * scheme and host.
     *
     * @throws UnsupportedValueException when the chosen server cannot address one
     */
    public function resolveUrl(string $reference): string
    {
        return $this->servers->resolve(ServerSelection::ROOT, $reference);
    }

    private static function selection(Server $server): ServerSelection
    {
        return ServerSelection::serving(self::serverUrl($server));
    }

    private static function serverUrl(Server $server): ServerUrl
    {
        return match ($server) {
            Server::TestServer => ServerUrl::of('https://api-test.dhl.com/track'),
            Server::ProductionServer => ServerUrl::of('https://api-eu.dhl.com/track'),
        };
    }
}
