<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking;

/**
 * The servers the API description names, for `ClientConfig::forServer()`.
 *
 * Each is named after what the description says of it, and their order means nothing: pick the one
 * your credentials belong to.
 */
enum Server
{
    /**
     * Test server.
     *
     * `https://api-test.dhl.com/track`
     */
    case TestServer;
    /**
     * Production server.
     *
     * `https://api-eu.dhl.com/track`
     */
    case ProductionServer;
}
