<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Validator;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Model\DgfRoute;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see DgfRoute} has to satisfy.
 */
final class DgfRouteConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'dgf:vesselName' => new Optional([new Type(['string']), new NotNull()]),
                'dgf:voyageFlightNumber' => new Optional([new Type(['string']), new NotNull()]),
                'dgf:airportOfDeparture' => new Optional([new NotNull(), ...DgfAirportConstraint::constraints()]),
                'dgf:airportOfDestination' => new Optional([new NotNull(), ...DgfAirportConstraint::constraints()]),
                'dgf:estimatedDepartureDate' => new Optional([new Type(['string']), new NotNull()]),
                'dgf:estimatedArrivalDate' => new Optional([new Type(['string']), new NotNull()]),
                'dgf:placeOfAcceptance' => new Optional([new NotNull(), ...DgfLocationConstraint::constraints()]),
                'dgf:portOfLoading' => new Optional([new NotNull(), ...DgfLocationConstraint::constraints()]),
                'dgf:portOfUnloading' => new Optional([new NotNull(), ...DgfLocationConstraint::constraints()]),
                'dgf:placeOfDelivery' => new Optional([new NotNull(), ...DgfLocationConstraint::constraints()]),
            ], null, null, true),
        ];
    }
}
