<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Validator;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Model\Dimensions;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;

/**
 * The rules a document for {@see Dimensions} has to satisfy.
 */
final class DimensionsConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'height' => new Optional([new NotNull(), ...QuantitativeValueConstraint::constraints()]),
                'length' => new Optional([new NotNull(), ...QuantitativeValueConstraint::constraints()]),
                'width' => new Optional([new NotNull(), ...QuantitativeValueConstraint::constraints()]),
            ], null, null, true),
        ];
    }
}
