<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Validator;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Model\Measurement;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see Measurement} has to satisfy.
 */
final class MeasurementConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                '@policy' => new Optional([...SecretPolicyConstraint::constraints()]),
                'timestamp' => new Optional([new Type(['string']), new NotNull()]),
                'deviceId' => new Optional([new Type(['string']), new NotNull()]),
                'pieceIds' => new Optional([new All([new Type(['string'])]), new Type(['array']), new NotNull()]),
                'location' => new Optional([new NotNull(), ...LocationConstraint::constraints()]),
                'humidity' => new Optional([new NotNull(), ...HumidityConstraint::constraints()]),
                'pressure' => new Optional([new NotNull(), ...PressureConstraint::constraints()]),
                'temperature' => new Optional([new NotNull(), ...TemperatureConstraint::constraints()]),
                'tilt' => new Optional([new NotNull(), ...TiltConstraint::constraints()]),
            ], null, null, true),
        ];
    }
}
