<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Validator;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Model\Organization;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Required;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see Organization} has to satisfy.
 */
final class OrganizationConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                '@type' => new Required([new Type(['string']), new NotNull()]),
                '@policy' => new Optional([...SecretPolicyConstraint::constraints()]),
                'name' => new Optional([new Type(['string']), new NotNull()]),
                'organizationName' => new Optional([new Type(['string']), new NotNull()]),
                'address' => new Optional([new NotNull(), ...SecuredAddressConstraint::constraints()]),
            ], null, null, true),
        ];
    }
}
