<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Validator;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Model\ProblemDetail;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see ProblemDetail} has to satisfy.
 */
final class ProblemDetailConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'detail' => new Optional([new Type(['string']), new NotNull()]),
                'instance' => new Optional([new Type(['string']), new NotNull()]),
                'status' => new Optional([new Type(['number']), new NotNull()]),
                'title' => new Optional([new Type(['string']), new NotNull()]),
                'type' => new Optional([new Type(['string']), new NotNull()]),
            ], null, null, true),
        ];
    }
}
