<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Validator;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Model\ProofOfDelivery;
use Symfony\Component\Validator\Constraints\Callback;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

use function array_key_exists;
use function is_array;

/**
 * The rules a document for {@see ProofOfDelivery} has to satisfy.
 */
final class ProofOfDeliveryConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'documentUrl' => new Optional([new Type(['string']), new NotNull()]),
                'signatureUrl' => new Optional([new Type(['string']), new NotNull()]),
                'signed' => new Optional([
                    new NotNull(),
                    new Callback(static function (mixed $value, ExecutionContextInterface $context): void {
                        if (null === $value) {
                            return;
                        }
                        if (
                            is_array($value)
                            && array_key_exists('@type', $value)
                            && $value['@type'] === 'UnknownEntity'
                        ) {
                            $context->getValidator()->inContext($context)->validate(
                                $value,
                                UnknownEntityConstraint::constraints(),
                            );

                            return;
                        }
                        if (
                            is_array($value)
                            && array_key_exists('@type', $value)
                            && $value['@type'] === 'Organization'
                        ) {
                            $context->getValidator()->inContext($context)->validate(
                                $value,
                                OrganizationConstraint::constraints(),
                            );

                            return;
                        }
                        if (is_array($value) && array_key_exists('@type', $value) && $value['@type'] === 'Company') {
                            $context->getValidator()->inContext($context)->validate(
                                $value,
                                CompanyConstraint::constraints(),
                            );

                            return;
                        }
                        if (is_array($value) && array_key_exists('@type', $value) && $value['@type'] === 'Person') {
                            $context->getValidator()->inContext($context)->validate(
                                $value,
                                PersonConstraint::constraints(),
                            );

                            return;
                        }
                        $context->buildViolation('This value matched none of the expected shapes: UnknownEntity, Organization, Company, Person.')->addViolation();
                    }),
                ]),
                'timestamp' => new Optional([new Type(['string']), new NotNull()]),
            ], null, null, true),
        ];
    }
}
