<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Validator;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Model\Provider;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Required;

/**
 * The rules a document for {@see Provider} has to satisfy.
 */
final class ProviderConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'destinationProvider' => new Required([...ProviderDestinationProviderConstraint::constraints()]),
            ], null, null, true),
        ];
    }
}
