<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Validator;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Model\SecuredPlace;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;

/**
 * The rules a document for {@see SecuredPlace} has to satisfy.
 */
final class SecuredPlaceConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'address' => new Optional([new NotNull(), ...SecuredAddressConstraint::constraints()]),
                'servicePoint' => new Optional([new NotNull(), ...ServicePointConstraint::constraints()]),
            ], null, null, true),
        ];
    }
}
