<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Validator;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Model\SecuredAddress;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see SecuredAddress} has to satisfy.
 */
final class SecuredAddressConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                '@policy' => new Optional([...SecretPolicyConstraint::constraints()]),
                'addressLocality' => new Optional([new Type(['string']), new NotNull()]),
                'addressLocalityServicing' => new Optional([new Type(['string']), new NotNull()]),
                'addressRegion' => new Optional([new Type(['string']), new NotNull()]),
                'countryCode' => new Optional([new Type(['string']), new NotNull()]),
                'postalCode' => new Optional([new Type(['string']), new NotNull()]),
                'streetAddress' => new Optional([new Type(['string']), new NotNull()]),
                'addressLine' => new Optional([new Type(['string']), new NotNull()]),
            ], null, null, true),
        ];
    }
}
