<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Validator;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Model\TrackingShipmentEvent;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Required;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see TrackingShipmentEvent} has to satisfy.
 */
final class TrackingShipmentEventConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'timestamp' => new Required([new Type(['string']), new NotNull()]),
                'location' => new Optional([new NotNull(), ...SecuredPlaceConstraint::constraints()]),
                'statusCode' => new Required([...StatusCodeConstraint::constraints()]),
                'status' => new Optional([new Type(['string']), new NotNull()]),
                'statusDetailed' => new Optional([new Type(['string']), new NotNull()]),
                'description' => new Optional([new Type(['string']), new NotNull()]),
                'remark' => new Optional([new Type(['string']), new NotNull()]),
                'nextSteps' => new Optional([new Type(['string']), new NotNull()]),
                'pieceIds' => new Optional([new All([new Type(['string'])]), new Type(['array']), new NotNull()]),
            ], null, null, true),
        ];
    }
}
