<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Validator;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Model\TrackingShipments;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see TrackingShipments} has to satisfy.
 */
final class TrackingShipmentsConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'url' => new Optional([new Type(['string']), new NotNull()]),
                'prevUrl' => new Optional([new Type(['string']), new NotNull()]),
                'nextUrl' => new Optional([new Type(['string']), new NotNull()]),
                'firstUrl' => new Optional([new Type(['string']), new NotNull()]),
                'lastUrl' => new Optional([new Type(['string']), new NotNull()]),
                'shipments' => new Optional([
                    new All([...TrackingShipmentConstraint::constraints()]),
                    new Type(['array']),
                    new NotNull(),
                ]),
                'possibleAdditionalShipmentsUrl' => new Optional([
                    new All([new Type(['string'])]),
                    new Type(['array']),
                    new NotNull(),
                ]),
            ], null, null, true),
        ];
    }
}
