<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Validator;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Model\TrackingShipment;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\GreaterThanOrEqual;
use Symfony\Component\Validator\Constraints\LessThanOrEqual;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see TrackingShipment} has to satisfy.
 */
final class TrackingShipmentConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                '@ttl' => new Optional([
                    new LessThanOrEqual(31536000.0),
                    new GreaterThanOrEqual(2592000.0),
                    new Type(['integer']),
                    new NotNull(),
                ]),
                'id' => new Optional([new Type(['string']), new NotNull()]),
                'service' => new Optional([...ServiceConstraint::constraints()]),
                'division' => new Optional([new Type(['string']), new NotNull()]),
                'origin' => new Optional([new NotNull(), ...SecuredPlaceConstraint::constraints()]),
                'destination' => new Optional([new NotNull(), ...SecuredPlaceConstraint::constraints()]),
                'status' => new Optional([new NotNull(), ...TrackingShipmentStatusConstraint::constraints()]),
                'pickUpDate' => new Optional([new Type(['string']), new NotNull()]),
                'estimatedTimeOfDelivery' => new Optional([new Type(['string']), new NotNull()]),
                'estimatedDeliveryTimeFrame' => new Optional([
                    new NotNull(),
                    ...EstimatedDeliveryTimeFrameConstraint::constraints(),
                ]),
                'estimatedTimeOfDeliveryRemark' => new Optional([new Type(['string']), new NotNull()]),
                'serviceUrl' => new Optional([new Type(['string']), new NotNull()]),
                'rerouteUrl' => new Optional([new Type(['string']), new NotNull()]),
                'returnFlag' => new Optional([new Type(['bool']), new NotNull()]),
                'details' => new Optional([new NotNull(), ...TrackingShipmentDetailsConstraint::constraints()]),
                'events' => new Optional([
                    new All([...TrackingShipmentEventConstraint::constraints()]),
                    new Type(['array']),
                    new NotNull(),
                ]),
            ], null, null, true),
        ];
    }
}
