<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Validator;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Model\TrackingShipmentDetails;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Callback;
use Symfony\Component\Validator\Constraints\Choice;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

use function array_key_exists;
use function is_array;

/**
 * The rules a document for {@see TrackingShipmentDetails} has to satisfy.
 */
final class TrackingShipmentDetailsConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'product' => new Optional([new NotNull(), ...ProductConstraint::constraints()]),
                'provider' => new Optional([new NotNull(), ...ProviderConstraint::constraints()]),
                'receiver' => new Optional([
                    new NotNull(),
                    new Callback(static function (mixed $value, ExecutionContextInterface $context): void {
                        if (null === $value) {
                            return;
                        }
                        if (
                            is_array($value)
                            && array_key_exists('@type', $value)
                            && $value['@type'] === 'UnknownEntity'
                        ) {
                            $context->getValidator()->inContext($context)->validate(
                                $value,
                                UnknownEntityConstraint::constraints(),
                            );

                            return;
                        }
                        if (
                            is_array($value)
                            && array_key_exists('@type', $value)
                            && $value['@type'] === 'Organization'
                        ) {
                            $context->getValidator()->inContext($context)->validate(
                                $value,
                                OrganizationConstraint::constraints(),
                            );

                            return;
                        }
                        if (is_array($value) && array_key_exists('@type', $value) && $value['@type'] === 'Company') {
                            $context->getValidator()->inContext($context)->validate(
                                $value,
                                CompanyConstraint::constraints(),
                            );

                            return;
                        }
                        if (is_array($value) && array_key_exists('@type', $value) && $value['@type'] === 'Person') {
                            $context->getValidator()->inContext($context)->validate(
                                $value,
                                PersonConstraint::constraints(),
                            );

                            return;
                        }
                        $context->buildViolation('This value matched none of the expected shapes: UnknownEntity, Organization, Company, Person.')->addViolation();
                    }),
                ]),
                'sender' => new Optional([new NotNull(), new Callback(static function (mixed $value, ExecutionContextInterface $context): void {
                    if (null === $value) {
                        return;
                    }
                    if (is_array($value) && array_key_exists('@type', $value) && $value['@type'] === 'UnknownEntity') {
                        $context->getValidator()->inContext($context)->validate(
                            $value,
                            UnknownEntityConstraint::constraints(),
                        );

                        return;
                    }
                    if (is_array($value) && array_key_exists('@type', $value) && $value['@type'] === 'Organization') {
                        $context->getValidator()->inContext($context)->validate(
                            $value,
                            OrganizationConstraint::constraints(),
                        );

                        return;
                    }
                    if (is_array($value) && array_key_exists('@type', $value) && $value['@type'] === 'Company') {
                        $context->getValidator()->inContext($context)->validate(
                            $value,
                            CompanyConstraint::constraints(),
                        );

                        return;
                    }
                    if (is_array($value) && array_key_exists('@type', $value) && $value['@type'] === 'Person') {
                        $context->getValidator()->inContext($context)->validate(
                            $value,
                            PersonConstraint::constraints(),
                        );

                        return;
                    }
                    $context->buildViolation('This value matched none of the expected shapes: UnknownEntity, Organization, Company, Person.')->addViolation();
                })]),
                'carrier' => new Optional([new NotNull(), new Callback(static function (mixed $value, ExecutionContextInterface $context): void {
                    if (null === $value) {
                        return;
                    }
                    if (is_array($value) && array_key_exists('@type', $value) && $value['@type'] === 'UnknownEntity') {
                        $context->getValidator()->inContext($context)->validate(
                            $value,
                            UnknownEntityConstraint::constraints(),
                        );

                        return;
                    }
                    if (is_array($value) && array_key_exists('@type', $value) && $value['@type'] === 'Organization') {
                        $context->getValidator()->inContext($context)->validate(
                            $value,
                            OrganizationConstraint::constraints(),
                        );

                        return;
                    }
                    if (is_array($value) && array_key_exists('@type', $value) && $value['@type'] === 'Company') {
                        $context->getValidator()->inContext($context)->validate(
                            $value,
                            CompanyConstraint::constraints(),
                        );

                        return;
                    }
                    if (is_array($value) && array_key_exists('@type', $value) && $value['@type'] === 'Person') {
                        $context->getValidator()->inContext($context)->validate(
                            $value,
                            PersonConstraint::constraints(),
                        );

                        return;
                    }
                    $context->buildViolation('This value matched none of the expected shapes: UnknownEntity, Organization, Company, Person.')->addViolation();
                })]),
                'shipper' => new Optional([new NotNull(), new Callback(static function (mixed $value, ExecutionContextInterface $context): void {
                    if (null === $value) {
                        return;
                    }
                    if (is_array($value) && array_key_exists('@type', $value) && $value['@type'] === 'UnknownEntity') {
                        $context->getValidator()->inContext($context)->validate(
                            $value,
                            UnknownEntityConstraint::constraints(),
                        );

                        return;
                    }
                    if (is_array($value) && array_key_exists('@type', $value) && $value['@type'] === 'Organization') {
                        $context->getValidator()->inContext($context)->validate(
                            $value,
                            OrganizationConstraint::constraints(),
                        );

                        return;
                    }
                    if (is_array($value) && array_key_exists('@type', $value) && $value['@type'] === 'Company') {
                        $context->getValidator()->inContext($context)->validate(
                            $value,
                            CompanyConstraint::constraints(),
                        );

                        return;
                    }
                    if (is_array($value) && array_key_exists('@type', $value) && $value['@type'] === 'Person') {
                        $context->getValidator()->inContext($context)->validate(
                            $value,
                            PersonConstraint::constraints(),
                        );

                        return;
                    }
                    $context->buildViolation('This value matched none of the expected shapes: UnknownEntity, Organization, Company, Person.')->addViolation();
                })]),
                'consignee' => new Optional([new NotNull(), new Callback(static function (mixed $value, ExecutionContextInterface $context): void {
                    if (null === $value) {
                        return;
                    }
                    if (is_array($value) && array_key_exists('@type', $value) && $value['@type'] === 'UnknownEntity') {
                        $context->getValidator()->inContext($context)->validate(
                            $value,
                            UnknownEntityConstraint::constraints(),
                        );

                        return;
                    }
                    if (is_array($value) && array_key_exists('@type', $value) && $value['@type'] === 'Organization') {
                        $context->getValidator()->inContext($context)->validate(
                            $value,
                            OrganizationConstraint::constraints(),
                        );

                        return;
                    }
                    if (is_array($value) && array_key_exists('@type', $value) && $value['@type'] === 'Company') {
                        $context->getValidator()->inContext($context)->validate(
                            $value,
                            CompanyConstraint::constraints(),
                        );

                        return;
                    }
                    if (is_array($value) && array_key_exists('@type', $value) && $value['@type'] === 'Person') {
                        $context->getValidator()->inContext($context)->validate(
                            $value,
                            PersonConstraint::constraints(),
                        );

                        return;
                    }
                    $context->buildViolation('This value matched none of the expected shapes: UnknownEntity, Organization, Company, Person.')->addViolation();
                })]),
                'proofOfDelivery' => new Optional([new NotNull(), ...ProofOfDeliveryConstraint::constraints()]),
                'proofOfDeliverySignedAvailable' => new Optional([new Type(['bool']), new NotNull()]),
                'totalNumberOfPieces' => new Optional([new Type(['integer']), new NotNull()]),
                'pieceIds' => new Optional([new All([new Type(['string'])]), new Type(['array']), new NotNull()]),
                'weight' => new Optional([new NotNull(), ...QuantitativeValueConstraint::constraints()]),
                'volume' => new Optional([new NotNull(), ...QuantitativeValueConstraint::constraints()]),
                'loadingMeters' => new Optional([new Type(['number']), new NotNull()]),
                'dimensions' => new Optional([new NotNull(), ...DimensionsConstraint::constraints()]),
                'references' => new Optional([new All([...ReferenceConstraint::constraints()]), new Type(['array']), new NotNull()]),
                'valueAddedServices' => new Optional([new NotNull(), ...ValueAddedServicesConstraint::constraints()]),
                'controlledDataCodes' => new Optional([new All([new Type(['string']), new Choice(null, ['consignee-city', 'servicepoint-facilityId', 'servicepoint-url', 'shipper-city', 'signatory-name'])]), new Type(['array']), new NotNull()]),
                'shipmentActivationDate' => new Optional([new Type(['string']), new NotNull()]),
                'dgf:routes' => new Optional([new All([...DgfRouteConstraint::constraints()]), new Type(['array']), new NotNull()]),
                'telemetry' => new Optional([new Type(['array']), new NotNull(), new All([...MeasurementConstraint::constraints()])]),
            ], null, null, true),
        ];
    }
}
