<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlUnifiedShipmentTracking\Validator;

use Override;
use Prefabcortex\DhlUnifiedShipmentTracking\Model\UnknownEntity;
use Symfony\Component\Validator\Constraints\Callback;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Required;
use Symfony\Component\Validator\Constraints\Type;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * The rules a document for {@see UnknownEntity} has to satisfy.
 */
final class UnknownEntityConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                '@type' => new Required([new Type(['string']), new NotNull()]),
                '@policy' => new Optional([
                    new Callback(static function (mixed $value, ExecutionContextInterface $context): void {
                        if (null !== $value) {
                            $context->getValidator()->inContext($context)->validate(
                                $value,
                                SecretPolicyConstraint::constraints(),
                            );
                        }
                    }),
                ]),
                'familyName' => new Optional([new Type(['string']), new NotNull()]),
                'givenName' => new Optional([new Type(['string']), new NotNull()]),
                'name' => new Optional([new Type(['string']), new NotNull()]),
                'organizationName' => new Optional([new Type(['string']), new NotNull()]),
                'address' => new Optional([new NotNull(), ...SecuredAddressConstraint::constraints()]),
            ], null, null, true),
        ];
    }
}
